### ISSUE TITLE
Permit XML whitespace in base64 data.

### ISSUE THREAD

**Issue by skynavga** [w3c/ttml2#1003]
See also https://github.com/w3c/ttml2-tests/issues/185#issuecomment-423238917.

**Comment by nigelmegitt** [comment]
According to the man page for `base64` there is an option to insert line breaks every _n_ characters when base64 encoding, but I haven't had chance to check if that changes all the bytes or just chops the encoded output and inserts additional characters. 

If we do allow white space we should be clear about how decoding is supposed to happen, i.e. if the processor is expected to strip all the white space before decoding, or if it is supposed to permit some specific white space to remain in the string passed to the decoder.

**Comment by nigelmegitt** [comment]
That would work for me.

**Comment by skynavga** [comment]
Marking this issue as a bug since the omission of interspersed LWSP in encoded data was an oversight.
