### ISSUE TITLE
Remove 'available' keyword from <measure>.

### ISSUE THREAD

**Issue by skynavga** [w3c/ttml2#1004]
The `available` keyword was drafted in early 2015 based on the `fill-available` keyword defined in a 2012 WD  of CSS Sizing Level 3. It has since been moved out to CSS Sizing Level 4 (as `stretch-fit`) where its details are not yet specified.

Since use of this keyword falls under `#extent-measure`, `#ipd`, and `#bpd`, all of which are marked at risk, I propose we remove it now rather than deprecating/obsoleting it in 2e.

In any case, I think the current definition we have is not sufficiently well-defined to permit creating test content at this juncture, so it would have to remain untested if we leave it in 1e.

**Comment by skynavga** [comment]
@palemieux I can't figure out what the current definition (in TTML2) means, i.e., how to translate it into a test. Apparently the CSSWG had similar problems if you read the history of their numerous rewrites of the notion of "stretch fit".

**Comment by skynavga** [comment]
For further reference, see the following

[1] https://www.w3.org/TR/2012/WD-css3-sizing-20120927/#width-height-keywords

>**fill-available** extent
>Roughly, the extent a box would take if it filled its available extent. (See Intrinsic Size Determination.)

[2] https://www.w3.org/TR/2016/WD-css-sizing-3-20160510/#width-height-keywords

>**fill**
>Use the fill-available inline size or fill-available block size, as appropriate to the writing mode.

[3] https://www.w3.org/TR/2017/WD-css-sizing-3-20170207/#width-height-keywords
>**stretch**
>Use the stretch-fit inline size or stretch-fit block size, as appropriate to the writing mode.
>
>NOTE: This is the formula used to calculate auto widths for non-replaced blocks in normal flow, see CSS2.1§10.3.3. It allows re-using this formula for boxes that are otherwise shrink-wrapped, like tables.

[4] https://www.w3.org/TR/2018/WD-css-sizing-3-20180304/#sizing-values

Here, there is no longer a keyword or definition, but instead we find:

>Note: This section previously defined stretch and fit-content as keywords representing the stretch-fit size and fit-content size, respectively. These keywords have been deferred to Level 4 (along with an additional contain keyword that behaves similarly to stretch but preserves the intrinsic aspect ratio, if any) to better work out the implications in situations with indefinite available space.

[5] https://drafts.csswg.org/css-sizing-4/#width-height-keywords

Just a heading, without any content.

**Comment by skynavga** [comment]
Some relevant background on the origin of this feature in TTML2 is https://www.w3.org/wiki/TTML/changeProposal015#shrink_fit. The main use case for this is something like: `<region tts:extent="fitContent fitContent"/>`.

We might want to introduce a shorthand for this in 2e: `<region tts:extent="fit"/>`.

**Comment by nigelmegitt** [comment]
For ease of reference the current definition of `available` in [`<measure>`](https://www.w3.org/TR/ttml2/#style-value-measure) is:

> For ipd, the numeric value equal to the ipd of the parent containing block's ipd less the current element's combined border and padding ipd. For bpd, the numeric value equal to the bpd of the parent containing block's bpd less the current element's combined border and padding bpd.

@skynavga is your point here that there is a circular dependency, and that we have no rule to resolve the parent containing block's ipd|bpd without knowing the ipd|bpd of the element whose size is being defined using `available`? I'm not 100% sure if I understood the CSS issue right, but that's the sense I got from that discussion.

If this is the case, then it seems that the context is relevant: in the case where the parent containing block is, say, a `p`, then the ipd of the parent containing block is known and fixed but the bpd is not; conversely if the parent containing block is a region, or the root container region, then both the ipd and bpd are known.

So, though it's rather late in the process to consider substantive changes of this form, another path here would be to qualify the usage depending on what information is known and fixed. I think on balance I'd prefer just removing the feature as per the issue and revisiting it in 2e if there's a use case for it.

**Comment by skynavga** [comment]
Merge early for PR processing.
