### ISSUE TITLE
Add audio styling attributes to Table 5-5.

### ISSUE THREAD

**Issue by skynavga** [w3c/ttml2#1009]
It appears that the `tta:*` attributes were inadvertently left out of Table 5-5.

**Comment by skynavga** [comment]
Marking as editorial as I believe their (semantic) inclusion in the Styling Attributes module is established elsewhere. Note that it may be better to add a new row (module) in this table labeled Audio Styling Attributes.

**Comment by nigelmegitt** [comment]
Sounds like a good solution to me.
