### ISSUE TITLE
Add a syntactic shortcut for an implied audio element.

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/ttml2#1013]
If a `span` has `tta:speak` set to something other than `"none"` then currently it generates an audio resource but it is not clear that the audio resource should play, unless the `span` has a child `audio` element with `src="http://www.w3.org/ns/ttml/resource/#speech"`. That has the benefit that the `audio` element provides a home for potential `tta:gain` and `tta:pan` attributes, but if they are not needed, because their default values are fine, then it is rather verbose so I would like to introduce a syntactic shortcut that in the absence of such an `audio` child element, one is assumed.

I'd also like to avoid the need for the `src="http://www.w3.org/ns/ttml/resource/#speech"` attribute altogether for an `audio` element as a child of a `span` for which speech synthesis is enabled. I would propose that omitting both the `src` attribute and a `source` child in that case should suffice.

**Comment by skynavga** [comment]
@nigelmegitt IIRC, you are proposing that the following are equivalent:

**full syntax**

```
<span tts:speak="normal">
  <audio src="http://www.w3.org/ns/ttml/resource/#speech"/>
  Some Text
</span>
```

**shortcut syntax**

```
<span tts:speak="normal">
  <audio/>
  Some Text
</span>
```

and, furthermore, that

```
<span tts:speak="normal">
  Some Text
</span>
```

produces no audio output.

Is this correct?

**Comment by nigelmegitt** [comment]
Yes @skynavga that's exactly correct.

**Comment by skynavga** [comment]
@nigelmegitt what are the intended semantics if an ancestor of a `span` is an audio generating element for which the audio source is the speech data resource? e.g., in the following, since `body` generates audio from the speech resource, then we don't need to imply `audio` on the `span` descendants of `body`

```
<body tta:speak="normal">
  <audio tta:gain="0.9" src="http://www.w3.org/ns/ttml/resource/#speech"/>
  <audio tta:gain="0.5" src="background.mp3"/>
  <div xml:id= "d1" tta:speak="none">...</div>   <!-- no speech -->
  <div xml:id= "d2">
    <p>
      <span>one</span>                           <!-- normal speech rate -->
      <span tta:speak="fast">two</span>          <!-- fast speech rate -->
      <span>three</span>                         <!-- normal speech rate -->
    </p>
  <div xml:id= "d3" tta:speak="none">...</div>   <!-- no speech -->
</body>
```

**Comment by skynavga** [comment]
@nigelmegitt re: https://github.com/w3c/ttml2/issues/1013#issuecomment-533864684, I have (in PR #1167 just posted) handled this by not implying an `audio` element (or source) when an ancestor is an audio generating element with a speech source, which means if such an ancestor exists and a descendent `span` wishes to specify other audio properties, e.g., gain, then they will need to use the second rule, e.g., `<audio tta:gain="0.5"/>` to get an implied speech source.
