### ISSUE TITLE
Allow audio element as a child of body.

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/ttml2#1014]
The `body` element does not permit a child `audio` element, but the exclusion seems unmotivated. Either motivate its exclusion or permit its inclusion.

**Comment by skynavga** [comment]
There appears to be no authorial requirement for this proposed change that cannot already be met by using an `audio` child of a `div`. If an author wants to associate audio with all `div` children of `body`, then the author can reparent these children to new, single `div` child of `body` and use `audio` with the outer `div`.

**Comment by skynavga** [comment]
As for motivating this treatment, there is no requirement to specify such motivation in the specification. I propose this issue be closed without taking further action in the spec.

**Comment by nigelmegitt** [comment]
There is an authorial application for allowing audio on body: `<body>` has the distinctive feature that there is only one of them. For the case where we want to pull in some audio explicitly from an external context by reference, such as programme audio, it's much easier to create an unambiguous profile that says "pull in the external audio track at the top level" than "create a `div` element, and pull in the audio there, and make that the only parent of the other content".

It's also easier to avoid coding an exception for one particular element type.

**Comment by skynavga** [comment]
I am willing to move forward on this in TTML3, but not in TTML2 since it is not a matter of fixing something broken, and since it constitutes new functionality in the sense that it changes the content model of `body`. Do you concur?

**Comment by nigelmegitt** [comment]
> Do you concur?

Not really, if feels like a substantive mistake in TTML2 actually and I'd prefer to fix it in 2nd Ed.

**Comment by skynavga** [comment]
On the basis that this was an unintentional omission from TTML2 1e, I'm going to proceed with creating a PR to address this issue. N.B. that this will entail a substantive change to a content model and thus require a schema change.

**Comment by skynavga** [comment]
Note further, that, for symmetry, we need to add `Embedded.class` rather than just `audio`, since `image` should also be permitted wherever `div` is permitted. At present, `image` is permitted as a block-level child of `div` but not as a block-level child of `body`, which is an additional argument that this was an unintentional omission.

**Comment by nigelmegitt** [comment]
I'd probably have preferred to handle the question about `image` as a separate issue, because I don't see the two cases as necessarily being directly analogous, but I'm happy to go along with this and fix it in a single PR, assuming that nobody objects to the `image` part specifically.
