### ISSUE TITLE
Constrain use of @type on data element for reference data embeddings.

### ISSUE THREAD

**Issue by skynavga** [w3c/ttml2#1022]
For `data` element, if `@type` is specified for a _reference data embedding_, then reference must not be to an _internal data source_; conversely, if reference is to an _external data source_, then `@type` should be specified.

Note that _reference data embedding_ needs to be added as a fourth content model described in the paragraph that follows the second note in §9.1.3. See also #1021.

**Comment by nigelmegitt** [comment]
@skynavga I'm struggling to understand what issue you're raising here, due to terminology. The spec doesn't define _reference data embedding_, only (from [data](https://www.w3.org/TR/ttml2/#embedded-content-vocabulary-data)) :

> the first is referred to as _simple data embedding_, the second as _chunked data embedding_, and the third as _sourced data embedding_.

Which one do you mean?

**Comment by skynavga** [comment]
@nigelmegitt I have just edited the first comment above to add a second paragraph. See also #1021 (where I tweaked the initial comment as well, referring to _reference data embedding_).

**Comment by nigelmegitt** [comment]
@skynavga Thanks, I edited a typo in that new paragraph, which referred back to this issue instead of 1021, which I think you meant.

**Comment by skynavga** [comment]
Correct. The basic idea is to push the `@type` specification closest to the data itself in case there is a chain of references. For references to external resources, specifying `@type` at the point of reference is fine; but for references to internal (embedded) resources, the `@type` should be specified only in the data defining context and not the data referencing context.

**Comment by skynavga** [comment]
This issue was partially addressed by #1132, which adds a definition for _reference data embedding_.
