### ISSUE TITLE
Note reliance on XSL-FO semantics w.r.t. tts:direction and tts:writingMode.

### ISSUE THREAD

**Issue by skynavga** [w3c/ttml2#1024]
Add `#direction-version-2` to cover new special inheritance semantics.

**Comment by nigelmegitt** [comment]
@skynavga Applying `tts:direction` to `p` doesn't seem to be a change - it's in both TTML1 and TTML2. However I see that the special inheritance semantics are new in TTML2 relative to TTML1.

**Comment by skynavga** [comment]
@nigelmegitt I've edited the initial comment to reflect your clarification.

**Comment by palemieux** [comment]
@nigelmegitt The special inheritance semantics are intended as a clarification and reflect those already specified at [XSL](https://www.w3.org/TR/xsl11/#direction).

**Comment by nigelmegitt** [comment]
@palemieux are you saying that there's no substantive difference so we don't need a new feature designator? 

I'm confused by your -1 on https://github.com/w3c/ttml2/issues/1024#issuecomment-451983750 - would you be able to explain what you didn't like about the comment?

**Comment by nigelmegitt** [comment]
I've added this to the agenda for tomorrow's call, noting that it is an incomplete conversation.

**Comment by palemieux** [comment]
For the record.

>I'm confused by your -1 on #1024 (comment) - would you be able to explain what you didn't like about the comment?

The thumbs down was relative to the second part of the comment: _However I see that the special inheritance semantics are new in TTML2 relative to TTML1._

**Comment by skynavga** [comment]
After review and discussion, it has been determined that the special inheritance semantics are not new in TTML2, but can be derived from XSL-FO 1.1 semantics as referenced by `tts:direction`. Accordingly, it is not necessary to add a new feature designation; however, an editorial note that refers to the XSL-FO 1.1 semantics is suggested as an editorial change.
