### ISSUE TITLE
Add top and bottom values to display align.

### ISSUE THREAD

**Issue by skynavga** [w3c/ttml2#1026]
Add `top` and `bottom` values to `tts:displayAlign` and add `#displayAlign-absolute feature`; N.B. we defined `#displayAlign-relative` in TTML2 but it constitutes all values in TTML1, which did not have absolute values (`top`, `bottom`).

**Comment by nigelmegitt** [comment]
@skynavga what's the motivation for this? Is `top` intended to be synonymous with `before` and `bottom` with `after`? Otherwise what is the difference?

**Comment by skynavga** [comment]
After researching this a bit further, I see that the absolute values `top` and `bottom` are supported by neither XSL-FO (`display-align`) or CSS Flex (`justify-content`), so I am closing this issue without further action.
