### ISSUE TITLE
Constrain value space of @use with tt:profile element.

### ISSUE THREAD

**Issue by skynavga** [w3c/ttml2#1029]
Constrain definition of `@use` with `ttp:profile` element such that the value cannot point to an internal fragment in a TTML document instance since that fragment cannot be a resource representing a Profile Definition Document instance; however, note that the URI (specified by `@use`) may still be non-absolute, since it can be absolutized via `xml:base` semantics.

**Comment by nigelmegitt** [comment]
Would such a constraint be testable? I'm thinking that it would likely be feasible to arrange for some combination of (server config + `xml:base` + relative `ttp:profile @use` value) that ends up resolving to a fragment of the same document even if at first glance they appear not to.

**Comment by nigelmegitt** [comment]
How does this issue interact with #1033 which seems to require that the `xml:base` processing is _not_ performed here?

**Comment by nigelmegitt** [comment]
OK that seems like a reasonable prohibition; I still suspect that it would be possible to define a redirect in a server from a URL without a fragment part to a URL that includes a fragment part, but I haven't had a chance to test that theory yet. In other words, I expect that if someone really wants to try hard to break this then they probably can.

**Comment by skynavga** [comment]
Note that an alternative to introducing this constraint is to widen the definition of `@use` to permit it to reference a `<fragment-profile-designator>`, in which case it would not be referencing a profile definition document. This would permit something like

```
<tt ttp:processorProfiles="#p2">
<head>
<ttp:profile xml:id="p1" use="ttml2-presentation">...</ttp:profile>
<ttp:profile xml:id="p2" use="#p1">...</ttp:profile>
</head>
</tt>
```

At present, this (`use="#p1"`) is not permitted since `#p1` does not reference a profile definition document.

**Comment by skynavga** [comment]
@nigelmegitt re: https://github.com/w3c/ttml2/issues/1029#issuecomment-452666025, any rewritten URL in a redirect chain that has to be resolved by a TTML content processor that constitutes a fragment would fail the _is it a profile definition document_ requirement.

**Comment by skynavga** [comment]
@nigelmegitt correct, if dereferencing a URL specified by `@use` (either directly or indirectly through a server) results in a reference to a fragment as opposed to an entire profile definition document resource, then that would violate the current requirement that `@use` dereferences a profile definition document resource (as a whole, and not as a fragment)
