### ISSUE TITLE
Add paragraph on use of {content,processor} profile overrides to §5.2.1.

### ISSUE THREAD

**Issue by skynavga** [w3c/ttml2#1031]
Add paragraph or note after the 5th paragraph or at the end of §5.2.1 that indicates that the document processing context may override either or both content and processor profile as declared by content author.

**Comment by nigelmegitt** [comment]
Isn't that already stated in the first Note in §5.2.1?

**Comment by skynavga** [comment]
@nigelmegitt regarding https://github.com/w3c/ttml2/issues/1031#issuecomment-452661610, no, that note does not say anything about overriding an author's declaration (of content or processor profile)
