### ISSUE TITLE
Note that profile combination is optional at the end of §5.2.1.

### ISSUE THREAD

**Issue by skynavga** [w3c/ttml2#1032]
Insert a note after the last paragraph of §5.2.1 indicating that profile combination is, itself, an optional feature that need not be supported by a given processor, and that, if profile combination is not supported, then the first supported profile applies. [Need to ensure there is also normative language elsewhere to back up this informative comment.]

**Comment by nigelmegitt** [comment]
I believe the normative language is in §E.2 table E-1 where the feature designators `#processorProfiles-combined` and `#contentProfiles-combined` are listed as optional.
