### ISSUE TITLE
Add IMSC profile designators to Table 5-2.

### ISSUE THREAD

**Issue by skynavga** [w3c/ttml2#1034]
At present, IMSC's use of profile designators in the TT Profile Namespace is technically out of compliance with TTML2 due to the following language:

**TTML2 (1e) §5.2.3**

>All profile designators which have the TT Profile Namespace as a prefix but are otherwise not listed in Table 5-2 – Profiles are reserved for future standardization, and must not appear in a conformant document instance.

To fix this, we need to add entries to Table 5-2 for IMSC's text and image profiles (both 1.0 and 1.1).

**Comment by skynavga** [comment]
@palemieux language equivalent to the above also appears in TTML1 (3e) in §5.2; you might want to open an issue in https://github.com/w3c/ttml1/issues

**Comment by palemieux** [comment]
+1 to https://github.com/w3c/ttml2/issues/1034#issuecomment-452664578 , with the added clarification that the use of the _TT Profile Namespace_ is reserved for W3C, unless already stated elsewhere or obvious.

**Comment by skynavga** [comment]
At present, the following language in §5.2.3 renders any document invalid that uses the IMSC profile designators, strictly on the basis of whether the designator is listed in Table 5-2 or not.

>All profile designators which have the TT Profile Namespace as a prefix but are otherwise not listed in Table 5-2 – Profiles are reserved for future standardization, and must not appear in a conformant document instance.

**Comment by nigelmegitt** [comment]
@skynavga https://github.com/w3c/ttml2/issues/1034#issuecomment-505320194 is confusing: it's a duplicate of the issue, which has already been discussed and an approach agreed. Please could you re-review the discussion on this issue?

**Comment by skynavga** [comment]
Thanks for pointing that out. I will delete the (redundant) comment.

**Comment by skynavga** [comment]
Ah, right. I will change the PR to normatively reference to the profiles registry document instead of further enumerating profiles in TTML itself.

**Comment by nigelmegitt** [comment]
Thank you @skynavga - does it need to be normative?

I think it can be informative: the TTML profiles registry is merely one listed location where W3C might publish TTML profiles. 

I agree the normative statement does need to be changed: it needs to say that W3C can publish profiles of TTML, rather than requiring them to be within the TTML specification itself.

**Comment by skynavga** [comment]
It must be a normative reference since it is referred to in normative text and has real conformance impact (which is why this issue and PR are marked as substantive).

**Comment by skynavga** [comment]
@nigelmegitt also, there is (and will be) only one TTML profile registry, regardless of where the profiles themselves are published

**Comment by nigelmegitt** [comment]
@skynavga regarding https://github.com/w3c/ttml2/issues/1034#issuecomment-505320194 in the future please do not delete comments; for consistency and the archive if you need to advise the group that a comment was in error, add a new message asking for the previous one to be disregarded. @plehegar tells me that this is what he would generally expect in line with the W3C's archive policies.

**Comment by nigelmegitt** [comment]
@skynavga ok, I'm persuaded it needs to be normative.

**Comment by skynavga** [comment]
@nigelmegitt regarding deletion of comments, I will delete any of my own comments I like; if someone wants to look at the prior content of the comment, they only have to click on the "edited" link to see past history
