### ISSUE TITLE
Constrain <fragment-profile-designator> to reference top-level profile element.

### ISSUE THREAD

**Issue by skynavga** [w3c/ttml2#1038]
In §8.3.8, constrain `<fragment-profile-designator>` to reference only top-level `tt:profile` elements, which is to say, references are not permitted to nested `tt:profile` elements.

**Comment by nigelmegitt** [comment]
This is confusing because the only use of `<fragment-profile-designator> ` is in the "constituents" of a [profile instance] where the normative text currently says:

> If profile is a nesting profile, then an ordered list of `<fragment-profile-designator>` expressions, where each designator denotes a constituent nested profile; otherwise, `null`.

If you want to constrain references _not_ to be nested profiles then we can remove `<fragment-profile-designator>` altogether, since it would be unusable in any context in the specification as it stands.

**Comment by palemieux** [comment]
Is the idea that `<fragment-profile-designator>` are not subject to the reference resolution procedure of RFC 3986, or that a different base URI than that potentially specified by `xml:base` applies?

**Comment by skynavga** [comment]
@nigelmegitt re: https://github.com/w3c/ttml2/issues/1038#issuecomment-479810664, I think you failed to note that `<fragment-profile-designator>` is also used in the definition of `<profile-designator>`, which is used in many contexts

**Comment by nigelmegitt** [comment]
@skynavga you're right, I don't know how I missed that, thanks for the correction.

**Comment by skynavga** [comment]
@palemieux re: https://github.com/w3c/ttml2/issues/1038#issuecomment-496715234, the intent of this PR (and issue) is to ensure that the following language from §5.2.3 is reflected elsewhere in the specification:

>A profile is referenced in one of two ways according to whether the profile is defined externally to the referring document or is defined inline within the referring document. When defined externally, a profile is referenced by means of an `<absolute-profile-designator>` or `<relative-profile-designator>` expression. When defined internally (inline), a profile is referenced either implicitly or by means of a `<fragment-profile-designator>` expression.

Special base processing semantics only applies in the case of `<relative-profile-designator>`. Note that the lexical space of `<relative-profile-designator>` and `<fragment-profile-designator>` do not intersect (or at least that is the intention).

**Comment by skynavga** [comment]
@palemieux to correct my above comment, this issue is intended to constrain the use of `<fragment-profile-designator>` even further than merely being an _internally_ defined profile. In particular, the intent is that top-level profile elements can be referenced by a `<fragment-profile-designator>` and that nested profiles cannot be thus referenced.
