### ISSUE TITLE
Define default value for xlink:show.

### ISSUE THREAD

**Issue by skynavga** [w3c/ttml2#1040]
Specify a default value for `xlink:show` in §8.2.5, where the possible values are `new`, `replace`, `embed`, `other`, `none`. In the case of TTML, my suggestion is to use `none`, which is assigned the following semantics in [XLink 1.1]:

>The behavior of an application traversing to the ending resource is unconstrained by this specification. No other markup is present to help the application determine the appropriate behavior.

Alternatively, consider that SVG 1.1 restricts the value of `xlink:show` to `new` and `replace` (in similar linking contexts) and assigns a default value of `replace`. However, for TTML captions, I suspect that the default linking behavior should not replace the subtitle presentation; therefore, it seems better to make show semantics application dependent, which is accomplished by `none` (or perhaps `other`).

**Comment by nigelmegitt** [comment]
+1 to `none`.

**Comment by skynavga** [comment]
I just noticed that a default value of `new` is already specified for `xlink:show` under the syntax definitions for `span` and `image`. I don't mind changing these to `none`; however, that would effectively be backward incompatible with TTML2 1e. We do have precedent for changing a default value in this fashion (`ttp:markerMode`) in TTML 2e, where we added the note:

>**Note:** The default value for this parameter was originally specified (in TTML 1.0 First Edition) as continuous; however, further evaluation of the state of the industry indicates this choice was incorrect, and that the most common default is discontinuous.

**Comment by nigelmegitt** [comment]
`none` would not invalidate any existing implementations that implement the default of `new`, since the behaviour of `new` would still be a reasonable implementation default.
