### ISSUE TITLE
Clarify that font resources cannot override generic font families.

### ISSUE THREAD

**Issue by palemieux** [w3c/ttml2#1042]
See https://lists.w3.org/Archives/Public/public-tt/2019Jan/0052.html

**Comment by nigelmegitt** [comment]
The pull request for this differs significantly from the alternative proposal I made, in particularly not including any update to 9.1.4, so added this to the agenda for discussion to avoid looping round with lots of comments on the issue or the pull request.

**Comment by skynavga** [comment]
So, I disagree with your alternate proposal, as it is an orthogonal proposal that potentially breaks backward compatibility. The current text of this PR is (now) consistent with the existing language found in §10.3.15. Let's approve this PR (as modified), and then if you want you can open a new issue changing all font family comparisons to case-insensitive.

**Comment by nigelmegitt** [comment]
OK, I still think we need something in 9.1.4 though, as per my proposal bullet 2 in https://github.com/w3c/ttml2/issues/1042#issuecomment-473884872 but removing the words "case insensitively" before "matches". This could be a note of course.

**Comment by nigelmegitt** [comment]
Sorry for the noise, I realised that my previous proposal brought in the concept of quoted family names, which I think we don't have available (though I'm not sure why not). The revised proposal for a note in 9.1.4 removing this is:

If the `family` attribute matches a generic family name then it does not override the generic family of the same name, and cannot be referenced by a `tts:fontFamily` attribute value.

**Comment by skynavga** [comment]
@nigelmegitt firstly, is there a reason you are making these comments in the issue instead of the PR (#1049)? it is confusing to have to respond to comments in both places; secondly, what is wrong with the note proposed in the PR and how does your proposed rewrite help? [I don't see any improvement by your rewrite.]; please comment further in #1049, not here in the issue
