### ISSUE TITLE
`#timeContainer` feature designator has limited usefulness

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/ttml2#1065]
The [`#timeContainer`](https://www.w3.org/TR/ttml1/#feature-timeContainer) feature is coarse grained.

It allows support for `timeContainer` to be asserted by itself. Non-support for this only makes sense when in `ttp:timeBase="smpte" ttp:markerMode="discontinuous"` since in all other cases some form of time containment semantic must apply.

This can lead to an inconsistency where a profile apparently does not support [`#markerMode-discontinuous`](https://www.w3.org/TR/ttml1/#feature-markerMode-discontinuous) but also does not support `#timeContainer`].

It is also not possible currently for a profile to state that it supports only `par` or `seq` time containment semantics.

This is a problem when specifying a profile where the intent is that processors need only support one or the other.

I propose:

* [ ] Add a constraint that it is an error to prohibit both `#markerMode-discontinuous` and `#timeContainer`.
* [ ] Add new finer grained time containment feature designators for `par` and `seq` semantics.

**Comment by cconcolato** [comment]
Can you clarify why you think timeContainer and timeBase are linked?

**Comment by nigelmegitt** [comment]
@cconcolato I'm not completely sure I've understood your question. 

My thinking is that some kind of time containment must always apply in general; the only case in which it feasibly does not is when `timeBase="smpte" markerMode="discontinuous"` but even in that case it _could_ apply if the children of an element are only considered for potential activation when their parent element is active, regardless of whether that activation event was triggered by a time or a matching SMPTE timecode label.

Otherwise in all other cases some kind of time containment is always implied, otherwise time expressions are not being computed sensibly.

**Comment by cconcolato** [comment]
Thanks. On futher read, I understand your concern a bit more.
The definition of `#timeContainer` from [TTML1](https://www.w3.org/TR/ttml1/#feature-timeContainer) is:
>A TTML transformation processor supports the #timeContainer feature if it recognizes and is capable of transforming the timeContainer attribute.
> A TTML presentation processor supports the #timeContainer feature if it implements presentation semantic support for the timeContainer attribute.

My question is: if the `#timeContainer` feature is not supported, doesn't it mean that the default semantics apply:
> If a timeContainer attribute is not specified on an element that has time container semantics, then par time container semantics must apply.

This would seem consistent with the note:
>An additional side-effect of operating in discontinuous mode is that time expressions of children have no necessary relationship with time expressions of their temporal container; that is, temporal containers and children of these containers are temporally activated and inactivated independently based on the occurrence of a labeled synchronization (marker) event.

**Comment by nigelmegitt** [comment]
> if the `#timeContainer` feature is not supported, doesn't it mean that the default semantics apply

That's not obvious to me. It reads to me as though neither `seq` nor `par` semantics are implemented by a processor that doesn't support `#timeContainer`, and I don't know what that means unless in a discontinuous marker mode, as per the note you mention @cconcolato . I agree that _could_ be one interpretation though.

I don't follow how the note suggests that `par` semantics apply if `#timeContainer` is unsupported. Please could you explain more?

**Comment by skynavga** [comment]
I agree with Cyril that this is the only logical interpretation. If a processor doesn't support `#timeContainer` then any specified `@timeContainer` is actually ignored, which means the default semantic (`par`) applies. This is consistent with language throughout the spec of the form "must use the closest supported value." And what else could it possibly mean? It certainly should not mean _if `@timeContainer` is ignored, then `seq` semantics apply_.

**Comment by nigelmegitt** [comment]
> this is the only logical interpretation

@skynavga even when there is actually a scenario in which time containment does not apply at all?

**Comment by nigelmegitt** [comment]
>  It certainly should not mean _if `@timeContainer` is ignored, then `seq` semantics apply._

I agree with this.

**Comment by nigelmegitt** [comment]
"must use the closest supported value" is phrasing used on style properties where some measurement of closeness can be made. Here there are two values, so whichever is the "other" one is only the closest by exclusion of any other possibility. I don't think the comparison is helpful.

**Comment by skynavga** [comment]
@nigelmegitt re: https://github.com/w3c/ttml2/issues/1065#issuecomment-488683580, if you are referring to smpte discontinuous mode, `par` semantics still apply, except that in this case, they effectively have no meaning since they are all event based; I would suggest working out how this would work in SMIL to convince yourself that we can still say the `par` semantics always apply by default.

**Comment by nigelmegitt** [comment]
@skynavga I'd be very happy to agree that `par` semantics apply in smpte discontinuous mode - in the past we have had discussions that led me to believe that possibly you didn't think that is the case.

Rereading the spec, the feature is indeed about the ability to process the attribute, and omission of the attribute still has a defined semantic as described in this thread. It is true that profiles cannot currently specify that they _only_ support `seq` semantics, but I have no use case for such a profile. I'm going to close this issue as no action is required, though if a use case arises we could still consider adding finer grained features for each time containment semantic.

Thanks for spending the time considering this.
