### ISSUE TITLE
Clarify "considered an error".

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/ttml2#1067]
As discussed on today's call (w3c/ttwg#31) in the context of #1049, wherever a condition is described as "considered an error" without qualification of the processing context in which it is an error, this needs to be addressed.

For example, under tts:extent we have:

> All other syntactically legal values must not be used in this context, and, if used, must be considered an error for the purpose of validation processing and must be ignored for the purpose of presentation processing, in which case the initial value (auto) applies.

which is clear, whereas in other places such as under tts:rubyPosition, we have:

> If specified (on the former ruby text content), then it is considered an error, and must be ignored for the purpose of presentation processing.

There are currently 13 matches for "considered an error" in the spec, soon expected to be 14.

In all cases, it should be clear what the processor behaviour is if the incorrect usage occurs, for example:
* validation processor reports an error
* presentation processor either aborts or continues, and if continuing, what the error handling is, typically some syntax is ignored.

The fix for this should be forward-ported to TTML3 also.

If the fix results in normative changes then new or updated associated tests for validation processors and presentation processors may be needed, and are part of the fix for this issue.

**Comment by skynavga** [comment]
This would be a strictly editorial change. We can resolve by linking each "considered an error" to the text "a violation of a prescription or proscription of this specification" found under **[validation exception]** in §5.3.1.1.

**Comment by nigelmegitt** [comment]
That's neat  - also change "error" to "validation error" which seems to be defined there.

I'm not convinced that's purely editorial though. It could still be that additional tests would be needed to track the change.

**Comment by skynavga** [comment]
It is editorial since "considered an error" means (and has always meant) a "proscription", which, in the context of validation, means "a violation of a proscription" (if detected).

Resolving this issue does not entail adding or changing a proscription.

**Comment by nigelmegitt** [comment]
In most places we didn't define whether the error was a validation error, so if we clarify that and that creates scenarios in which a validating processor now has a specified behaviour, it follows that we need to check that tests exist that demonstrate that behaviour. It may be that we've already got the tests in place, of course.

**Comment by skynavga** [comment]
It has always meant validation error, i.e., a violation of a proscription. There is no other possible interpretation of "considered an error".

**Comment by skynavga** [comment]
From TTML1 1e §3.1 (5) - Document Conformance

>The Reduced XML Infoset satisfies all additional mandatory syntactic and semantic constraints defined by this specification.

The phrase "considered an error" defines a (syntactic or semantic) constraint, the violation of which makes the document invalid, ergo, a (detectable) validation error.

**Comment by nigelmegitt** [comment]
That's okay @skynavga for document instances, however if the semantic constraint is one that applies to processors only, then it is not reflected in the Reduced XML Infoset and this does not apply. I have checked all uses of the word "error" in the specification, and this isn't a big issue (possibly it is not an issue at all). I was prompted to do so by the note in §2.3 Document Conventions:

> For example, the phrases "treat X as an error" and "consider X as an error" are to be read as mandatory requirements in the context of use. 

My thinking was that if there are any contexts of use relating only to processors, we would need to be careful.

Actually there are two that fall into a borderline may-need-change category:

The [compute containment scaling] and [compute cover scaling] algorithms both have a step 1 that requires a _presentation_ processor to raise an error condition.

Conversely there are a lot of places in the spec where the phrase "error for the purpose of validation processing" is used, which we could simplify with this change.

**Comment by skynavga** [comment]
>The [compute containment scaling] and [compute cover scaling] algorithms both have a step 1 that requires a presentation processor to raise an error condition.

Actually, it does not specify presentation processor. The intent here was that the condition described be "considered an error" (in document conformance), so we should probably tweak that language.

>Conversely there are a lot of places in the spec where the phrase "error for the purpose of validation processing" is used, which we could simplify with this change.

Actually, we should not simplify that language, since it is written that way to distinguish error handling behavior between validation and presentation processing.

**Comment by nigelmegitt** [comment]
> it is written that way to distinguish error handling behavior between validation and presentation processing

I thought this change would define all "considered an error" language in terms of validation processing, though?
