### ISSUE TITLE
Create an `#audio-presentation` feature.

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/ttml2#1068]
The [`#presentation`](https://www.w3.org/TR/ttml1/#feature-presentation) feature designator requires support for region layout and presentation, and line layout, neither of which is relevant to a TTML2 presentation processor whose rendered output is only audio. 

This means that an audio-only profile of TTML2 would not necessarily support `#presentation` and therefore would not support the TTML2 Presentation Profile, the intent of which is to be a minimal profile for presentation. 

The consequence is it would be reasonable to define a kind of presentation processor profile that does not conform to the minimal presentation profile requirements, which sounds nonsensical.

I propose that we add a new feature designator that applies to audio presentation only, which does not include the constraints implied by visual text layout requirements. For completeness we also could consider creating a minimal TTML2 audio presentation processor profile.

**Comment by skynavga** [comment]
I am fine with adding a `#presentation-audio` feature in TTML2 2ed; however, add a new TTML2 Audio Presentation Profile is going to far, as it is most certainly adding new functionality, and will require a variety of changes to the conformance section. I suggest we consider the latter for TTML3, and not TTML2 2ed. In the mean time, I will publish a PR to ttml2 that adds a `#presentation-audio` feature.
