### ISSUE TITLE
The ittm:altText attribute should be in TT namespace in TTML 2.0

### ISSUE THREAD

**Issue by plehegar** [w3c/ttml2#107]
NOTE: This issue assumes that smpte:backgroundImage is also promoted to a TTML 2.0 namespace element or equivalent functionality (See ISSUE 238).

At present in IMSC, the smpte:backgroundImage element is used in a document conforming to the image profile as a child element of a containing div. However the *text equivalent* supported by the ittm:altText element must be placed as a child of a metadata element that is itself a child of that div. 

This position of the ittm:altText under a metadata child contradicts the 'equivalence' of the two elements and diminishes the value of the altText tag and unnecessarily increases the verbosity of the document.

Subject to ISSUE 238, it is suggested that ittm:altText should be deprecated in favour of a native ttml element that is placed at the *same document level* as any new TTML 2.0 background image element.

(raised by John Birch on 2014-07-23)
From tracker issue http://www.w3.org/AudioVideo/TT/tracker/issues/328

**Comment by skynavga** [comment]
The ``ttm:item`` element should be used to hold the alternate text. It would be a child of the ``tt:image`` element used as a content image, e.g.,

<pre>
&lt;div>
  &lt;image src="#localImage">
    &lt;ttm:item name='altText'>alternative text for local image&lt;/ttm:item>
  &lt;/image>
&lt;/div>
</pre>

Note that ``smpte:backgroundImage`` (in IMSC and SMPTE-TT) maps to the foreground image construct ``tt:image`` in TTML2. Background images in TTML2 are reserved for purely stylistic purposes, and not for representing content.

Action Item: add ``altText`` as a standard named metadata item.

**Comment by skynavga** [comment]
Committed.

**Comment by nigelmegitt** [comment]
See also 45665eb which is a related commit.
