### ISSUE TITLE
Unspecified mapping of shear percentage to shear angle.

### ISSUE THREAD

**Issue by palemieux** [w3c/ttml2#1075]
_10.4.5.3 Shear Calculations_ does not specify the algorithm for converting the shear percentage value into the shear angle.

FWIW, [imscJS](https://github.com/sandflow/imscJS/blob/7c3e9d0d5527e74f009a580aa033fdeb983586a6/src/main/js/html.js#L1270) currently uses `arcsin(<% value>)` although it is not clear why.

**Comment by skynavga** [comment]
The intended algorithm is shear angle = shear percentage * 90deg., i.e., that it be a linear mapping, which is what TTPE implements; arcsin(shear percentage) does not produce the intended mapping. I will post a PR that makes the mapping explicit.
