### ISSUE TITLE
Application of ruby align.

### ISSUE THREAD

**Issue by skynavga** [w3c/ttml2#1090]
For the sake of consistency, remove the text "only if the computed value of ``tts:ruby`` is ``container``" from the _applies to_ entry of the property definition table for `tts:rubyAlign`. Moreover, make clear (in prose) that the semantics of application is the empty set for spans for which the ``tts:ruby`` attribute's computed value is not ``container``.

**Comment by nigelmegitt** [comment]
I think this change would make the specification worse. I would prioritise usefulness over editorial consistency, here. If we do want editorial consistency I would prefer to introduce similar phrasing for other style attributes where the set of "applies to" elements is a subset of `span` elements and not all of them.

This is as per the discussion in last week's meeting documented at https://www.w3.org/2019/05/23-tt-minutes.html#item05

**Comment by skynavga** [comment]
Closing, with no further action considered necessary at this time.
