### ISSUE TITLE
Application of ruby position.

### ISSUE THREAD

**Issue by skynavga** [w3c/ttml2#1091]
For the sake of consistency, remove the text "only if the computed value of `tts:ruby` is `textContainer` or `text`" from the applies to entry of the property definition table for `tts:rubyPosition`. Moreover, ensure (in prose) that the semantics of application is the empty set for spans for which the `tts:ruby` attribute's computed value is not `textContainer` or `text`.

**Comment by nigelmegitt** [comment]
Same comment as https://github.com/w3c/ttml2/issues/1090#issuecomment-496449105

**Comment by skynavga** [comment]
Closing, with no further action considered necessary at this time.
