### ISSUE TITLE
Fix typo.

### ISSUE THREAD

**Issue by skynavga** [w3c/ttml2#1103]
s/semntically/semantically/ in definition of [non-content image]

**Comment by cconcolato** [comment]
I also noticed an extra 'either' in the definition of inline-region:
"An inline region is specified either explicitly by a region element child of certain content elements."

**Comment by skynavga** [comment]
@cconcolato regarding https://github.com/w3c/ttml2/issues/1103#issuecomment-497402771, I am not seeing that typo in the current master branch, so it looks like it has been taken care of in another PR;
