### ISSUE TITLE
Clarify meaning of significant text node.

### ISSUE THREAD

**Issue by skynavga** [w3c/ttml2#1105]

**Comment by cconcolato** [comment]
Today the term "significant text node" is used 4 times. 3 times in the context of the [construct anonymous spans] procedure. The other occurence is in https://www.w3.org/TR/ttml2/#isd-vocabulary-region. I think only this one needs to be clarified: either the [construct anonymous spans] procedure applies and it should be linked or another term should be used. For the other uses, I'm not sure anything is necessary. Maybe it should be clear that if the term is used in the future it should be in the context of the [construct anonymous procedure].

**Comment by skynavga** [comment]
@cconcolato no editorial change is strictly necessary; however, some of them may be useful for understanding; I, for one, have an operational understanding of "significant text node" already, since I am the one who wrote this phrase as such, and I meant "a text node that is not ignored" in some context of use; however, others (such as you), have pointed out that we don't define what "significant" means when applied to "text node": I agree that I didn't define the meaning, and, since you raised the question in the first place, I propose to define it in order to reduce or eliminate guessing on the part of the reader;

**Comment by skynavga** [comment]
@cconcolato I should also remind that we have two ways of defining terms: (1) by adding a definition of the term in §2.2 (I consider these heavy-weight definitions) and (2) by defining the term inline in the prose in the place of its first use by using `<termdef>...</termdef>` and referring to this definition subsequently using `<termref>...</termref>`, which renders as a link to the former (I consider these light-weight definitions); I intend to use the latter mechanism to resolve this issue;

**Comment by palemieux** [comment]
@cconcolato Do you interpret _for each significant text node in a content element_ as meaning _for each significant child text node in a content element_ or _for each significant descendant text node in a content element_?

**Comment by skynavga** [comment]
I'm interested in hearing @cconcolato 's answer, but my current thinking is that _significant text node in a content element_ is (without further clarification) ambiguous with regard to whether one is referring to only child text nodes of that element or to child text nodes and child text nodes of descendant elements of that element. I think my intended meaning was the former and not the latter; however, the presence of anonymous spans complicates matters, in which case it depends on whether one is talking about the state of the document tree before or after anonymous span construction.

**Comment by cconcolato** [comment]
@palemieux for the `audio` element it says:
> No text node descendant of an audio element is a significant text node for the purpose of performing the [construct anonymous spans] procedure.

In this case (and for the `image` element which has the same text), significant text node includes children and descendants.

In the [construct anonymous procedure](https://www.w3.org/TR/ttml2/#procedure-construct-anonymous-spans), I think it is meant to cover only child text nodes. I assume the procedure is called on child elements so it would take care of descendants but I could not find the text. 

Anyway, the fact that the `audio` and `image` text refers to descendant is probably not necessary but not hurting.

For ruby containers, if the procedure would use 'child', it should be fine too. 

Btw, I noted the following:
> If a sequence of children of a span element consists solely of character information items, then that sequence must be considered to be an anonymous span for the purpose of applying style properties that apply to span elements, for details about which, see the [construct anonymous spans] procedure.

Is it saying something more than what the construct anonymous procedure says?

**Comment by skynavga** [comment]
It turned out to be more complicated to define _significant text node_ than I had thought. I ended up with a heavy-weight definition for it, but light-weight definitions for _text node_, _element node_, and _data character_.
