### ISSUE TITLE
Add informative note to tts:luminanceGain that tts:luminanceGain is not relative to graphics white of the display

### ISSUE THREAD

**Issue by jmccrossan-fox** [w3c/ttml2#1117]
Currently the definition of luminanceGain states:
_"The tts:luminanceGain attribute is used to specify the absolute luminance of a region when its presentation requires a greater dynamic range than that provided by the [SRGB] color space, and when that presentation requires an absolute luminance value."_

To provide further clarity, consider adding an informative note to the above to advise that when tts:luminanceGain is applied during presentation it defines an absolute color & brightness, and it does not reflect a luminance level which is in relation to the graphics white of the display.

**Comment by nigelmegitt** [comment]
@jmccrossan-fox Thank you for raising this issue!

Please could you explain more about the motivation here? For example is there a reading of the current text that suggests a relative luminance level? Has this text caused confusion for an implementer for example, that needs to be resolved?

My reason for pushing for this is to make sure we have a clear idea of the problem that you've found, and therefore can assess any potential solution against that problem.

**Comment by jmccrossan-fox** [comment]
Hi @nigelmegitt thanks for reviewing!

In technical discussions that we have participated in, some technical experts have interpreted that “luminanceGain” is a gain relative to graphics white – probably due to the use of the word “gain” in the attribute. The current normative text states “the tts:luminanceGain attribute is used to specify the absolute luminance of a region ….” which I think is clear as a normative statement, but given the confusion encountered we believe there is benefit to adding an informative note explicitly highlighting that tts:luminanceGain is not relative to graphics white.

**Comment by skynavga** [comment]
This seems reasonable, I will create a PR to this effect. It is too bad that _gain_ was included in the name of this property. I don't recall the particulars of the history of the naming but it was poorly made for certain. Names are important and should reflect their intended semantics.

**Comment by skynavga** [comment]
Upon re-reading the current specification text, I have come to the conclusion that luminance gain does indeed specify a gain. If it were an absolute luminance, then it would have the units of candelas per square meter (or equivalent). But it is in fact unit-less, and functions as a multiplier with respect to 80 cd/m2 with a reference color of SRGB white. I will express the note accordingly.
