### ISSUE TITLE
J.1: `ttm:metadata` is used but `metadata` element is in TT namespace

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/ttml2#1121]
In appendix J.1 `ttm:metadata` is referenced 8 times - it links to [`metadata`](https://www.w3.org/TR/ttml2/#metadata-vocabulary-metadata) whose namespace does not match the prefix `ttm` - that element is in the namespace matching the `tt` prefix which by document convention is omitted. No element called `metadata` is defined by the spec in the `ttm` namespace.

Proposed fix: remove the `ttm:` prefix from all places where it is used before `metadata`.

**Comment by skynavga** [comment]
This is an editorial fix to the link text, since the correct element type is referenced by the link. Note also that the schemas are correct.
