### ISSUE TITLE
Ruby constraints cannot be validated prior to ISD construction

### ISSUE THREAD

**Issue by palemieux** [w3c/ttml2#1140]
Validation of ruby constraints can only happen after ISD construction since:

* the `tts:ruby` style property can be set using `initial` and impacted by conditionalized styles
* ruby constraints are specified in terms of the computed value of the `tts:ruby` style property

Is that the intent, or are should ruby style properties be specified solely using:
* inline styling
* referential styling
* chained referential styling
* nested styling

edit.: added impact of conditionalized styles

**Comment by skynavga** [comment]
At first order, I do not agree with this your statement that validation can only occur after ISD construction. If the initial value of `tts:ruby` is not changed by an `initial` element, then validation can occur before ISD construction. Notwithstanding this point, I do not know of a use case for changing the initial value of `tts:ruby`, so I would be happy to propose a PR that disallows such a change, i.e., by constraining the semantics of `initial`, or by specifying such constraint in the context of the definition of `tts:ruby`, which would be preferable (to preserve locality of reference).

**Comment by palemieux** [comment]
@skynavga What about the impact of using `condition` on a `style` element that specifies `tts:ruby`?

**Comment by skynavga** [comment]
Added to TPAC Agenda, https://www.w3.org/wiki/TimedText/tpac2019#Topics.

**Comment by nigelmegitt** [comment]
I see that #1146 has been opened before the TTWG has discussed this at length and worked out what we want to do with it. I will hold off any review of that pull request for the time being until we know what we need.

**Comment by skynavga** [comment]
@nigelmegitt are you suggesting there is something unusual about opening a PR before the WG has discussed an issue? it is my firm conviction that it is ALWAYS better to have a PR open by the editor before discussing an issue, and this has been typical for past practice as well; in fact, it is the duty of the editors to take the lead in proposing solutions to issues, which is what PRs are for; I sincerely hope you are not attempting to suggest there is an existing policy or propose a new policy that would require the WG to discuss an issue before an editor takes the initiative to draft a PR; further, I suggest we do not discuss this policy matter in this conversation, which is off topic;

**Comment by nigelmegitt** [comment]
@skynavga It's reasonable to have a concrete starting point for a discussion - I'm happy to treat this pull request as that.

**Comment by skynavga** [comment]
Per TPAC 2019 TTWG meeting, closing this PR without merging.
