### ISSUE TITLE
Update IANA registration for TTML2

### ISSUE THREAD

**Issue by plehegar** [w3c/ttml2#115]
Update the MIME type registration for TTML with IANA to include the processorProfiles parameter with syntax as described in the Codecs Registry page [1].

[1] https://www.w3.org/wiki/TTML/CodecsRegistry

(raised by Nigel Megitt on 2014-10-17)
From tracker issue http://www.w3.org/AudioVideo/TT/tracker/issues/351

**Comment by nigelmegitt** [comment]
Note that this is in progress based on the TTML profiles registry at http://w3c.github.io/tt-profile-registry/ .

**Comment by skynavga** [comment]
No action w.r.t. TTML2 itself.
