### ISSUE TITLE
Change 'descendant' (a person) to 'descendent' (an abstraction) throughout.

### ISSUE THREAD

**Issue by skynavga** [w3c/ttml2#1166]

**Comment by palemieux** [comment]
This should be deferred until a later milestone, or more information provided to motivate the urgency.

**Comment by skynavga** [comment]
@palemieux not to worry; just took me a minute; pls approve and we'll be done with this

**Comment by nigelmegitt** [comment]
Actually I disagree that it's a valid issue at all. We don't have an official dictionary, but my go-to is the Oxford English Dictionary and it says that:

* descendent is a variation of descendant that is now used in heraldry and very rarely is used to mean "that is coming or going down"
* descendant (adj.) carries both meanings, i.e. it can relate to a person or to a thing:

> In extended use: a person or thing whose origin may be traced to a particular source or predecessor; a machine, artefact, system, etc., that has developed from an earlier, esp. more rudimentary, version.

Using "descendent" would just be confusing and wrong by this definition.

I suggest closing with no change.

**Comment by skynavga** [comment]
Withdrawn.
