### ISSUE TITLE
Normatively define short code processorProfiles parameter

### ISSUE THREAD

**Issue by plehegar** [w3c/ttml2#117]
The ttp:processorProfiles parameter, to be used within in TTML2 documents, is already defined. A similar processorProfiles parameter for use externally to TTML2 documents, using registered short codes and syntax similar to that described in https://www.w3.org/wiki/TTML/CodecsRegistry is needed within the TTML2 specification as well, so that it can be normatively referenced.

This is a pre-requisite for updating the IANA registration of the MIME type, Issue-351.

(raised by Nigel Megitt on 2014-10-17)
From tracker issue http://www.w3.org/AudioVideo/TT/tracker/issues/353

**Comment by skynavga** [comment]
It has been decided that this will be done outside the scope of TTML2 proper.
