### ISSUE TITLE
CSS font-matching algorithm may introduce fingerprinting issues

### ISSUE THREAD

**Issue by npdoty** [w3c/ttml2#1202]
Review of TTML2 2nd Edition noted many potential fingerprinting vectors: https://github.com/w3c/ttml2/issues/1189
(Whether those issues present a privacy risk depends on a clearer understanding of what information is revealed by content processors to whom.)

Addition of external font loading and the CSS font-matching algorithm could introduce those fingerprinting issues to IMSC 1.2.

Mitigations for fingerprinting in CSS are under discussion now in CSSWG and PING.

More info in email: https://lists.w3.org/Archives/Public/public-privacy/2020JanMar/0055.html

**Comment by palemieux** [comment]
@npdoty See PR for your review.

**Comment by nigelmegitt** [comment]
I'm reopening this pending confirmation from @npdoty, @samuelweiler or PING more generally that the change made in #1203 and now merged addresses the issue, as requested at https://github.com/w3c/ttml2/pull/1203#issuecomment-638984684 on 4th June 2020.

**Comment by samuelweiler** [comment]
> I'm reopening this pending confirmation from @npdoty, @samuelweiler or PING more generally that the change made in #1203 and now merged addresses the issue, as requested at [#1203 (comment)](https://github.com/w3c/ttml2/pull/1203#issuecomment-638984684) on 4th June 2020.

Thank you, Nigel.  As in the PR, I am not satisfied.  I think a normative mitigation is in order.  Nick proposed a mere SHOULD, not a MUST - that gives implementers an out, if needed.

**Comment by nigelmegitt** [comment]
Understood @samuelweiler .

As per my action logged at https://github.com/w3c/ttml2/issues/1202#issuecomment-642737770 on 2020-06-11 I sent an email request to the Chairs of PING CC staff contacts of both groups, requesting a joint meeting between TTWG and PING to see if we could gain a better mutual understanding of each others' objectives, in the hope that we can reach to a resolution on this, given that there seems to be no proposal that is satisfactory to @samuelweiler and TTWG. At this time (2020-06-17Z0758) I have not yet had a response.

**Comment by skynavga** [comment]
@nigelmegitt re: https://github.com/w3c/ttml2/issues/1202#issuecomment-646097153, it is not clear to me that the comments of @samuelweiler represent a consensus PING position or represent his personal opinion; in any case, there are many precedents that permit us to decline to process their request for a normative change; we can simply resolve this by stating that the TTWG position is not to satisfy the requested change at this time; nothing in the process forces us to accept the change (in general or in the context of this specific CR);

**Comment by nigelmegitt** [comment]
@skynavga I agree, that is a possible course of action. As Chair, I am attempting to ensure that we have exhausted all routes to getting to a consensus view, and that includes @samuelweiler 's view regardless of whether it is a PING position or a personal one. If I am satisfied that we have exhausted all routes, then that only leaves the option that you describe.

**Comment by tairt** [comment]
@npdoty, @samuelweiler As I understand the motivation of PING is to provide privacy and security guidance, in this case on strategies to avoid fingerprinting issues in the context of font downloading.

As I understand the discussion in #1203 one of the questions is, if guiding text is made normative.

@npdoty proposed the following:

> A content processor SHOULD NOT dereference external font resources conditionally on the presence of user-installed fonts, where that dereferencing could reveal information about the user's system or fingerprint the user.

As the overall goal is to guide implementers in the right direction, could the following be an alternative (added as a Note):

> It is strongly encouraged to NOT dereference external font resources conditionally on the presence of user-installed fonts, where that dereferencing could reveal information about the user's system or fingerprint the user unless there are valid reasons and the full implications are understood and the case was carefully weighed before implementing.

This has essentially the same meaning (it uses the definition of SHOULD NOT in https://tools.ietf.org/html/rfc2119). The only difference is that it does not use normative keywords. But the text may highlight the guiding aspect even better?

**Comment by tairt** [comment]
@npdoty , @samuelweiler One additional option could be a more detailed guideline on how to avoid the fingerprinting on MDN (e.g. as a separate page in the IMSC chapter, https://developer.mozilla.org/en-US/docs/Related/IMSC). This would have the advantage that solutions can be updated more frequently, security, and TTML experts could work collaboratively on it and (at least in my opinion) the reach to implementers will be possibly better than in the specification itself.

**Comment by skynavga** [comment]
@tairt re: https://github.com/w3c/ttml2/issues/1202#issuecomment-648721821, I can accept your proposed language provided that: (1) change "It is strongly encouraged to NOT" to read "It is recommended that the the <loc href="#terms-document-processing-context">document processing context</loc> not", (2) change "the case was" to "the case is", and (3) appendix P remains non-normative. I should point out that we have precedent (in five notes) for the language "it is recommended" in other non-normative contexts in the specification text.

**Comment by skynavga** [comment]
Note that "document processing context" here should be linked to the terminology section, i.e.,

``<loc href="#terms-document-processing-context">document processing context</loc>``

**Comment by nigelmegitt** [comment]
Discussed on a call on 2020-07-27, minutes at https://www.w3.org/2020/07/27-tt-minutes.html

Chair's summary, based also on @plehegar 's statements at the end:
* TTWG to go ahead with the closest language that they can agree to the PING review request
* PING to consider their options given the changes
* TTWG and PING to continue to work together in the future to try to improve the mitigation to the issue raised

**Comment by skynavga** [comment]
I've drafted a new PR (#1210) that attempts to address the comments from PING, but without going as far as making the language normative. Nonetheless, I have included language "should consider not", which, in the present context (Appendix P), has a non-normative status. I would be willing to go as far as changing this to "should not" if folks prefer that. N.B. As I mentioned on today's call, we have precedent for using the language "should not" in non-normative text, so doing so would not introduce new precedent.

**Comment by samuelweiler** [comment]
> would not introduce new precedent.

Why the worry about precedents?

**Comment by skynavga** [comment]
@samuelweiler because we are a WG with 17 years of history which includes a history of established consensus about how to write specifications, what should and should not go into specifications, how testing is approached and a myriad of other details the sum of which form the basis for what traditional standards development organizations, such as ITU, ISO, ANSI, and others consider fair and best practice; in other words, its our body of convention; the PING, the IETF, and other SDOs, as well as individual editors, have their own conventions... you will find many distinct conventions within the W3C, for example, the HTML WG was comfortable publishing a spec (HTML5) that was largely untested and perhaps untestable in a significant way; however, the TTWG has not comfortable in doing so, as was mentioned by @nigelmegitt in our recent call; that represents a difference of convention, or, a difference in the role of precedent as it were

**Comment by nigelmegitt** [comment]
@npdoty #1210 was merged and published in TTML2 2nd Ed CR2 if you would like to confirm that the change represents at least an improvement.
