### ISSUE TITLE
Include better positioning example in Introduction

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/ttml2#1204]
From implementor feedback: the examples in the introduction at [1.2 Document Example](https://www.w3.org/TR/ttml2/#example) seem to suggest that specifying a `region` attribute on the `body` element is a good idea. 

However as we know from [[construct intermediate document]](https://www.w3.org/TR/ttml2/#procedure-construct-intermediate-document) step 3d, the effect of this is that if any descendant specifies a different region, then that descendant gets pruned. This is non-obvious to the casual reader, but the effect is that, except in simple cases, setting `@region` on `body` is probably a bad idea.

Another data point: setting `region` on `body` is prohibited in the EBU-TT-D profile.

I propose that we:

1. Change the TTML Body example fragment from:

```xml
<body region="subtitleArea">
  <div>
```

to:

```xml
<body>
  <div region="subtitleArea">
```

and

2. Add additional examples demonstrating positioning, perhaps with two regions defined, one at the top and one at the bottom, with content in both regions.

**Comment by skynavga** [comment]
Given that this example has been stable since TTML1 1e, I do not agree with this change, particularly in 2e.

**Comment by nigelmegitt** [comment]
This was discussed during w3c/ttwg#107, during which @skynavga suggested not changing the example but instead adding a note. This is now done in #1207, as well as adding a new example as per this issue.

**Comment by skynavga** [comment]
Note that my earlier objections are mooted by improvements made by proposer and subsequent approval of PR by myself.
