### ISSUE TITLE
Add 2nd edition change log?

### ISSUE THREAD

**Issue by samuelweiler** [w3c/ttml2#1245]
TTML2 has a log of differences v TTML1.  It might help the casual reader if the differences between TTML2 and TTML2 "(2nd Edition)" were also called out.

**Comment by skynavga** [comment]
There is. See https://www.w3.org/TR/2020/CR-ttml2-20200128/ttml2-changes.html#change-history-ttml2-1e-to-ttml2-2e.

**Comment by samuelweiler** [comment]
Perhaps that could be included in the base doc, or linked from it?

**Comment by skynavga** [comment]
It is (the latter). See link in the SOTD section.

**Comment by samuelweiler** [comment]
Great.  Thank you.
