### ISSUE TITLE
Permit `ttm:role` attribute in `ttm:desc` elements

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/ttml2#1247]
I've seen real world usage of the `ttm:role` attribute on `ttm:desc` elements, used to describe the purpose/type of description. Suggest in §14.2.2 adding [Metadata Items](https://www.w3.org/TR/ttml2/#element-vocab-type-metadata-items) alongside Content. It could also be useful on Data elements.

**Comment by nigelmegitt** [comment]
For example: https://w3c.github.io/adpt/#bbc-example-section includes:

```xml
      <p xml:id="ad61b" begin="62.24s" end="71.52s">
        <ttm:desc ttm:role="x-shotDescription">SHOT CHANGE: 62.36s Nick Cotton centre screen facing right.</ttm:desc>
```

**Comment by nigelmegitt** [comment]
I've been looking into the semantics of `ttm:role` specifically.

Currently, a `ttm:role` attribute on a `<metadata>` element defines role(s) applicable to the `<metadata>` element's parent element.

If we make this change, then the slightly unusual scenario occurs that the `ttm:role` attribute on a child of a `<metadata>` element would not be "inherited" by that `metadata` element's children. This is in contrast to `ttm:role` applied to content elements, where its values _do_ seem to apply to descendant content elements, though this is slightly unclear. See #1271 also.

**Comment by skynavga** [comment]
I can't envision `ttm:role` applying to a descendant of a `metadata` element, at least with respect to the TTML defined metadata vocabulary. Though I suppose one could invent a scenario where it might apply to foreign metadata vocabulary. On the other hand, it was never the intention that `ttm:role` would semantically apply to metadata, but would apply only to content data.

**Comment by nigelmegitt** [comment]
Closing with no change as discussed in TTWG meeting
