### ISSUE TITLE
Add ttm:mediaTimestamp (or equivalent) attribute

### ISSUE THREAD

**Issue by plehegar** [w3c/ttml2#125]
Define ttm:mediaTimestamp attribute (or equivalent) to allow author to explicitly associate a related 'begin' time in the document's time space with a specific timestamp in a related media object's time space. For precedent, see [1] for definition of X-TIMESTAMP-MAP.

[1] https://tools.ietf.org/html/draft-pantos-http-live-streaming-14

(raised by Glenn Adams on 2015-01-01)
From tracker issue http://www.w3.org/AudioVideo/TT/tracker/issues/361

**Comment by skynavga** [comment]
Already addressed by prior addition of ttp:mediaOffset.

**Comment by nigelmegitt** [comment]
Reopening: we have not added `ttp:mediaOffset` and when discussing it on multiple occasions I have raised an objection in advance to adding it on the grounds that it will create confusion where TTML documents are used or referenced in wrapper formats that already provide this functionality, such as ISOBMFF, and add a further unwelcome degree of complexity when processing time expressions in TTML. I also do not believe that a media offset would be an equivalent.

To reiterate previous discussions, I would instead like to see something that defines the playback entry point in the document's time space; it is a trivial extension to specify a cross-map between any time in the playback media timeline and any time in the document's time space. This is semantically much more useful than something that can potentially send some document times into negative values.

**Comment by skynavga** [comment]
ttp:mediaOffset is already present in the spec, and has been for at least 6 months or more

**Comment by skynavga** [comment]
Closing this again. You can file a new issue to remove ttp:mediaOffset if needed. BTW, I completely disagree with your claim about causing confusion if wrapper formats support this information. There are literally dozens of features in TTML you could make this claim against, and it is and has never been sufficient reason to not support internal specification of information.

**Comment by nigelmegitt** [comment]
I am puzzled as to why on one particular browser instance I was not seeing `ttp:mediaOffset` - on another I can now see that it is present. I will raise a separate issue.

**Comment by palemieux** [comment]
@skynavga Multiple members have consistently objected to `ttp:mediaOffset` (as recently as December 2016), so the editor's apparent unilateral decision to add it 6 months ago is not a particularly meaningful data point. At the very least, this should be added as a feature that can be prohibited by profiles.

**Comment by skynavga** [comment]
Sure, we can add a feature that facilitates profiling.
