### ISSUE TITLE
Incorrect illustration of example for tts:position

### ISSUE THREAD

**Issue by ed-gh** [w3c/ttml2#1269]
In the published recommendation, section 10.2.34 [1], the example illustration [2] does not correctly illustrate the prose and alignment depicted above the example. The associated region's visible bottom edge has a distance of 48px from/to the bottom edge of the postioning rectangle having a vertical extent of 480px. However, the prose specifies "A percentage value component for a horizontal position offset is relative to the width of the positioning rectangle minus the width of the associated region. A percentage value component for a vertical position offset is relative to the height of the positioning rectangle minus the height of the associated region.", therefore the distance between the positioning rectangle's and associated region's reference edge(s) should be (480 - 92) * 0.1 = 38.8px, for which the coverage of the pixels in the bottom pixel row was/is already set correctly (as was/is the top pixel row).

[1] https://www.w3.org/TR/ttml2/#style-attribute-position
[2] https://www.w3.org/TR/ttml2/images/position.png

Presumably correct version:
![ttml-position-9px-down](https://github.com/w3c/ttml2/assets/28450948/9b877a79-be60-41a0-8c6d-098268063ee9)

**Comment by skynavga** [comment]
In general, examples, including example renditions, are considered to be non-normative in all cases (unless explicitly specified to be normative renditions, of which there are none), whereas prose (text) in normative contexts is always normative (unless written in a Note). I would note, however, that this is not explicitly stated anywhere in the specification, although there are normative statements that tie layout and presentation semantics to a combination of XSL-FO and CSS models. For example, some of the prose and the _Percentage Based Positioning_ image of [1] is based on CSS Backgrounds and Borders, §3.6 [3] (renumbered as §2.6 in a more recent draft [4]).

I would suggest either (1) no change to the specification or (2) add a clarifying sentence to the last note in _Document Conventions_ [5] as follows:

>In addition, example renditions of example code fragments as well as other images not marked as example renditions are considered to be non-normative unless explicitly marked as normative.

[3] https://www.w3.org/TR/2017/CR-css-backgrounds-3-20171017/#the-background-position
[4] https://www.w3.org/TR/css-backgrounds-3/#propdef-background-position
[5] https://www.w3.org/TR/ttml2/#conventions

**Comment by nigelmegitt** [comment]
@ed-gh I think your calculation is wrong and the example is correct. As I read it the specification says that the point `(480 - 92) * 0.1 = 38.8px` up from the bottom of the overall rendering area (root container region) is coincident with the point `92 * 0.1 = 9.2px` up from the bottom of the region. So the bottom edge of the region is `38.8 + 9.2 = 48px` up from the bottom of the rendering area, as shown in the example.

When you quoted the text that explains what percentages are relative to, you omitted the following paragraph:

>The following image depicts a position value "75% 50%", where the rectangle with dashed line denotes the positioning rectangle and the rectangle with solid line denotes the region being positioned. In this case the region is positioned such that a vertical line located at 75% of its width coincides with a vertical line located at 75% of the width of the positioning rectangle, and a horizontal line located at 50% of its height coincides with a vertical line located at 50% of the width of the posititoning area.

and its associated diagram, that makes this at least a little clearer.

There is likely potential for making the specification even clearer about how this alignment works.

**Comment by ed-gh** [comment]
@nigelmegitt My understanding of the prose, in combination with the illustration preceded by the annotation which you are quoting, is that the  reference point calculated from the overall rendering area's dimensions times the percentages is supposed to coincide with the reference point calculated from the associated region's dimensions times the same percentages.
In the example, the "48px-from-bottom-edge-of-document" point should therefore equal the "9.2px-from-bottom-edge-of-region" point, resulting in a net distance of 38.8px between said edges.

@skynavga That may certainly be true / applicable / the way things are (supposed to be) done, however I'm thinking whenever there is a chance to remove or reduce ambiguity or contradictions, it is a good choice to do so, especially in the standards domain.

**Comment by nigelmegitt** [comment]
@ed-gh if I understand you correctly, you're saying that a point (or strictly, a line) _y<sub>1</sub>_ 10% up from the bottom of the overall rendering area should coincide with a point/line _y<sub>2</sub>_ 10% up from the bottom of the region?

That's not my interpretation of the text you quoted originally which states that _y<sub>1</sub>_ is relative to the height of the overall rendering area needs minus the height of the region.

**Comment by ed-gh** [comment]
@nigelmegitt re: point vs. line : yes, I should have written line where I did write point.

I *think* we are each having a different take on the (mathematical) association of words.

Quoting from @skynavga 's link [3] : 

> [...] With a value pair of 75% 50%, the point 75% across and 50% down the image is to be placed at the point 75% across and 50% down the area.

where 'image' (background image) is mapped to 'associated region' and 'area' mapped to '(overall) rendering area' in my concept.
That way, regardless of the references edges, or center/center as a point, no percentage in the range [0..100] can "push the associated region out of rendering area bounds", which can happen when applying your concept - which I hope to have understood correctly - (e.g. using the provided numbers and reference edges, but applying a vertical percentage of 100%, this would result in an offset of (480 - 92) * 1.0 + 92 from the bottom edge of the rendering area, and would therefore be outside of the rendering area.

**Comment by nigelmegitt** [comment]
Thanks @ed-gh , no, we're understanding the intent in exactly the same way. I'm not sure how you reach your conclusion though.

For example, you say that "(480px - 92px) * 1.0 + 92px" would be outside the rendering area, but that expression evaluates to 480px, which I'm seeing as exactly the position of the bottom edge, entirely as expected, and not outside the 0-100% range.

**Comment by ed-gh** [comment]
@nigelmegitt Sure, but if the entire rendering area has a height of 480px, and the distance between the bottom edge of the rendering area and the bottom edge of the associated region is 480px as well, the associated region is no longer within the rendering area.
Use my (somewhat convoluted) concept, the distance between the bottom edges calculates as 480px * 1.0 - 92 * 1.0 = 388px, which would have the entire associated region remain within the rendering area.

**Comment by nigelmegitt** [comment]
Ah, there's the difference. In this example, `bottom 100%`, it doesn't say the distance between the bottom edge of the rendering area and the bottom edge of the region is 480px in that example case. Instead, it says that the line within the region area, positioned 100% of the region height up from the region bottom edge, or in other words, the top edge of the region, is coincident with the line 100% of the rendering area up from the bottom of the rendering area, i.e. the top.

In other words, the alignment position (sometimes called the "anchor") in the vertical direction is 0px down from the top of the rendering area, and 0px down from the top of the region area. Thus the top edges align and the region is within the rendering area.

The intent of the specification is to match how CSS background positioning works. A good resource to look at for that is the [MDN page on `background-position`](https://developer.mozilla.org/en-US/docs/Web/CSS/background-position) - if you play with the position in the last of the "try it" examples you'll see that at bottom 0% the star is touching the bottom edge, and at bottom 100% it is touching the top edge, and it never goes outside the rendering area.

**Comment by nigelmegitt** [comment]
Ah, I begin to understand, with apologies @ed-gh. Just for my own peace of mind I ran the calculations from scratch `center bottom 10%`:

Translated to 4 component equivalent as per [`<position>`](https://www.w3.org/TR/ttml2/#style-value-position):

`center bottom 10%` -> `left 50% bottom 10%` -> `left 50% top (100% - 10%)` == `left 50% top 90%`

Root container region size is 640px 480px.
Region size is 308px 92px.

x-axis percentage basis is 640 - 308 = 332px
The left edge of the region is 50% of 332px i.e. 166px, which is correct for centering horizontally.

y-axis percentage basis is 480 - 92 = 388px
The top edge of the region is 90% of 388px = 349.2px, so the bottom edge is 349.2 + 92 = 441.2px down, equivalent to 38.8px up from the bottom of the rendering area.

This is the result you are reporting @ed-gh, if I understand correctly.

Also, it exactly mirrors what I would expect for `top 10%`, which is that the top edge is 38.8px down from the top of the rendering area. 

I no longer agree with https://github.com/w3c/ttml2/issues/1269#issuecomment-1903610311 and now do agree that the rendered example image is incorrect. It is true as @skynavga pointed out that it is informative content, but it is not useful to have _wrong_ informative content!

**Comment by ed-gh** [comment]
Sorry, there is one more thing I would like to see clarified:

If I am not mistaken, TTML2 does not specify a deviation (or exception) from the CSS calculation rules regarding Length values, therefore non-integer values would be illegal for e.g. position values, as far as presentation (rendering) is concerned.  
If that was the case, the interpolated (anti-aliased) boundary lines at the top and bottom of the region background depicted in the example would be incorrect, and the position values should be rounded to the nearest integer (in case of negative numbers, they should round towards positive infinity - this is not applicable in this example, just mentioning it for completeness).

Is this conclusion correct?

**Comment by skynavga** [comment]
No, it is not correct. In particular, the semantic rendering model for TTML2 is based on [XSL-FO 1.1](https://www.w3.org/TR/2006/REC-xsl11-20061205/), which, in turn, makes reference to [CSS2 1998](https://www.w3.org/TR/1998/REC-CSS2-19980512/). None if these specifications specify normative requirements or recommendations regarding sub-pixel rendering. Therefore, the presence or absence of sub-pixel rendering is left as an implementation detail. Furthermore, from a syntactic standpoint, the use of real-valued, non-integral `<length>` expressions, whether associated with the `px` unit or not, is permissible in all cases.

As for what length values are _illegal_, i.e., _invalid_, or not in a given context, TTML2 does not prescribe or proscribe the rendering semantics of non-integral values. Consequently, such usage constitutes UB (undefined behavior), and not illegal (invalid) rendering behavior or content.
