### ISSUE TITLE
Seeking clarification on behavior when RubyReserve and TextCombine are used together

### ISSUE THREAD

**Issue by swetha831** [w3c/ttml2#1276]
After consulting the TTML2 specification, issue #978 titled "Clarify that text combination is not defined in a ruby base or text context. #978", and the associated comment on GitHub (https://github.com/w3c/ttml2/issues/978#issuecomment-415927400)

> Further, CSS does not define the presentation semantics of text-combine-upright in a ruby context. It isn't even mentioned in the CSS Ruby Module. And the definition of text-combine-upright similarly does not mention usage in a ruby context. The existence of an implementation that supports such usage does not mean it is defined or sanctioned by the CSS specs. As the author of the TTML2 ruby and text combine features, I can assure you such a use case was not discussed or considered in drafting the current language. That makes it undefined in my book.

, it is clear that the behavior when using a ruby container in conjunction with the `textCombine` attribute is currently undefined.

I would like to verify if the behavior of the following code, which utilizes both `rubyReserve` and `textCombine`, is similarly undefined. 

```
xml
<p tts:rubyReserve="outside">
  <span tts:textCombine="all">1998</span><span>サンプル</span>
```

Note that we do not have a ruby container in this paragraph. However, the `tts:rubyReserve` specification states that an author can specify `rubyReserve` even if a ruby container is not present within the block. 
> "An author may use the `tts:rubyReserve` attribute to ensure that consecutive baselines of line areas in a block area maintain a fixed placement, irrespective of the presence or absence of ruby text annotations."

This implies that the above TTML is valid. Could you please confirm that the behavior is undefined?
Citations:
[1] https://github.com/w3c/ttml2/issues/978

**Comment by skynavga** [comment]
I believe the example you give is valid, and that the semantics of both `tts:rubyReserve` and `tts:textCombine` apply independently. In other words, I see no semantic conflict in applying both styles. Note, however that `tts:textCombine` only applies in the case of a vertical writing mode.

Further, I don't believe it is necessary to explicitly state this combination of styles is valid in the spec.
