### ISSUE TITLE
The tts:lineHeight property should apply to span

### ISSUE THREAD

**Issue by plehegar** [w3c/ttml2#131]
In order to control height of ruby annotation area, it is necessary to use tts:lineHeight on `<span tts:ruby="textContainer"/>` and possibly on `<span tts:ruby="text"/>`.

(raised by Glenn Adams on 2015-02-22)
From tracker issue http://www.w3.org/AudioVideo/TT/tracker/issues/373

**Comment by nigelmegitt** [comment]
@skynavga is this still the case or is the height now handled using `tts:bpd`?

**Comment by skynavga** [comment]
It still applies, as it is orthogonal to bpd.

**Comment by skynavga** [comment]
Incorporate resolution of these comments into #150 and closing this issue.
