### ISSUE TITLE
Clarify the application specific usages of clockMode="local"

### ISSUE THREAD

**Issue by plehegar** [w3c/ttml2#136]
Propose some words to allow:
1. 'whatever's local to you', 
2. an arbitrary clock reference (with extra metadata to indicate the clock source).

(raised by Nigel Megitt on 2015-04-09)
From tracker issue http://www.w3.org/AudioVideo/TT/tracker/issues/383

**Comment by nigelmegitt** [comment]
Note that something similar has been done in [EBU-TT Part 3](https://tech.ebu.ch/publications/tech3370) in which a reference clock identifier parameter is available for clarifying the intent behind `ttp:clockMode="local"`.

**Comment by skynavga** [comment]
Addressed in c36dffb71744a489372fe6a86ab303dc2f258a5d; closing with no further action required.

**Comment by nigelmegitt** [comment]
Noting that this was done without a pull request or review period, so members may wish to take a look as though this was "PR merged early".
