### ISSUE TITLE
The tts:displayAlign property may need to apply to content elements

### ISSUE THREAD

**Issue by plehegar** [w3c/ttml2#137]
especially if their children specify explicit bpd

(raised by Glenn Adams on 2015-04-10)
From tracker issue http://www.w3.org/AudioVideo/TT/tracker/issues/384

**Comment by nigelmegitt** [comment]
@skynavga are you any clearer at this time if `tts:displayAlign` is in fact needed for content elements? Would this be equivalent to the `vertical-align` CSS property?

**Comment by skynavga** [comment]
Absent specific market requirements, and absent a concrete proposal, I am marking this for ttml.next and closing. If someone wishes to submit a PR for TTML2, then you may re-open.

**Comment by skynavga** [comment]
After further consideration, I've determined that we do indeed need to apply display alignment to block level content elements since we allow tts:bpd to be applied to these content elements, and thus block level alignment in BPD is required.
