### ISSUE TITLE
There's no apparent use case for the "any" term in ttp:contentProfiles

### ISSUE THREAD

**Issue by plehegar** [w3c/ttml2#139]
There doesn't seem to be any reasonable use for the "any" term in ttp:contentProfiles. Propose removing it.

(raised by Pierre-Anthony Lemieux on 2015-04-10)
From tracker issue http://www.w3.org/AudioVideo/TT/tracker/issues/386

**Comment by nigelmegitt** [comment]
+1 to this - it is meaningless for a document to claim conformance to "any" of a list of content profiles.

**Comment by nigelmegitt** [comment]
Meeting 2017-04-13: Agreed to remove the "any" term from `ttp:contentProfiles` since it has no defined or intuitive meaning.
