### ISSUE TITLE
Embedded graphics don't fully meet requirement

### ISSUE THREAD

**Issue by plehegar** [w3c/ttml2#141]
Requirement R217 - Embedded Graphics is:

> The TT AF shall be capable of expressing block and inline, embedded graphics of both bitmap and vector or outline formats.
> 
> If block or inline graphics are used for the purpose of expressing pre-rasterized text in a bitmap format, then the original text that produced such a pre-rasterized form shall also be required to be present in TT AF content.

The current draft of TTML2 does not enforce the second part of the requirement, and permits that original text be omitted from the TTML content.

R218 - Non-Embedded Graphics likewise has the same sub-requirement.

(raised by Nigel Megitt on 2015-06-05)
From tracker issue http://www.w3.org/AudioVideo/TT/tracker/issues/389

**Comment by skynavga** [comment]
First, this would be a problem for translating from IMSC1 (in particular) to TTML2, so I think we cannot mandate alternate text inclusion. But we can certainly recommend it (should) be present.

**Comment by nigelmegitt** [comment]
I do not think we have a requirement to translate from IMSC1 to TTML2; however if we did then the translation of image profile documents would not be possible for those div elements that do not have an `ittm:altText` element. Even if the `altText` were present however it would probably not be possible to guarantee that its contents match the image within the `div` by any automated process.

However we do have a TTML requirement for this so we should meet that requirement, or change it.

**Comment by palemieux** [comment]
> However we do have a TTML requirement for this so we should meet that requirement, or change it.

The requirement that *the original text that produced such a pre-rasterized form shall also be required to be present in TT AF content* is not applicable to all applications, e.g. different information might be present if the objective is to allow indexing. As in the case of IMSC, a separate text subtitle/caption file really ought to be provided (so that styles, etc. can be expressed).

So I think this specific clause of R217 out to be removed (as currently drafted).

**Comment by nigelmegitt** [comment]
I thought you might say that @palemieux ! It probably is fair to say that whereas the requirement applies to an _authoring_ format, since the scope of TTML now includes _distribution_ the requirement is no longer applicable and the shall can be changed to a should.

**Comment by skynavga** [comment]
I have no plans to require authors to provide alt text in TTML2. At most,
we can recommend.

**Comment by palemieux** [comment]
Couple of potential solutions:

1. change `S` to `P` for R217 in Annex M
2. move Annex M to a wiki page (some of these requirements in https://www.w3.org/TR/2006/NOTE-ttaf1-req-20060427/ might no longer be valid, and some may be missing)
3. update https://www.w3.org/TR/2006/NOTE-ttaf1-req-20060427/

I would lean towards (2) at first glance.

**Comment by skynavga** [comment]
An alternative to (2) is simply to remove Annex M, which I would support (as it is the easiest); however, if someone wants to take on the work of moving it to a wiki, then I'd be happy to replace the content of Annex M with a reference to that wiki.

**Comment by nigelmegitt** [comment]
I rather like having Annex M, and it certainly helps answer the transition question about whether the spec meets the requirements. I don't mind keeping it up to date.

I notice that none of the options presented in https://github.com/w3c/ttml2/issues/141#issuecomment-300065553 is to modify the spec to meet the requirement. I still think we should consider the options for doing that, as a first order task. For example why not permit non-altText character content as normal in (sometimes anonymous) spans and specify a presentation precedence when both a foreground image and text is present? This could even be made conditional on presentation capabilities. I am not really clear how the document author could be forced to provide equivalent text, so in that sense maybe the requirement needs to be modified.

If we want to do anything with Annex M that should be a separate issue please. I would favour keeping it. If we need any changes to the original requirements document that would also be possible, though I am not aware of any changes in it other than to add AD requirements at some point.

**Comment by palemieux** [comment]
> I notice that none of the options presented in #141 (comment) is to modify the spec to meet the requirement. 

As discussed above, the _shall_ in "if block or inline graphics are used for the purpose of expressing pre-rasterized text in a bitmap format, then the original text that produced such a pre-rasterized form shall also be required to be present in TT AF content" does not make sense. I thought @nigelmegitt agreed, but perhaps not?

> I don't mind keeping it up to date.

This would mean tracking every addition in TTML2 and making sure it is matched to a requirement. Do you have time?

**Comment by nigelmegitt** [comment]
> This would mean tracking every addition in TTML2 and making sure it is matched to a requirement. 

Yes, I'm aware of that and happy to do it. I've done it before, by the way.

**Comment by skynavga** [comment]
Keep in mind that Annex M is strictly informative, so there is no material
requirement to keep it up to date. It's sole purpose is to provide
historical background.

**Comment by palemieux** [comment]
@nigelmegitt Can you confirm that you agree that the _shall also be required to be present_ in R217 is not correct?

**Comment by skynavga** [comment]
[Meeting 05/11/17] @nigelmegitt to produce PR that marks Annex M entry as P (partial) and adds note that authorial requirements are out of scope in this context, i.e., this is not a syntactic requirement but a usage requirement.

**Comment by skynavga** [comment]
Merge from #318 closes this issue.
