### ISSUE TITLE
Percentage and writing mode relative edges apply to tts:padding

### ISSUE THREAD

**Issue by skynavga** [w3c/ttml2#144]
Since TTML2 introduces padding on content elements (body, div, p, span), a better definition of percentages and edges is required.

**Comment by nigelmegitt** [comment]
There's no issue reference for this in the TTML2 WD - is this still current or has it been actioned but not referenced (question for @skynavga)?

**Comment by skynavga** [comment]
Not referenced but still actionable.

**Comment by palemieux** [comment]
> Since TTML2 introduces padding on content elements (body, div, p, span), a better definition of percentages and edges is required.

Why is padding necessary of elements other than `<region>`? Are the underlying use cases captured somewhere?

**Comment by skynavga** [comment]
Well, that is how TTML2 supports linePadding, i.e., as padding on span.

**Comment by palemieux** [comment]
> Well, that is how TTML2 supports linePadding, i.e., as padding on span.

As noted at https://lists.w3.org/Archives/Public/public-tt/2016Dec/0021.html, linePadding is not padding on `<span>`, but padding on *lines*. In other words, applying linePadding to a paragraph containing two spans (whether nested or consecutive), does not yield additional space between the spans.

**Comment by skynavga** [comment]
I didn't say which span, but I mean an anonymous span that is synthesized
to wrap the entire content of the paragraph.

**Comment by palemieux** [comment]
> I didn't say which span, but I mean an anonymous span that is synthesized
>to wrap the entire content of the paragraph.

This will not work is there is more than one span in the paragraph, and each one has a different background color.

**Comment by skynavga** [comment]
On Sat, Dec 17, 2016 at 9:44 PM, Pierre-Anthony Lemieux <
notifications@github.com> wrote:

> I didn't say which span, but I mean an anonymous span that is synthesized
> to wrap the entire content of the paragraph.
>
> This will not work is there is more than one span in the paragraph, and
> each one has a different background color.
>
Not necessarily. It depends on how we define behavior at line boundaries.
We are not obligated to limit ourselves to CSS tools to do this.

**Comment by palemieux** [comment]
I see no value in extending tts:padding to all content elements only to satisfy the narrow use case of linePadding, where in any case tts:padding would behave differently than it does on region. Using linePadding as it is used in EBU-TT-D and IMSC would achieve the same result, with fewer implementation requirements (no need to support padding outside of region) and smoother transition from EBU-TT-D and IMSC.

**Comment by skynavga** [comment]
This has been a long standing ask, along with border on content elements,
that goes back at least 3 years, which has effectively been provisionally
adopted by the group. If there are insufficient implementations to support
going to PR with this feature, then that will be the time to remove it.

**Comment by skynavga** [comment]
I should also add that, since this is supported by XSL-FO and CSS, we can't
argue against it due to lack of CSS support.

**Comment by palemieux** [comment]
> This has been a long standing ask, along with border on content
> elements, that goes back at least 3 years,

Can you point to the use case?

> I should also add that, since this is supported by XSL-FO and CSS, we can't
> argue against it due to lack of CSS support.

Right.

It is however possible to argue against adding CSS padding to meet the linePadding use case as currently specified in IMSC and EBU-TT-D since CSS padding does not in fact yield the expected result.

**Comment by skynavga** [comment]
On Sat, Dec 17, 2016 at 10:13 PM, Pierre-Anthony Lemieux <
notifications@github.com> wrote:

> This has been a long standing ask, along with border on content
> elements, that goes back at least 3 years,
>
> Can you point to the use case?
>
adding padding

> I should also add that, since this is supported by XSL-FO and CSS, we can't
> argue against it due to lack of CSS support.
>
> Right.
>
> It is however possible to argue against adding CSS padding to meet the
> linePadding use case as currently specified in IMSC and EBU-TT-D since CSS
> padding does not in fact yield the expected result.
>
supporting line padding is not the sole use case

**Comment by palemieux** [comment]
>>  Can you point to the use case?
> adding padding

What style of subtitles/captions require padding beyond region?

> supporting line padding is not the sole use case

It is in fact a different use case since it does not behave like CSS padding.

**Comment by skynavga** [comment]
On Sat, Dec 17, 2016 at 10:24 PM, Pierre-Anthony Lemieux <
notifications@github.com> wrote:

> Can you point to the use case?
> adding padding
>
> What style of subtitles/captions require padding beyond region?
>
those that wish to use padding on content elements; keep in mind that TTML
is not restricted to subtitles and captions

> supporting line padding is not the sole use case
>
> It is in fact a different use case since it does not behave like CSS
> padding.
>
not so, since we haven't yet defined background behavior at line boundaries

**Comment by nigelmegitt** [comment]
Marking as discussed and agreed as per the discussion in w3c/ttml1#205.

**Comment by skynavga** [comment]
Duplicate of #302.
