### ISSUE TITLE
Ways to make span background height be lineHeight

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/ttml2#150]
Address any outstanding comments under the following, which are hereby incorporated into this issue:

- [ ] #101 span background height
- [ ] #131 span line height
- [x] #163 clarify bpd

Many (most?) CSS implementations draw the background box behind inline areas with a height less than the line height, meaning that successive lines are drawn with gaps between their background areas, if there's no block level background color set. We want to be able to avoid that situation, since it negatively impacts readability and hence accessibility when background colors are applied to spans.

See also the discussions minuted [here](https://www.w3.org/2016/02/18-tt-minutes.html#item05) and [here](https://www.w3.org/2016/02/25-tt-minutes.html#item05) and [this thread](https://lists.w3.org/Archives/Public/public-tt/2016Feb/0104.html).
## First question: is the height actually defined?

[CSS 2 §10.6.1](https://www.w3.org/TR/CSS2/visudet.html#inline-non-replaced):

> The height of the content area should be based on the font, but this specification does not specify how. A UA may, e.g., use the em-box or the maximum ascender and descender of the font. (The latter would ensure that glyphs with parts above or below the em-box still fall within the content area, but leads to differently sized boxes for different fonts; the former would ensure authors can control background styling relative to the 'line-height', but leads to glyphs painting outside their content area.)
> 
> Note: level 3 of CSS will probably include a property to select which measure of the font is used for the content height.

See also §10.6.6 and §10.6.7 in that specification.

I'm still trying to work out what this means and whether it provides flexibility to implementers to make the inline box height be the same as the line height, or if there's some other calculation that applies.
## Second question: do we need syntax and semantics for clarifying it in TTML2?

Pending the answer to the first question.

**Comment by nigelmegitt** [comment]
### Further investigations relating to the first question: 

Looking at XSL-FO: [Backgrounds](https://www.w3.org/TR/xslfo20/#rend-border) are painted: 

> The background, if any, is rendered in the padding-rectangle, in accordance with the background-image, background-color, background-repeat, background-position-vertical, and background-position-horizontal traits.

Then in [Inline-areas](https://www.w3.org/TR/xslfo20/#area-inline), we have:

> An inline-area has its own line-height trait, which may be different from the line-height of its containing block-area. This may affect the placement of its ancestor line-area when the line-stacking-strategy is line-height.

This led me to try an experiment in CSS, where in an example that previously had gaps between lines I added the property: `line-height: inherit;` and that made the line spacing equal to the background area, in other words the lines got closer together and the gap between background areas no longer existed. 

However all I've really done here is reduced the line height to be the same as the padding rectangle, rather than increasing the size of the padding rectangle to be the line height in a reliable way, which is what I want to be able to do. The padding rectangle can of course be increased by applying padding, but that does not increase the line spacing, nor is it reliable since the actual used line height varies across implementations. 

Turning once again to CSS, and repeating the reference in the main issue description, the height of [inline, non-replaced elements](https://www.w3.org/TR/2011/REC-CSS2-20110607/visudet.html#inline-non-replaced) is possibly the place where different implementation practices are most clearly permitted (or perhaps accommodated):

> The 'height' property does not apply. The height of the content area should be based on the font, but this specification does not specify how. A UA may, e.g., use the em-box or the maximum ascender and descender of the font.

Furthermore: 

> The vertical padding, border and margin of an inline, non-replaced box start at the top and bottom of the content area, and has nothing to do with the 'line-height'. But only the 'line-height' is used when calculating the height of the line box.

But slightly hopefully:

> Note: level 3 of CSS will probably include a property to select which measure of the font is used for the content height.

But I can't find any evidence that this is actually happening. The [CSS Intrinic and Extrinsic Sizing Level 3](https://www.w3.org/TR/css3-sizing/) document hasn't been updated since 2012. The [CSS Inline Layout Module Level 3](https://www.w3.org/TR/css-inline-3/) is clearly being worked on, and has a request for width and height on initial letter, but does not otherwise address the size of the padding edge or the content height.

### Second question: do we need syntax and semantics?

It may well be that someone more expert in XSL-FO and/or CSS than me can point me in the right direction, but my feeling after this research is that the semantic that I believe we need is not defined in either of those specifications right now. Since it is implementable in CSS with some Javascript, I'd like us to define it in TTML2, share with CSSWG and proceed. In other words, yes, we need syntax and semantics.

### Third question: what are the syntax and semantics?

One way to do this is to modify the current definition of `tts:padding` in TTML2. Noting that the attribute only applies to region in TTML1 so we have some flexibility. My proposal is to add a new keyword to the style attribute, that may be used in place of a `<length>` specification when applied to the `span` element only:

Define a new measure for padding that is:

Values: `<padding-measure>` | `<padding-measure> <padding-measure>` | `<padding-measure> <padding-measure> <padding-measure>` | `<padding-measure> <padding-measure> <padding-measure> <padding-measure>` 

```
<padding-measure>: <length> | "line"
```

This has no effect in relation to start and end edges but may be used to replace a length expression to extend padding to the nearest line area edge in the relevant dimension or dimensions. 

When used in place of a length expression that applies to both the before and after padding edges, `"line"` extends the before padding edge to the before edge of the line area and the after padding edge to the after edge of the line area and does nothing to the start and end edges. 
When used in place of a length expression that applies to the before padding edge `"line"` extends the before padding edge to the before edge of the line area.
When used in place of a length expression that applies to the after padding edge `"line"` extends the after padding edge to the after edge of the line area.

When used in place of a length expression in a `tts:padding` attribute that applies to any element other than `<span>` `"line"` evaluates to zero.

**Comment by skynavga** [comment]
On Fri, Mar 4, 2016 at 9:17 AM, Nigel Megitt <notifications@github.com>
wrote:

> Further investigations relating to the first question:
>
> Looking at XSL-FO: Backgrounds
> <https://www.w3.org/TR/xslfo20/#rend-border> are painted:
>
> The background, if any, is rendered in the padding-rectangle, in
> accordance with the background-image, background-color, background-repeat,
> background-position-vertical, and background-position-horizontal traits.
>
> Then in Inline-areas <https://www.w3.org/TR/xslfo20/#area-inline>, we
> have:
>
> An inline-area has its own line-height trait, which may be different from
> the line-height of its containing block-area. This may affect the placement
> of its ancestor line-area when the line-stacking-strategy is line-height.
>
> This led me to try an experiment in CSS, where in an example that
> previously had gaps between lines I added the property: line-height:
> inherit; and that made the line spacing equal to the background area, in
> other words the lines got closer together and the gap between background
> areas no longer existed.
>
> However all I've really done here is reduced the line height to be the
> same as the padding rectangle, rather than increasing the size of the
> padding rectangle to be the line height in a reliable way, which is what I
> want to be able to do. The padding rectangle can of course be increased by
> applying padding, but that does not increase the line spacing, nor is it
> reliable since the actual used line height varies across implementations.
>
> Turning once again to CSS, and repeating the reference in the main issue
> description, the height of inline, non-replaced elements
> <https://www.w3.org/TR/2011/REC-CSS2-20110607/visudet.html#inline-non-replaced>
> is possibly the place where different implementation practices are most
> clearly permitted (or perhaps accommodated):
>
> The 'height' property does not apply. The height of the content area
> should be based on the font, but this specification does not specify how. A
> UA may, e.g., use the em-box or the maximum ascender and descender of the
> font.
>
> Furthermore:
>
> The vertical padding, border and margin of an inline, non-replaced box
> start at the top and bottom of the content area, and has nothing to do with
> the 'line-height'. But only the 'line-height' is used when calculating the
> height of the line box.
>
> But slightly hopefully:
>
> Note: level 3 of CSS will probably include a property to select which
> measure of the font is used for the content height.
>
> But I can't find any evidence that this is actually happening. The CSS
> Intrinic and Extrinsic Sizing Level 3 <https://www.w3.org/TR/css3-sizing/>
> document hasn't been updated since 2012. The CSS Inline Layout Module
> Level 3 <https://www.w3.org/TR/css-inline-3/> is clearly being worked on,
> and has a request for width and height on initial letter, but does not
> otherwise address the size of the padding edge or the content height.
> Second question: do we need syntax and semantics?
>
> It may well be that someone more expert in XSL-FO and/or CSS than me can
> point me in the right direction, but my feeling after this research is that
> the semantic that I believe we need is not defined in either of those
> specifications right now. Since it is implementable in CSS with some
> Javascript, I'd like us to define it in TTML2, share with CSSWG and
> proceed. In other words, yes, we need syntax and semantics.
>
agreed

> Third question: what are the syntax and semantics?
>
> One way to do this is to modify the current definition of tts:padding in
> TTML2.
>
I don't like overlaying this onto padding. It is clearly not padding that
we are talking about here. It is also entirely independent of padding in
the sense that padding may or may not apply independently.

What we really want to do here is specify the content block progression
dimension (bpd), aka content rectangle height, for an inline,
non-replaceable element. But we can't use 'bpd' (aka 'height') for this
purpose, since we have defined bpd to trigger application of inline-block
display semantics.

Perhaps one of the following:

   - contentBlockProgressionDimension (descriptive, but too long)
   - contentBpd (shorter)
   - bpdContent (postfix qualified short form, my preference)

Noting that the attribute only applies to region in TTML1 so we have some
> flexibility.
>
Not really. We are talking TTML2 here, and in TTML2 padding applies to
content elements as well.

> My proposal is to add a new keyword to the style attribute, that may be
> used in place of a <length> specification when applied to the span
> element only:
>
> Define a new measure for padding that is:
>
> Values: <padding-measure> | <padding-measure> <padding-measure> | <padding-measure>
> <padding-measure> <padding-measure> | <padding-measure> <padding-measure>
> <padding-measure> <padding-measure>
>
> <padding-measure>: <length> | "line"
>
> This has no effect in relation to start and end edges but may be used to
> replace a length expression to extend padding to the nearest line area edge
> in the relevant dimension or dimensions.
>
Again, I see padding as orthogonal, so this doesn't work for me.

> When used in place of a length expression that applies to both the before
> and after padding edges, "line" extends the before padding edge to the
> before edge of the line area and the after padding edge to the after edge
> of the line area and does nothing to the start and end edges.
> When used in place of a length expression that applies to the before
> padding edge "line" extends the before padding edge to the before edge of
> the line area.
> When used in place of a length expression that applies to the after
> padding edge "line" extends the after padding edge to the after edge of
> the line area.
>
I don't see a particular use case to separate the treatment of before and
after dimensions here; rather, the defined property should apply to the bpd
of the content area (box) as a whole.

> When used in place of a length expression in a tts:padding attribute that
> applies to any element other than <span> "line" evaluates to zero.
>
I think you are saying here that this property should apply only to areas
generated by inline, non-replaceable elements, but I need to give it some
more thought to convince myself it isn't more generally applicable.

So my counter proposal is something like:

bpdContent
  : auto                  // initial value ... implementation dependent
  | bpdBounds             // bpd of bounding box of content pixels
  | bpdFont               // bpd of em square of resolved font
  | bpdLine               // bpd of content area of nearest line area
ancestor
  | bpdLineLeaded         // bpdLine + 2*halfLeading
  | lineHeight            // resolved value of lineHeight property
  | <length>              // explicit length measure

**Comment by nigelmegitt** [comment]
>> One way to do this is to modify the current definition of tts:padding in TTML2.

>I don't like overlaying this onto padding. It is clearly not padding that
we are talking about here. It is also entirely independent of padding in
the sense that padding may or may not apply independently.

Okay, I have no problem with this - my thinking was that we're trying to size the padding rectangle correctly, hence adding semantics to `tts:padding` seemed to make sense. I'm also happy to separate out this semantic into a different conceptual thing that I'm thinking of as the starting point for the padding rectangle for inline areas. `tts:padding` would then be used to extend this padding rectangle as normal.

I think this is what you're referring to by using the term "content", i.e. you're referencing the XSL-FO Content Rectangle and the CSS Content Area, right?

So my view right now is let's go with the `bpdContent` proposal. I'm not particularly comfortable with the name, but that's not a big deal for me. The "bpd" part is not intuitive either here or on block level `tts:bpd` attributes, especially for readers unfamiliar with XSL-FO who therefore won't be expecting something that looks like "block-progression-dimension" (which as a further aside is described [here](https://www.w3.org/TR/2006/REC-xsl11-20061205/#block-progression-dimension) as a "Writing-mode Relative Equivalent of a CSS2 Property" without saying which property). 

Here we also have the potential confusion that both inline-areas and block-areas content rectangles, but we're only referring to the content rectangles of inline areas ("inline boxes" in CSS). So setting aside the "bpd" area maybe we should call it `tts:inlineContentBpd`. I see you've noted that you need to think about whether it has wider applicability though, so happy to defer this until you've resolved that question.

> I don't see a particular use case to separate the treatment of before and
after dimensions here; rather, the defined property should apply to the bpd
of the content area (box) as a whole.

I agree we don't need separate before and after treatment if we are separating this from `tts:padding`.

> So my counter proposal is something like:
>
>bpdContent
  : auto                  // initial value ... implementation dependent
  | bpdBounds             // bpd of bounding box of content pixels
  | bpdFont               // bpd of em square of resolved font
  | bpdLine               // bpd of content area of nearest line area
>ancestor
  | bpdLineLeaded         // bpdLine + 2*halfLeading
  | lineHeight            // resolved value of lineHeight property
  | <length>              // explicit length measure

Looks good to me.

**Comment by tairt** [comment]
While this discussion already concentrates on a new solution in TTML 2 I opened issue https://github.com/w3c/ttml1/issues/209 to clarfiy the intended semantics in TTML 1.

**Comment by fantasai** [comment]
Is there a reason you can't do this?

http://software.hixie.ch/utilities/js/live-dom-viewer/?%3C!DOCTYPE%20html%3E%0A%3Cstyle%3E%0A%20%20p%20%7B%20line-height%3A%202%3B%20%20width%3A%205em%3B%20%7D%0A%20%20span%20%7B%20background%3A%20yellow%3B%20padding%3A%200.5em%200%3B%20%2F*%20calc(1lh%20-%201em)%20*%2F%7D%20%0A%3C%2Fstyle%3E%0A%0A%3Cp%3E%3Cspan%3EHere%20is%20some%20text%20with%20a%20background%20and%20no%20gap.

**Comment by nigelmegitt** [comment]
That uses `calc()` (pretty neat, if you have that available in CSS); we need to be able to define this at authoring time not at runtime. Also as per the thread above we consider this to be orthogonal to padding, not something to be solved using padding.

**Comment by nigelmegitt** [comment]
Further conversation with @fantasai : action to raise an issue with CSSWG against the css-inline spec to have the content area of an inline box to be defined rather than undefined, and referenceable as a length so that it can be put into formulas and predicted.

**Comment by palemieux** [comment]
Extending the background beyond the inline area in the block progression direction (as suggested here) needs to be considered together with extending the background beyond the inline area the in the inline progression direction (as allowed by the linePadding attribute in IMSC and by ??? in TTML2).

**Comment by skynavga** [comment]
I think we need to distinguish between these two cases. In one case, we are
talking about a way to fix the content height (or width). In the other
case, we are talking about adding padding around (outside of) the content
height (or width). So they are (or should be) treated as orthogonal.

**Comment by palemieux** [comment]
> In one case, we are
> talking about a way to fix the content height (or width). 

Per the thread above, it looks like the idea is not to set the content height, but instead specify that the background extends to the previous line.

> In the other case, we are talking about adding padding around (outside of) the content
> height (or width).

Note that linePadding adds padding to the line (whether created by an explicit `br` or by flow) and not to the span.

>So they are (or should be) treated as orthogonal.

They need to be considered together lest their miter ends up looking like:

![miter](https://cloud.githubusercontent.com/assets/4871350/21290479/cd5020ea-c470-11e6-9675-508674afad98.png)

**Comment by skynavga** [comment]
On Sat, Dec 17, 2016 at 4:53 PM, Pierre-Anthony Lemieux <
notifications@github.com> wrote:

> In one case, we are
> talking about a way to fix the content height (or width).
>
> Per the thread above, it looks like the idea is not to set the content
> height, but instead specify that the background extends to the previous
> line.
>
That is not my intent. See
https://github.com/w3c/ttml2/issues/150#issuecomment-192490492.

> In the other case, we are talking about adding padding around (outside of)
> the content
> height (or width).
>
> Note that linePadding adds padding to the line (whether created by an
> explicit br or by flow) and not to the span.
>
> So they are (or should be) treated as orthogonal.
>
> I don't agree, since the extent of the line box extends outward (in ipd)
to the edges of the containing block's content rectangle. The "line
padding" is added to the first and last inline area of the line area.

**Comment by skynavga** [comment]
Address any outstanding comments under the following, which are hereby incorporated into this issue:

 - [ ] #101 span background height
