### ISSUE TITLE
Ensure that it is possible to extract plain text

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/ttml2#151]
See the text just above https://www.w3.org/2015/10/28-tt-minutes.html#action03 for context.

Especially where relatively complex syntax is needed for correct presentation of text, for example nested spans, Rubys, temporal order differing from document order etc, it needs to be clear how to extract the plain text content from a TTML2 document instance - this is useful for accessibility purposes for example.

Possible (non-exclusive) solutions:
* define an algorithm for extracting content that clarifies the order of precedence of time vs document
* add a new entry for the `ttm:role` attribute of `"presentation-enhancement"` to allow such content to be filtered out - e.g. to exclude spans for rubys
* incorporate one or more of the WAI-ARIA roles such as "main" via either the existing role attribute or a new one with a different name.

**Comment by skynavga** [comment]
Non-actionable without a proposal. Labeling as ttml.next for forward tracking.
