### ISSUE TITLE
Disparity "closest supported value" language misleading

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/ttml2#153]
There's a note on `tts:disparity` that says:

> In this context, the phrase closest supported value means the value for which the Euclidean distance between the computed disparity and the supported disparity is minimized. If there are multiple closest supported values equally distant from the computed value, then the value least distant from 0 is used.

This is slightly misleading since it does not point out that for correct display of stereoscopic content sub-pixel rendering is important. See [this thread](https://lists.w3.org/Archives/Public/public-tt/2015Jan/0041.html) where we discussed this previously.

I suggest we either keep this (because it is formally correct) and add a note along the lines of:

> The presentation of stereoscopic content depends in general on the use of sub-pixel (anti-aliasing) rendering techniques; implementations that quantise region position as adjusted by disparity to an integer pixel value may create undesirable visual effects. This is particularly important when there is a smooth animation of disparity, for example to maintain a constant distance between the subject and the text in front of it.

**Comment by skynavga** [comment]
On Fri, Mar 4, 2016 at 6:51 AM, Nigel Megitt <notifications@github.com>
wrote:

> There's a note on tts:disparity that says:
>
> In this context, the phrase closest supported value means the value for
> which the Euclidean distance between the computed disparity and the
> supported disparity is minimized. If there are multiple closest supported
> values equally distant from the computed value, then the value least
> distant from 0 is used.
>
> This is slightly misleading since it does not point out that for correct
> display of stereoscopic content sub-pixel rendering is important. See this
> thread <https://lists.w3.org/Archives/Public/public-tt/2015Jan/0041.html>
> where we discussed this previously.
>
I see this as a quality of implementation (QoI) issue. If implementers want
to create good rendering, they will use sub-pixel rendering as able. If
they don't want to do so, that's their business.

My policy is that we can't and shouldn't prevent poor implementations.

**Comment by nigelmegitt** [comment]
Agree we can't prevent poor implementations but that does not stop us from encouraging good ones, hence the proposed addition of a Note.
