### ISSUE TITLE
Create a section on options for customisation

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/ttml2#156]
As per [Action-460](https://www.w3.org/AudioVideo/TT/tracker/actions/460), and recorded in [these minutes](https://www.w3.org/2016/04/07-tt-minutes.html#action01), add a section to TTML2 explaining the options for customisation, including as a minimum:
-  deliberate non-compliance of presentation processors with the specification; 
-  local setting of implementation dependent values such as default value for `tts:color` etc.; 
-  use of parameters and conditions to control styling for using.

This will also serve as a placeholder for any other mechanisms that we introduce for customisation.

**Comment by skynavga** [comment]
Labeling this for ttml.next and closing. If someone wishes to post a PR on this for inclusion in the upcoming WR, then please do so and reopen this issue.

**Comment by nigelmegitt** [comment]
@skynavga I don't recall discussing this issue and agreeing to move to ttml.next - I would prefer to leave issues open and not done, and mop this up in an activity later on. It may be higher on someone else's priority list than yours.

**Comment by skynavga** [comment]
Moving off editor's WR list due to lack of PR.

**Comment by nigelmegitt** [comment]
Adding back on to editor's WR list now that there is a PR.
