### ISSUE TITLE
Clock-time form time expressions allow 60 seconds for media timebase

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/ttml2#158]
Equivalent issue to [TTML1 issue 210](https://github.com/w3c/ttml1/issues/210).

There appears to be no restriction on the use of a value of `60` in the seconds component of a clock-time time expression of the form hh:mm:ss. When using `ttp:timeBase="media"` it therefore appears that a minute can have 61 seconds; my understanding of the use case for this is to accommodate UTC leap seconds, so I would expect a restriction that the `60` seconds value can only apply when `ttp:timeBase="clock"`, and possibly additionally when `ttp:clockMode="utc"|"local"` since GPS clocks are not adjusted for leap seconds.

The discussed proposal is in TTML1 to disrecommend 60 seconds according to above and in TTML2 to prohibit 60 seconds as per above.

**Comment by nigelmegitt** [comment]
This has been resolved with an informative comment however my expectation here from https://github.com/w3c/ttml1/issues/210#issuecomment-212449373 was that it would be resolved with a normative provision.

**Comment by skynavga** [comment]
I did (do) not share that expectation, particularly if you are suggesting that we declare the appearance of 60 in other contexts as prohibited, since that would not be backward compatible with TTML1 in this regard. The informative note is sufficient notice to allow a verifier to conclude that a warning can be issued if it does appear. I suggest we discuss further on WG telecon.

**Comment by nigelmegitt** [comment]
Well it was your note @skynavga that gave me the impression (which I was happy with) that we would have a normative provision in TTML2 to match an informative one in TTML1. I understand the point about backward compatibility. At the very least having a `60` seconds value in any scenario other than `ttp:timebase="clock" ttp:clockMode="utc"` should be deprecated.

**Comment by skynavga** [comment]
Address additional comments in f88869e84d157744f6d28ffa26affa6dbe6b6ad9 as reported by @nigelmegitt.
