### ISSUE TITLE
Replace "CEA" with "CTA"

### ISSUE THREAD

**Issue by mikedo** [w3c/ttml2#159]
Most of the references to “CEA” should be replaced with “CTA” - e.g. "CTA 608".  They changed their name and also the name of their standards. See http://cta.tech/  

The namespaces with “cea” in it have not changed and probably won’t.

**Comment by skynavga** [comment]
Closed. Note that 'cea' in tokens has not changed to 'cta'? Should we change the tokens as well?

**Comment by skynavga** [comment]
Fixed. Should we change syntactic tokens as well?

**Comment by skynavga** [comment]
TTWG (09/19/2016) - remove both CEA/CTA and EBU named items, to be defined external (if desired) by use of qualified names; keep altText and usesForced in spec as unqualified names.

**Comment by skynavga** [comment]
Committed.
