### ISSUE TITLE
No restriction on time expression for smpte discontinuous mode

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/ttml2#161]
When `ttp:timeBase="smpte"` and `ttp:markerMode="discontinuous"` it is clear that calculations shall not be done on time expressions and they cannot be converted to real times, however there's no restriction that the time expressions shall use clock time with frames (i.e. the form "hh:mm:ss:ff"), and there's no explanation for how any alternative time expression should be related back into a smpte timecode.

https://w3c.github.io/ttml2/spec/ttml2.html#timing-time-value-expressions

**Comment by skynavga** [comment]
There is no such implied restriction; rather, the note under [1] provides the operational semantics:

>When operating with smpte time base and discontinuous marker mode, there is no effective time coordinate space; rather, all time expressions are interpreted as labeled synchronization events (markers), where the document processing context emits these events, which, when they correspond with time expressions that denote the same label, cause a temporal interval to begin or end accordingly.

In other words, it is up to the document processing context to decide what "time expressions ... denote the same label".

[1] file:///Users/glenn/work/ttml2/spec/ttml2.html#parameter-attribute-markerMode

**Comment by nigelmegitt** [comment]
Are you suggesting that a processing context may wish to convert a clock time expression, say, using fractions of seconds, to a SMPTE marker mode, and then look for that in the source of SMPTE timecode? And that this conversion is something that we do not need to document?

The whole premise (of SMPTE discontinuous) seems untenable to me unless we have something approximately the same as a SMPTE timecode marker, though I accept the (at some point previously stated) point that there is no specification for making the arguably obvious conversion between SMPTE timecode bits and a frame based time expression; in the absence of that then the field could seem open for other conversions to be equally legitimate.

It would help to have some data points about the number of implementations that can deal with anything other than `hh:mm:ss:ff` time expressions when in SMPTE discontinuous mode. My guess is this is zero, but a guess isn't especially useful here.

**Comment by skynavga** [comment]
I should have noted as well that we already added the following text in [1], deprecating the use of offset-time as well as a fraction component in a clock-time for smpte time base:

> If the computed value of the ttp:version property is greater than or equal to 2 (two) and the computed value of the governing time base is smpte, then (1) use of an offset-time form of <time-expression> is deprecated, and (2) use of a fraction seconds component in a clock-time form of <time-expression> is deprecated.

Does that address your concern?

[1] https://w3c.github.io/ttml2/spec/ttml2.html#timing-value-time-expression

**Comment by nigelmegitt** [comment]
Ah, thank you, yes that does help. It's not quite the positive "you should/shall use `hh:mm:ss:ff`" that is one of the possible resolutions for this issue but it is very close - the `:ff` component is marked as optional. 

Is it a reasonable assumption that implementors will treat a missing `:ff` component as identical to `:00` for the purpose of interpreting as a SMPTE timecode label? I'm not sure, since it is only a label.

**Comment by mikedo** [comment]
There are not really any "frames" - this is just a string label. The strings are not identical and there is currently no default value.  We would have to define a default value and its encoding to me identical to whatever we think the default should be.

**Comment by nigelmegitt** [comment]
@mikedo that's what I thought too. However unless I have misunderstood there is currently no specified algorithm for converting (in either direction) between the string label in the TTML document and the SMPTE timecode value.

**Comment by mikedo** [comment]
Right.  All we can do is map between the strings. 12M semantics were not incorporated, and also, there is no canonical string representation of 12M - it is not defined by SMPTE. There are several different edit list string representations in practice. So, here, it is truly just a string label. We can define the string mapping with a default if we want to.

**Comment by nigelmegitt** [comment]
I would be happy to add text specifying the synthesis of a time expression label from SMPTE timecode, presumably along the lines of:

* Take the hours component and create a 2 digit zero padded equivalent numerical representation string which we label `hh`
* Take the minutes component and create a 2 digit zero padded equivalent numerical representation string which we label `mm`
* Take the seconds component and create a 2 digit zero padded equivalent numerical representation string which we label `ss`
* Take the frames component and create a 2 digit zero padded equivalent numerical representation string which we label `ff`
* Concatenate the above components with interceding `:`s to create a label of the form `hh:mm:ss:ff`

Then having defined this it is clear that the only marker labels that will match with a string comparison when `ttp:markerMode="discontinuous"` are those of the same form, and a time expression omitting the frames component will never be matched at runtime.

**Comment by skynavga** [comment]
I am far from convinced that there is any problem here. If you can show how
lack of a defined mapping results in interoperability failures, then that
would be a good starting point for a problem description.

**Comment by nigelmegitt** [comment]
I can't point to any specific examples of interoperability failures, just theoretical ones.

Since the algorithm for mapping SMPTE timecode to a time expression is undefined it would be feasible and conformant for the following to occur:
* A SMPTE time code value whose hours are 0, minutes are 8, seconds are 13 and frames are 20 is received.
* Implementation 1 maps it to the string  `12345f` and
* Implementation 2 maps it to `00:08:13:20` (25fps).

One of these strings matches a time expression in the TTML and the other does not. The two implementations are not interoperable.

**Comment by skynavga** [comment]
That just means one of the implementations is broken, not that there is an
interop problem.

The form of the timestamp/label and how comparison occurs takes place
wholly within the implementation, and is not visible to either author or
end user. It is the implementers responsibility to "do the right thing" in
this regard.

**Comment by nigelmegitt** [comment]
> That just means one of the implementations is broken, not that there is an
interop problem.

I don't understand this. We have a situation where one TTML document works with one implementation but does not work with another implementation, yet both implementations are apparently conformant. How is that not an interop problem?

**Comment by skynavga** [comment]
Are you suggesting it is reasonable that an implementation does the
following?

   - A SMPTE time code value whose hours are 0, minutes are 8, seconds are
   13 and frames are 20 is received.
   - Implementation 1 maps it to the string 12345f and

**Comment by skynavga** [comment]
On Thu, Apr 20, 2017 at 2:37 AM, Glenn Adams <glenn@skynav.com> wrote:

> Are you suggesting it is reasonable that an implementation does the
> following?
>
>    - A SMPTE time code value whose hours are 0, minutes are 8, seconds
>    are 13 and frames are 20 is received.
>    - Implementation 1 maps it to the string 12345f and
>
>
>
Let me back up.

If one implementation wants to map a time expression equivalent to
00:08:13:20 to a label expressed as a frame count and then converts smpte
time codes embedded in media to a label expressed as a frame count and then
compares the frame counts. While another implementation uses hh:mm:ss:ff
format for labels and does comparisons, then both implementations will
match the same smpte time code with the same expression, yes (assuming that
frame rate is handled consistently in the first implementation)?

**Comment by nigelmegitt** [comment]
> If one implementation wants to map a time expression equivalent to
00:08:13:20 to a label expressed as a frame count and then converts smpte
time codes embedded in media to a label expressed as a frame count and then
compares the frame counts.

Ah right, I see - you are envisaging that despite the marker mode, the implementation is nevertheless performing some processing on the time expression to convert it to an internal canonical format. I had made the opposite assumption, that the label is to be treated purely as a string for direct comparison, and that it is actually non-conformant for implementations to do any processing on it. I came to this conclusion from the text and notes about the treatment of time expressions in discontinuous mode in https://w3c.github.io/ttml2/spec/ttml2.html#parameter-attribute-markerMode

**Comment by skynavga** [comment]
On Thu, Apr 20, 2017 at 3:06 AM, Nigel Megitt <notifications@github.com>
wrote:

> If one implementation wants to map a time expression equivalent to
> 00:08:13:20 to a label expressed as a frame count and then converts smpte
> time codes embedded in media to a label expressed as a frame count and then
> compares the frame counts.
>
> Ah right, I see - you are envisaging that despite the marker mode, the
> implementation is nevertheless performing some processing on the time
> expression to convert it to an internal canonical format. I had made the
> opposite assumption, that the label is to be treated purely as a string for
> direct comparison, and that it is actually non-conformant for
> implementations to do any processing on it. I came to this conclusion from
> the text and notes about the treatment of time expressions in discontinuous
> mode in https://w3c.github.io/ttml2/spec/ttml2.html#parameter-
> attribute-markerMode
>
It "the label" can be "treated purely as a string for direct comparison"
but that is really an implementation detail, since, as Mike points out,
SMPTE time codes themselves don't have a canonical format in the first
place. So it is up to an implementation to "do the right thing" when
comparing a SMPTE time code and some equivalent expression derived from a
time expression. Presumably the implementation does this in a consistent,
sensible manner, but different implementations may use different expression
formats or comparison algorithms. Thus the avoidance of defining an actual
label format.

**Comment by nigelmegitt** [comment]
SMPTE time codes do have a defined format in terms of bits to be inserted in data streams; they just do not have a canonical _string_ format. For me this is the missing part. 

Given the existing text about discontinuous markerMode I think it would be worth adding a further note that implementations are expected to use their own internal algorithm to compare the time expression with a time code value, and that this may legitimately require parsing and processing the time expression, in other words not simply using it as a string. This would resolve the issue for me.

**Comment by skynavga** [comment]
Ok, it should be no problem to provide such a note. I'll take that action.

**Comment by nigelmegitt** [comment]
Thank you @skynavga !

**Comment by skynavga** [comment]
Resolved in 900a48d68a8760a96b4607caa6fdaa1c0c2833b9.
