### ISSUE TITLE
Need parameter attribute to express resolved storage aspect ratio in ISD

### ISSUE THREAD

**Issue by skynavga** [w3c/ttml2#162]
Need to pass through to ISD (on isd:sequence or isd:isd) a parameter expressing the resolved storage aspect ratio (as extent) of root container region. For example, this parameter may be defined as ttp:storageAspectRatio but prohibited from appearing in TTML2 source content; rather, only permitted in ISD content.

**Comment by skynavga** [comment]
Note that this is predicted on having already retargeted the originally proposed ttp:storageAspectRatio to ttp:displayAspectRatio.

**Comment by nigelmegitt** [comment]
That change from SAR to DAR is captured in #30 .

**Comment by skynavga** [comment]
Understood, but this is a separate issue.

**Comment by skynavga** [comment]
Incorporate resolution of these comments into #30 and closing this issue.
