### ISSUE TITLE
Use of fractional seconds in clock-time expression in smpte mode

### ISSUE THREAD

**Issue by skynavga** [w3c/ttml2#165]
Need to address semantics of using a clock-time expression that contains fractional seconds when time base is smpte continuous mode. As there is no current prohibition on the presence of the fractional component in clock-time expressions, the current semantics of the `seconds` variable of the `countedFrames` expression is not well-defined.

[1] http://w3c.github.io/ttml2/spec/ttml2.html#time-expression-semantics-smpte

**Comment by nigelmegitt** [comment]
TTML1 [§10.3.1](https://www.w3.org/TR/ttml1/#timing-value-timeExpression) does not permit this for clock-times:

> `clock-time`
>  `: hours ":" minutes ":" seconds ( fraction | ":" frames ( "." sub-frames )? )?`

**Comment by skynavga** [comment]
Note that the syntax for clock-time makes the use of fractional seconds or frames mutually exclusive:

<pre>
clock-time
  : hours ":" minutes ":" seconds ( fraction | ":" frames ( "." sub-frames )? )?
</pre>

The question remains, however, as to whether an expression such as ``HH:MM:SS.SSS`` is permitted in smpte continuous mode, and if it is, then how is it to be interpreted with respect to the ``countedFrames`` expression.

**Comment by nigelmegitt** [comment]
I think it probably is permitted, unfortunately.

**Comment by mikedo** [comment]
I think we should not debate the individual sentences of TTML1.

 

I believe text that suggests that fractional seconds are permitted in timebase=“smpte” is simply an error. SMPTE time code, as defined in the *normative* reference - SMPTE 12M, has no such concept.

 

The fact that it may be intellectually possible to define semantics and mappings is not, in my opinion, sufficient justification for perpetuating this interpretation.


We should take the obvious course of clarifying that timebase=”smpte” is precisely 12M and not “12M as extended by W3C”.

 

Unrelated, but the reference to 12M in TTML2 should be updated to ST12-1, which among other things, has support for more framerates.

 

                Mike

**Comment by palemieux** [comment]
@mikedo +1

**Comment by nigelmegitt** [comment]
@mikedo So you're suggesting that we should modify the normative permission to have fractional seconds in `timeBase="smpte"` via an erratum to TTML1SE that explicitly prohibits it?

**Comment by mikedo** [comment]
TTML2 should be clear, and in my view should be strictly 12M.  For consistency with TTML2 and clarity, yes we should probably also issue an erratum against TTML1SE.  If an implementer has actually used this combo syntax, the semantics are undefined today – unclear at best. Either way, we need to modify TTML1SE, and either way, it would likely alter conformance of such an implementation.

**Comment by skynavga** [comment]
On Thu, Jul 7, 2016 at 9:38 AM, Michael A Dolan <notifications@github.com>
wrote:

> I think we should not debate the individual sentences of TTML1.
>
>
>
> I believe text that suggests that fractional seconds are permitted in
> timebase=“smpte” is simply an error. SMPTE time code, as defined in the
> *normative* reference - SMPTE 12M, has no such concept.
>

To be very clear, the TTML1 normative syntax *does* permit use of
fractional seconds or frames (but not both) in a clock-time expression when
in smpte time base, so it is not a matter of a suggestion.

For TTML1, I believe we can do only the following:

(1) via errata, add note in TTML1 that (informatively) discourages the use
of fractional component rather than frames component;
(2) via errata, expand the definition *seconds* of countedFrames expression
in N.3 to handle case where fractional seconds are specified (instead of
frames);

For TTML2, we need to support backward compatibility with TTML1, so we need
the same text enhancing the countedFrames expression. We can then
separately deprecate the use of fractional seconds, but still need the
definition of what it means if it is used.

**Comment by skynavga** [comment]
On Thu, Jul 7, 2016 at 9:56 AM, Michael A Dolan <notifications@github.com>
wrote:

> TTML2 should be clear, and in my view should be strictly 12M. For
> consistency with TTML2 and clarity, yes we should probably also issue an
> erratum against TTML1SE. If an implementer has actually used this combo
> syntax, the semantics are undefined today – unclear at best. Either way, we
> need to modify TTML1SE, and either way, it would likely alter conformance
> of such an implementation.


Also, to make this clear, Nigel noted that the syntax (in TTML1) does not
actually permit the combination of fractional seconds and frames: it is
either none of these or one of these only.

**Comment by palemieux** [comment]
> (1) via errata, add note in TTML1 that (informatively) discourages the use of fractional component rather than frames component;
> (2) via errata, expand the definition *seconds* of countedFrames expression in N.3 to handle case where fractional seconds are specified (instead of frames);

As suggested by @mikedo (I think), an alternative approach is to state that, even though allowed by syntax, the behavior of fractional seconds is not specified (the syntax was allowed in error) and that using fractional seconds is not encouraged.

In other words, explicitly specifying the behavior of fractional seconds (suggested by (2) above) might in fact encourage their use.

**Comment by skynavga** [comment]
On Thu, Jul 7, 2016 at 10:20 AM, Pierre-Anthony Lemieux <
notifications@github.com> wrote:

> (1) via errata, add note in TTML1 that (informatively) discourages the use
> of fractional component rather than frames component;
> (2) via errata, expand the definition *seconds* of countedFrames
> expression in N.3 to handle case where fractional seconds are specified
> (instead of frames);
>
> As suggested by @mikedo <https://github.com/mikedo> (I think), an
> alternative approach is to state that, even though allowed by syntax, the
> behavior of fractional seconds is not specified (the syntax was allowed in
> error) and that using fractional seconds is not encouraged.
>
I'm not entirely sure it was "allowed in error", but I don't recall any
discussion around this point other than what I mentioned today: that we
started with SMIL[12] time expressions and added the ability to express
frames. What we may have not done is consider whether to limit this syntax
when using smpte time base.

I am not comfortable saying the behavior is undefined, particularly if we
can posit a reasonable interpretation (whether it is used or not). I view
the current situation as having a syntax whose semantics is not fully
defined, so saying it is undefined doesn't help.

> In other words, explicitly specifying the behavior of fractional seconds
> (suggested by (2) above) might in fact encourage their use.
>
I would rather define the semantics and separately add text to discourage
such usage. In TTML2 we can go further by deprecating such usage.

**Comment by nigelmegitt** [comment]
Notes from f2f meeting 2016-09-20: agree not to support fractions of seconds in time expressions for smpte timebase; need also to consider how to deal with offset time expressions that may evaluate to times that are not coincident with equivalent frame times (including fractional frames and dropped frames).

**Comment by nigelmegitt** [comment]
Addition to the above: for smpte we should only permit clock-time expressions with seconds and frames. There will be a "shall not" for this for TTML2, but we will make it a should not for TTML1 so that we do not break existing content.

**Comment by nigelmegitt** [comment]
As discussed, apply the fix to w3c/ttml1#188 here.

**Comment by skynavga** [comment]
Resolved follow-on PR to add note in 38edb87683dc2bdff4e05cd913ed261c320dc33a.
