### ISSUE TITLE
Disallow duplicate designators in ttp:{content,processor}Profiles

### ISSUE THREAD

**Issue by skynavga** [w3c/ttml2#166]
If multiple designators are specified in a designator list, then their absolutized forms must be distinct; i.e., no duplicates allowed.

**Comment by nigelmegitt** [comment]
I'm not clear why you want to disallow this - in either the case `"all(X Y Z)"` or `"any(X Y Z)"` there would be no semantic difference by including a duplicate, e.g. `"all(X Y Z)"` would clearly mean exactly the same as `"all(X Y Y Z)"`. Perhaps this should be a _should_ rather than a _must_?

**Comment by skynavga** [comment]
I consider it an error of redundancy to have multiple identical descriptors. Further, it may not be apparent from reading the content (at first glance) that they are identical. Only after their absolutized forms are determined can the check be performed. Closing this as it has been merged. A follow-on issue can be created if desired.
