### ISSUE TITLE
Add safe crop area

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/ttml2#173]
As described in https://lists.w3.org/Archives/Public/public-tt/2016Jun/0003.html and in this PDF:

[Subtitle Safe Crop Area BBC submission 2016-06-09.pdf](https://github.com/w3c/ttml2/files/397449/Subtitle.Safe.Crop.Area.BBC.submission.2016-06-09.pdf)

Proposal is to add into the `ttp` parameter namespace a safe crop area and to define the processor semantics associated with that safe crop area.

**Comment by skynavga** [comment]
No objection to merge during today's call. Revised description and added notes to attempt to address concerns about naming and intended semantics.

**Comment by tairt** [comment]
After reviewing it I found the description how the values are computed hard to understand. I would like to check if other reader/users may have the same problem.

**Comment by skynavga** [comment]
I could have used formulas, i.e., algebraic expressions, by I felt prose was better. I suppose I could expand the note:

> **Note** The intent of the following rules is to ensure that the safe crop area is bounded by the root container region.

Is there a specific part of this language you feel it is necessary to further elaborate?
