### ISSUE TITLE
Viewport unit {vw,vh} naming: {rw,rh} preferred.

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/ttml2#181]
TTML2 introduces the excellent new units `vw`and `vh`, which are relative to the width and height of the root container region. However this definition could be perceived as clashing with the CSS definition of the identically named units, which are relative to the viewport. This may cause (at least) two implementation difficulties:

1. In the case of a root container region that is not coincident with a related media object (or the media player) an implementation may assume that the root container region is in fact coincident and calculate sizes incorrectly.

2. A naïve translation to HTML and CSS for rendering on a media player may not translate the units at all and assume that for TTML rendering purposes the viewport is identical to a host HTML page's  viewport, resulting in incorrect sizes except when viewing in full screen mode.

This is a case of something that is not exactly _wrong_ as is, but may encourage or lead to poor implementations. I would propose nudging implementors towards checking the specification more carefully by renaming these units `rw` and `rh` to make it clear that they are related to the root container region and not the viewport.

I would also propose the addition of an editorial note describing how to convert `rw` to `vw` and and `rh` to `vh` respectively given a root container region whose size is defined relative to a media player window and whose media player window size is known relative to the viewport.

**Comment by skynavga** [comment]
Given there are already multiple implementations using the new units, and given there is already a substantial amount of content using them, changing names would be unnecessarily disruptive and serve no technical purpose. My response to confused users is RTFM.

**Comment by nigelmegitt** [comment]
On further thought the current use of `vw` and `vh` is in fact a bug since, on RTFMing CSS they mean something different there, and we now are referencing CSS. Reopening.

**Comment by nigelmegitt** [comment]
By the way, commenting as Chair, please note that prematurely closing issues without offering a chance for discussion and consideration is an abuse of process; also, though early implementations are highly valued, I'm sure that the implementers are very well aware that they are using a working draft only that is subject to change. The arguments used to dismiss this issue initially are applicable to CR stage but not WD stage. We do have freedom to make changes where deemed appropriate at WD stage.

**Comment by skynavga** [comment]
If there were a technical reason for considering a change, I would do so. But there is none, and the usage is already active. I am removing the bug label. In no way is this a bug.

**Comment by skynavga** [comment]
Also, regarding CSS, we are entirely consistent with the CSS definition since the TTML root container region corresponds with notion of the CSS initial containing block.

**Comment by nigelmegitt** [comment]
There most certainly is a technical reason - `vw` and `vh` are defined by https://www.w3.org/TR/css3-values/#viewport-relative-lengths as:

> The viewport-percentage lengths are relative to the size of the initial containing block.

and 

> The containing block in which the root element lives is a rectangle called the initial containing block. For continuous media, it has the dimensions of the viewport and is anchored at the canvas origin; it is the page area for paged media.

and

> User agents for continuous media generally offer users a viewport (a window or other viewing area on the screen) through which users consult a document. User agents may change the document's layout when the viewport is resized (see the initial containing block).
>
> When the viewport is smaller than the area of the canvas on which the document is rendered, the user agent should offer a scrolling mechanism. There is at most one viewport per canvas, but user agents may render to more than one canvas (i.e., provide different views of the same document).

In our case the viewport is likely to be the media playing area _not_ the root container region. The root container region has no fixed relationship in size to the media player, though it is highly likely that many implementers will make the dangerous assumption that they are in fact the same. Therefore this is inconsistent with CSS and we do need to address this otherwise TTML 2 renderers will not produce output that matches the document.

I also note that neither the definition of continuous media nor paged media seem to be a good fit for TTML content. Possibly paged media is the better fit, but the definitions for that case are incomplete currently.

**Comment by skynavga** [comment]
I will insist yet again, that there is no technical issue with how vw/vh are defined in TTML2 at present. They are well defined. However, if you want to suggest a more concrete definition for root container region, then we can have that conversation, but it is unrelated to vw/vh unit definition. So it should be addressed in a different issue.

**Comment by nigelmegitt** [comment]
I don't see any problem with root container region - it's fine to define a coordinate system and give it this term. Changing it now would have a huge impact on everything that refers to it, which is pretty much everything position related. 

However returning to `vw` and `vh`, I see that we now have a defined term for viewport, so it seems like we should be relating `vw` and `vh` to the viewport; we do need to disentangle how the concepts of related media (video) frame size, media player window and root container region relate to each other. I've made a start at doing this with #184 - the expectation is that we will also bring in the equivalent of `ittp:aspectRatio` somehow, to allow positioning of the root container region against the media.

Regardless of how that turns out, I still think the most useful units at authoring time are percentages of the root container region width and height, in other words exactly how `vw` and `vh` are currently defined. The issue is not with the semantic at all, just the label, because I still think it will clash with most readers' understanding of those terms, especially now that we have viewport defined. 

Rather than going round in circles I suggest we pick this up at the f2f, and will add an agenda item for it.

**Comment by nigelmegitt** [comment]
2016-09-20 f2f meeting conclusion: rename `vw` and `vh` to `rw` and `rh` respectively.

**Comment by skynavga** [comment]
See PR #199.
