### ISSUE TITLE
Ensure that document conventions cover syntax used in value expressions.

### ISSUE THREAD

**Issue by rpuri-netflix** [w3c/ttml2#186]
TTML2 specification appears to use notations such as:
1. Usage of '||' in Section 10.2.6 (tts:border)
2. Various expressions (e.g., `<measure>`, `<time-expression>`) appear to use EBNF notation. Perhaps for sake of completeness, we should call that explicitly

**Comment by palemieux** [comment]
The use of the space character in syntax expression is inconsistent:

* `<length> <length>` means two `<length>` expressions separated by one space character
* `multiplicitive-expression "*" unary-expression` means the three expressions concatenated without interstitial characters
* `identifier ( <lwsp> identifier )*` means identifiers separated by multiple lswp characters

**Comment by skynavga** [comment]
Merged from #311 and closing.
