### ISSUE TITLE
Create a registry of named metadata items.

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/ttml2#188]
Follow on from #159 - need to create an external registry of named metadata items to reference from TTML2.

Should include items removed in 45665eb.

**Comment by skynavga** [comment]
My intention was that the registry not specify actual named items, but merely a binding from namespaces to other documents, where the latter would contain the names defined in its namespace.

**Comment by nigelmegitt** [comment]
The good thing about delegating definition to a separate document is we can also defer the conversation about exactly what goes in that document.

I'm neutral about how we structure it but it seems simpler to define all the new named items in a single document than refer on to additional ones, if I've understood your proposal correctly.

**Comment by skynavga** [comment]
Closing this as it is not related to TTML2 spec text. Probably should create a WG ACTION to cover this.
