### ISSUE TITLE
Add support for adjacent background area merging

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/ttml2#189]
Follow-on from #176 which was closed since the core issue, corner rounding, was resolved. This is the new home for the additional requirement to merge background areas such that the corner rounding results in a nice looking output.

Extracted comments from: https://github.com/w3c/ttml2/issues/176#issuecomment-246140753 and https://github.com/w3c/ttml2/issues/176#issuecomment-248003223

None of the examples of rounded borders I have seen use different radii for the two directions, so I'd advocate simplifying to a single value for now, until a need for two radii is presented.

However one thing that may be underspecified at the moment is the flow of rounded rectangles between adjacent areas. I've seen this kind of thing:
![image](https://cloud.githubusercontent.com/assets/4988915/18413555/0d647110-77a3-11e6-8f7d-49f1f920b0b0.png)

where I would rather have seen something like this:
![image](https://cloud.githubusercontent.com/assets/4988915/18413553/05a8c354-77a3-11e6-9815-af3746928234.png)

or even perhaps:

![image](https://cloud.githubusercontent.com/assets/4988915/18413552/f194230e-77a2-11e6-9a97-1c660f0d0a3b.png)

In other words when creating a composite background shape from congruent area backgrounds the radial centre should be offset in the direction of the hypotenuse of the right angle triangle formed between the vertex being drawn and the two adjacent vertices, not away from it. There are probably more elegant ways to describe this!

Further examples from f2f meeting 2016-09-19:

![image](https://cloud.githubusercontent.com/assets/4988915/18634866/c8d12f64-7e7a-11e6-97c9-e86b9b63ab99.png)

and 

![image](https://cloud.githubusercontent.com/assets/4988915/18634873/d04b0d00-7e7a-11e6-84c8-860bb1dcb600.png)

These require a little more thought in terms of how to specify them

**Comment by nigelmegitt** [comment]
Meeting 2017-05-11: Agreed to add examples for backgrounds on p and span with rounded borders, assigned to Nigel.

**Comment by skynavga** [comment]
Note that example images for span and p should be the first and last images in the first comment above.

**Comment by skynavga** [comment]
@nigelmegitt what is your schedule for a PR to add examples?

**Comment by skynavga** [comment]
Lacking a PR, I am taking this off my work list. If a PR is posted, then please restore to my list.

**Comment by nigelmegitt** [comment]
I've opened a PR, and put it back on your list @skynavga .
