### ISSUE TITLE
Keyword value withBase not defined by tts:rubyAlign

### ISSUE THREAD

**Issue by dae-kim** [w3c/ttml2#196]
See attached render from latest TTPE:

...style xml:id="s3" tts:ruby="container" tts:rubyAlign="withBase"...
...region xml:id="横下" tts:displayAlign="after" tts:extent="80vw 30vh" tts:position="center bottom 10vh"...
...base: 文文文文  ruby: ルルル...

![ttpi000001](https://cloud.githubusercontent.com/assets/15376166/19209421/f804f930-8cbe-11e6-9649-91c226d76ad8.png)

**Comment by skynavga** [comment]
I'm not sure what you are reporting. The withBase value is defined in the syntax definition of tts:rubyAlign [1] and in the schema files. Perhaps you are noticing that this value is not mentioned in the text following the syntax definition in the spec?

Also, I'm not sure about the image you include here. Clearly there is a problem with it, but I can't say the source of the problem (example content or TTPE implementation). In any case, the image doesn't appear to be related to the title of this issue.

**Comment by dae-kim** [comment]
I'm looking at the Editor's Draft:
http://w3c.github.io/ttml2/spec/ttml2.html#style-attribute-rubyAlign'

"withBase" is the only value not mentioned in the paragraph:

"If the value of this attribute is start, then the start edge of the first glyph area descendant of an inline area generated from a ruby text container or ruby text annotation is aligned to the start edge of that inline area. If the value is center, then excess whitespace is equally distributed before and after the first and last ruby annotation glyph areas, respectively. If the value of this attribute is end, then the end edge of the first glyph area descendant of an inline area generated from a ruby text container or ruby text annotation is aligned to the end edge of that inline area. If the value is spaceBetween, then excess whitespace is equally distributed between each ruby annotation glyph area. If the value is spaceAround, then excess whitespace is equally distributed before and after each ruby annotation glyph area descendant."

**Comment by skynavga** [comment]
Added definition for both ``auto`` and ``withBase`` values. Regarding the image above, you need to use an example where the number of ruby and base glyphs are equal. There is a minor bug in TTPE when the number of ruby glyphs is greater than the number of base glyphs. In any case, if the glyph counts are not equal, then you don't get the normal ``withBase`` semantics.
