### ISSUE TITLE
Process [construct intermediate document] prunes "set" elements

### ISSUE THREAD

**Issue by palemieux** [w3c/ttml2#210]
The [construct intermediate document] process "prune[s] elements if they are not a content element". This prunes `set` elements, which cannot be used for the "10.4.4.4 Style Resolution Process".

**Comment by skynavga** [comment]
Good catch. It is clearly conflicting with 10.4.4.4's list. We should also do an errata for TTML1.

**Comment by nigelmegitt** [comment]
Discussed and agreed - implement as per w3c/ttml#216

**Comment by skynavga** [comment]
Resolved in 32fea6031fc30824ce15de0dd5022c097fbbb630.
