### ISSUE TITLE
Ambiguous definition of "empty" in Synchronic Document Construction

### ISSUE THREAD

**Issue by palemieux** [w3c/ttml2#212]
In "11.3.1.3 Intermediate Synchronic Document Construction", the algorithm states "prune elements [...] if they are empty".

What does "empty" mean? For instance, is a `p` without text content, e.g. `<p></p>`, empty? Similarly, is a `div` without `p` elements empty?

The term "empty" is not defined.

**Comment by skynavga** [comment]
This is a commonly understood term of art with respect to XML and XML Info Sets. See [1] for example.

[1] https://www.w3.org/TR/REC-xml/#dt-empty

**Comment by palemieux** [comment]
> This is a commonly understood term of art with respect to XML and XML Info Sets. See [1] for example.

So... `<p></p>` is considered empty but `<p> <\p>` is not?

What about `<div> </div>`?

Does this definition interact with "xml:space"?

At the very least, a reference to https://www.w3.org/TR/REC-xml/#dt-empty must be provided if this is intended definition.

**Comment by skynavga** [comment]
On Sun, Oct 30, 2016 at 10:38 AM, Pierre-Anthony Lemieux <
notifications@github.com> wrote:

> This is a commonly understood term of art with respect to XML and XML Info
> Sets. See [1] for example.
>
> So... <p></p> is considered empty but <p> <\p> is not?
>
correct in both cases

> What about <div> </div>?
>
empty, since div does not accept #PCDATA content, and since whitespace in
element content (but mixed content) is not significant


> Does this definition interact with "xml:space"?
>
 no

> At the very least, a reference to https://www.w3.org/TR/REC-xml/#dt-empty
> must be provided if this is intended definition.
>
i don't think so; but if the group would like a note, then I will add; we
can't (and shouldn't) cite a definition of every term, especially when it
is well understood; for example, we don't define element, attribute,
document, character, glyph, and many other assumed terminology

**Comment by skynavga** [comment]
on second thought, perhaps we do need a definition, and possibly even
change the term, because we may have renderable marks even when there is no
content; e.g., consider:

<p tts:ipd="100%" tts:bpd="1em" tts:backgroundColor="red"/>

from the perspective of XML the p is an empty element; but it should
actually generate an area with a renderable background color of height 1em
and width same as containing block's width;

**Comment by palemieux** [comment]
> from the perspective of XML the p is an empty element;

Exactly, the definition of empty per XML does not concern itself with the actual semantics of the content and merely states "An element with no content is said to be empty" with "content" defined as `content	   ::=   	CharData? ((element | Reference | CDSect | PI | Comment) CharData?)*`.

**Comment by skynavga** [comment]
Actually, the definition is:

> [Definition: The text between the start-tag and end-tag is called the element's content:]

So, in that sense, both ``<p> </p>`` and ``<div> </div>`` are non-empty. So, I agree we have an issue here, both for this reason and the one I mention above about background color on an otherwise "empty" ``p``.

**Comment by palemieux** [comment]
Could "empty" be defined as "not containing a span, whether anonymous"?

**Comment by skynavga** [comment]
I think we will need to abandon the term empty and use a phrase like *has usable content* where *content* includes anything that can produce or affect the layout of a rendered mark.

**Comment by palemieux** [comment]
> has usable content where content includes anything that can produce or affect the layout of a rendered mark

I think this needs to be more specific since the concept of "usable content" is used to prune elements during ISD construction, which itself determines layout and marks.

What elements other than non-empty spans affect layout and/or rendered marks?

**Comment by skynavga** [comment]
On Sun, Oct 30, 2016 at 2:14 PM, Pierre-Anthony Lemieux <
notifications@github.com> wrote:

> has usable content where content includes anything that can produce or
> affect the layout of a rendered mark
>
> I think this needs to be more specific since the concept of "usable
> content" is used to prune elements during ISD construction, which itself
> determines layout and marks.
>
> What elements other than non-empty spans affect layout and/or rendered
> marks?
>
span, p, or div with explicit ipd/bpd, with or without background marks

**Comment by skynavga** [comment]
also deal with <br/> see #w3c/ttml1/197.

**Comment by nigelmegitt** [comment]
Note that we discussed and agreed in w3c/ttml1#197 the proposal to avoid pruning `<br>` elements.

**Comment by skynavga** [comment]
Resolved in 32fea6031fc30824ce15de0dd5022c097fbbb630.

**Comment by palemieux** [comment]
* Note re: issue-197 remains
* Why does _presentation related element_ include _contains or expresses presentable content_ in addition to _affects the presentation of content_?
* I think _affects the presentation of content_ should be more specific. This is important for interoperability since `whenActive` is triggered when `when some content is flowed into the region.`

**Comment by skynavga** [comment]
The issue you refer to (197) is a TTML1 issue. Please file a new issue on "presentation related element" if you wish  to see a change in the definition. It is impractical to be as specific as you want to be without writing an extremely complex, brittle piece of specification text. The basic definition of presentable content is that it is presentation related unless you can prove it isn't.

Re-closing this issue. Feel free to file a new issue to word smith presentation related element.
