### ISSUE TITLE
Why is isd:css necessary?

### ISSUE THREAD

**Issue by palemieux** [w3c/ttml2#214]
Why is isd:css necessary? Can't Referential Styling (chained or not) be merged into Inline Styling as part of ISD construction (just as Nested Styling)?

**Comment by skynavga** [comment]
> Why is isd:css necessary?

The intent of isd:css is to represent the results of performing the *Style Resolution Process* [1] on a given element, and thus, flatten the hierarchical style model of elements in the ISD to the greatest extent possible. This goal is analogous to having ISDs flatten the hierarchical timing model.

[1] http://w3c.github.io/ttml2/spec/ttml2.html#semantics-style-resolution-process-overall

If you are asking if it is possible to define ISD content so as not to flatten the style matter, then yes, it would be possible to do that. But it would increase post-ISD processing requirements by postponing the style flattening that eventually must occur.

> Can't Referential Styling (chained or not) be merged into Inline Styling as part of ISD construction (just as Nested Styling)?

I don't understand this part of your question.

**Comment by palemieux** [comment]
The specification states "The isd:css element is used to represent a unique computed style set of some collection of elements that share the same set of computed styles". Doesn't this mean that isd:css is not necessary since the computed style set could be applied to each of the elements directly?

**Comment by skynavga** [comment]
Are you suggesting an alternate design as follows: for each element E in an ISD, rewrite CSS(E) as inline styles on E? Then yes, that would be possible; however, it would remove the obvious advantage of sharing identical computed style sets across multiple Es. Since it will be the case that CSS(E1)=CSS(E2), E1!=E2, in a very high number of cases, then using inline styles would be extremely uneconomical.

**Comment by palemieux** [comment]
Thanks for confirming that isd:css is not necessary, but provided for convenience.

**Comment by skynavga** [comment]
> Thanks for confirming that isd:css is not necessary, but provided for convenience.

It is more than mere convenience, but more importantly, for economy. Many design choices in TTML and the standards it references employ economy as an essential requirement. Authorial convenience, though valuable, is orthogonal to economy. Some users may consider economy a necessary characteristic.
