### ISSUE TITLE
Use of 'em' units in tts:fontSize on region element is not well defined.

### ISSUE THREAD

**Issue by palemieux** [w3c/ttml2#216]
The resolution to https://github.com/w3c/ttml1/issues/206 needs to be implemented here in order to remain compatible with TTML1 documents.

**Comment by nigelmegitt** [comment]
Also incorporate the fix to w3c/ttml1#214.

**Comment by skynavga** [comment]
TTML2 will require a somewhat different treatment, since ```region``` inherits from ```tt```, unlike TTML1, which doesn't allow inheritable styles on ```tt```.

**Comment by skynavga** [comment]
Resolved in 8abbce40aff32c96eef8bde16815991a2b36ec07.

**Comment by palemieux** [comment]
The definition _styled element_ is not necessary (and confusing) since _Style Resolution Process_ occurs in _Synchronic Flow Processing_, after _Intermediate Synchronic Document Construction_. Just as body elements are reparented to region elements, region elements can be reparented to tt, eleminating the need for _styled element_ .

**Comment by skynavga** [comment]
I'm re-closing this issue. Please open a new issue if you wish.

**Comment by palemieux** [comment]
For discussion at the next TTWG call.

**Comment by skynavga** [comment]
Closing again. If you want to open a new issue, please do so.

**Comment by nigelmegitt** [comment]
[as Chair] @skynavga please remember that we have a 10 day review period - since @palemieux is requesting a change to the pull request that was merged early, and marked as such, it is reasonable to allow the issue to remain open until there is consensus on the edits. I am reopening this.

**Comment by skynavga** [comment]
Closing again. The original resolution was not an early merge. Please file a new issue regarding use of "styled element".
