### ISSUE TITLE
Cell metric in tts:textOutline

### ISSUE THREAD

**Issue by palemieux** [w3c/ttml2#217]
In Section 10.2.47:

> When a <length> expressed in cells is used in a tts:textOutline value, the cell's dimension in the block progression dimension applies. 

Is the intent for for the computed value of an outline thickness specified in "c" to depend on writingMode (to determine block progression direction)? Note that the example does not provide a value for writingMode.

I would think it would be unexpected to have an outline thickness of "1c" yield different results across regions depending on writingMode, even though cellResolution remains unchanged by definition.

Should the prose read _When a <length> expressed in cells is used in a tts:textOutline value, the computed cell height applies._?

**Comment by palemieux** [comment]
Also, note that fontSize="1c" "refers to the height of the Computed Cell Size", independently of block progression direction.

**Comment by skynavga** [comment]
the group needs to consider this since TTML1 already makes use of this definition, albeit, in a note; personally, I don't have a problem with the proposed change

**Comment by nigelmegitt** [comment]
[Meeting 2016-11-03] Discussed in meeting; group agreed to make c units on `tts:textOutline` refer to the height of a computed cell, and following wide review to issue an errata to the existing TTML1 notes to correct them.
