### ISSUE TITLE
Step 10.4.4.2(6)(a) does not apply to textDecoration

### ISSUE THREAD

**Issue by palemieux** [w3c/ttml2#219]
Section 10.2.44 implies that styling inheritance should apply to each of the underline, lineThrough and overline decorations individually.

_if P is present in the specified style set of E, SSS(E), then continue to the next style property_ in step 10.4.4.2(6)(a) need to be rephrased.

**Comment by skynavga** [comment]
No it doesn't. There is only one textDecoration property, and it applies equally to underline, overline, and line through.

**Comment by palemieux** [comment]
If the parent specifies `textDecoration="underline lineThrough"` and the child specifies `textDecoration="noUnderline"`, the result is `textDecoration="lineThrough"`, right?

**Comment by skynavga** [comment]
ok, I see what you are saying; this is a special case where inheritance applies even when there is an explicit inline style; hmm, going to have to think about this a bit;

**Comment by nigelmegitt** [comment]
[Meeting 2017-01-12] Agreed that @skynavga will craft some words to say that each individual property is inherited separately, resulting in the outcome described in https://github.com/w3c/ttml2/issues/219#issuecomment-258591321.

**Comment by skynavga** [comment]
Resolved in #308 merge.
