### ISSUE TITLE
xml:space inheritance rules during ISD construction

### ISSUE THREAD

**Issue by palemieux** [w3c/ttml2#220]
XML specifies _this declared intent [of xml:space] is considered to apply to all elements within the content of the element where it is specified, unless overridden with another instance of the xml:space attribute._

TTML specifies _the xml:space attribute may be used with any element in the core vocabulary catalog except parameter vocabulary._

TTML does not mention processing of `xml:space` in the ISD construction process.

Will an `xml:space` value specified on the `head`, `layout` and `region` elements apply (unless overridden) to all descendants of region elements resulting from the ISD construction process (and override `xml:space` values placed on the `body` element)?

**Comment by palemieux** [comment]
Reading Section 2.10 at https://www.w3.org/TR/xml/#sec-white-space, it looks like the value of `xml:space` is determined (on `span`) by the structure of the XML document, prior to ISD construction and style resolution.

**Comment by skynavga** [comment]
Correct. The same applies to xml:lang. It would be useful to add a note to this effect in TTML[12].
