### ISSUE TITLE
tts:unicodeBidi="bidiOverride" set incorrectly in WritingMode008.xml

### ISSUE THREAD

**Issue by palemieux** [w3c/ttml2#243]
`tts:unicodeBidi="bidiOverride"` is set on region, but `tts:unicodeBidi` applies to `p` and `span` and does not inherit.

**Comment by skynavga** [comment]
Shouldn't you be reporting this against TTML1? We don't have a test suite
for TTML2 (yet).

**Comment by palemieux** [comment]
I was looking at https://github.com/w3c/ttml2/tree/gh-pages/testsuite .

Yes, it is also against TTML1.

**Comment by skynavga** [comment]
The contents of the testsuite directory in the ttml2 repo are merely a side
effect of having originally copied the ttml1 repo. But it has no standing
as a test suite for ttml2, so let's close this and open against ttml1 repo
only until we have a test suite plan for ttml2. If you like, you can open a
general issue against ttml2 for the purpose of establishing a test suite.

**Comment by palemieux** [comment]
Ok. Will open against TTML1.

Shouldn't the TTML1 tests be included in the TTML2 tests since TTML2 is expected to be a superset? The TTML1 tests do not necessarily need to be part of the implementation report however.

**Comment by skynavga** [comment]
On Mon, Feb 13, 2017 at 12:11 AM, Pierre-Anthony Lemieux <
notifications@github.com> wrote:

> Ok. Will open against TTML1.
>
> Shouldn't the TTML1 tests be included in the TTML2 tests since TTML2 is
> expected to be a superset?
>
Probably. But we need to develop a testing plan. In the mean time, please
file any TS bugs against the ttml1 repo only.

**Comment by palemieux** [comment]
Ok. Done: https://github.com/w3c/ttml1/issues/234
