### ISSUE TITLE
Signaling HDR pixels in PNG for use with <image>

### ISSUE THREAD

**Issue by palemieux** [w3c/ttml2#244]
The TTML2  allow PNG images to be displayed. In order to allow the use of the `image` with HDR video (see #233 for additional background on HDR video), TTML2 should support PNG sources carrying HDR images as specified in the [attached](https://github.com/w3c/ttml2/files/778427/png_st2084_20170125.zip). The latter is intended to be compatible with current PNG implementations and uses existing PNG structures:

- HDR pixels are carried PQ-encoded using full-range quantization
- the profile name field of the iCCP chunk is used to signal the color system
- implementations that do not recognize the magic profile names but
support the iCCP chunk will process the image using an embedded ICC
profile, which can evolve as the ICC standard evolves
- implementations that do not recognize the iCCP chunk should display
the image according to the cHRM and gAMA chunks
- implementations that ignore iCCP, cHRM and gAMA chunks will still
display the image
- implementations that merely blit the PNG onto video with the same
HDR colorspace, but without any color conversion, would end-up with an
adequate image

**Comment by nigelmegitt** [comment]
How is this a wide or horizontal review comment @skynavga ?

**Comment by skynavga** [comment]
On Tue, Mar 28, 2017 at 11:02 AM, Nigel Megitt <notifications@github.com>
wrote:

> How is this a wide or horizontal review comment @skynavga
> <https://github.com/skynavga> ?
>
I don't understand your question.

**Comment by nigelmegitt** [comment]
Apparently @skynavga you added a "wide review comment" label on Feb 17 which is now showing up as a "horizontal review comment" however it looks like an issue raised by @palemieux hence my confusion about the labelling on this bug.

**Comment by skynavga** [comment]
Given that TTML2 does not specify support for any specific image type, and, further, does not specify any details or constraints on how some image type may be supported, I oppose this proposed change. On the other hand, if TTML2 does take on the task of specifying support for image types, and those types happen to include PNG, then it would be reasonable to consider this proposed change.

**Comment by palemieux** [comment]
Handling of HDR images is as important as handling HDR text. A potential alternative would be to publish the proposed annex as a WG note.

**Comment by nigelmegitt** [comment]
Meeting 2017-04-13: Agreed to draft a WG Note for this and reference it from TTML2. @palemieux to draft the Note.

**Comment by nigelmegitt** [comment]
Closing this for now since any request to add a reference to the WG Note can be a new issue later.

**Comment by nigelmegitt** [comment]
The WG Note will live in https://github.com/w3c/png-hdr-pq

**Comment by svgeesus** [comment]
should I send review comments here, or on the new repo? I have a bunch of questions, actually.

**Comment by palemieux** [comment]
@svgeesus I am working on a first version, so recommend posting issues directly against it once it is available.

**Comment by palemieux** [comment]
Initial draft at https://w3c.github.io/png-hdr-pq/
