### ISSUE TITLE
Why not use elements for ruby?

### ISSUE THREAD

**Issue by r12a** [w3c/ttml2#245]
10.2.34 tts:rubyAlign [and other sections]
https://www.w3.org/TR/2016/WD-ttml2-20161117/#style-attribute-rubyAlign

> The tts:ruby attribute is used to specify the application of ruby styling.
> This attribute may be specified by any element type that permits use of attributes in the TT Style Namespace; however, this attribute applies as a style property only to those element types indicated in the following table.
>  ...
> Applies to:	span

It's not clear to me why ruby markup is specified using spans-with-attributes, especially when the attribute significantly constrains the expected behaviour of the span.  It seems more logical to use inline elements to establish the semantic mappings between items that constitute a base text with ruby.  I understand that very few elements are used with TTML, but i think that using `ruby`, `rb`, and `rt` in this case would make life much simpler for  both user and spec editor, and since they are inline elements, they reflect semantic mappings rather than styling, and that seems it could be squeezed into the current model without too much pain(?).

**Comment by dronca** [comment]
This may be a small and relatively pain-free model change from the spec perspective, it is a significant change for the TTML2 implementations that have been stood up as part of the TTML2 spec effort.  This request is too late to be considered for TTML2 and we recommend that it be deferred to TTML3.

**Comment by skynavga** [comment]
My recommendation is to have the group decide to reject this proposal for the following reasons:

 * introduces new element vocabulary for no reason, when attributes can serve same purpose; a design principle of TTML being to minimize element count to the bare minimum, which is achieved with div, p, span, and br;

 * existing implementations of tts:ruby already in use in the field;

 * ARIB TTML extensions to add ruby are based on use of extension style attributes, so the current treatment is more consistent with those extensions;

**Comment by r12a** [comment]
Ok.
