### ISSUE TITLE
Complex ruby is usually both mono and group ruby

### ISSUE THREAD

**Issue by r12a** [w3c/ttml2#246]
10.2.33 tts:ruby
Example Fragment – Complex Ruby
https://www.w3.org/TR/2016/WD-ttml2-20161117/#style-attribute-ruby-example-2-images

A much more representative example of complex ruby would show mono-ruby before and group ruby after.

`<span tts:ruby="text">とうなん</span>` should be changed to 

`<span tts:ruby="text">とう</span><span tts:ruby="text">なん</span>`

**Comment by r12a** [comment]
If the behaviour is not defined for the mismatch case you need to change other parts of the spec. 

For example, the following

> This model corresponds to the maximal content model for the ruby element defined by [Ruby], §2.1

though technically accurate wrt the table in §2.1, is slightly misleading because the maximal content model for [Ruby] as a whole also includes the `rbspan` attribute, which allows the definition of complex ruby in that spec to be stated as not just double-sided ruby, but "Defining more fine-grained associations between parts of a ruby text and parts of the base text".

I would therefore recommend to  change the term 'complex ruby' to 'double-sided ruby', because what you have is not really complex, and the term 'complex' sets the wrong expectation. (I am ignoring the argument that, in normal text, phonetic mappings are usually character by character whereas semantic mappings are often related to multiple base characters – which is why multiple mappings in double-sided ruby (which typically involve both a phonetic and semantic annotation) are comonplace in ordinary text.)

You should also clarify in the spec that such mismatched mappings are (at least currently) disallowed – i see nothing in the rules specified (i may have missed it) that prevents authors using, or implementations handling, multiple mappings in double-sided ruby.  (Note that in HTML this multiple mapping is easy to do, and doesn't require an rbspan attribute.)

**Comment by cconcolato** [comment]
I have changed the term in 60c75ef. 
Regarding disallowing the use of mismatched mappings, we already have some text for that in https://github.com/w3c/ttml2/pull/623: 
> This version of TTML leaves the mapping between Ruby Base Content and Ruby Text Content undefined when the number of Ruby Text Content does not equal the number of Ruby Base Content in the same Ruby Container. 

Can you approve the PR?

**Comment by nigelmegitt** [comment]
@cconcolato do you mean pull request #618?

**Comment by nigelmegitt** [comment]
I see that both #618 and #623 have been merged, so my question in https://github.com/w3c/ttml2/issues/246#issuecomment-365937104 is moot.

**Comment by nigelmegitt** [comment]
@r12a The term "complex ruby" has now been removed, and the definition of [`tts:ruby`](https://w3c.github.io/ttml2/index.html#style-attribute-ruby) now uses the term "double-sided ruby". There is a note, just above the example for simple ruby, which explains that mismatched mappings are syntactically permitted but have undefined behaviour.

I've classified this as "WR resolved partial" because I think we have at least partially addressed the issue. Please could you indicate for wide review if this issue has been resolved to your satisfaction?

**Comment by nigelmegitt** [comment]
I changed the labels on this issue because we did in fact make some spec changes to address it, and therefore did not ultimately reject the wide review comment.

**Comment by r12a** [comment]
The i18n WG has closed its tracker for this issue.
