### ISSUE TITLE
How to handle mismatched sequences in complex ruby 

### ISSUE THREAD

**Issue by r12a** [w3c/ttml2#247]
I may have missed it, but i think the spec doesn't say anything about what should happen if, for example, an rbc contains 2 rb items and the rtc contains 4 rt items, or vice versa.

**Comment by nigelmegitt** [comment]
@r12a drawing your attention to the above resolution.

**Comment by r12a** [comment]
chaps, i've been swamped this week and unable to get to this stuff. I plan to try to do so tomorrow.

**Comment by r12a** [comment]
Hm. Well it's good at least that the spec now recognises that it doesn't address the problem. The note by Cyril is clear, and addresses my original question. I'll report back to the i18n WG.

**Comment by r12a** [comment]
The i18n WG has closed its tracker for this issue.
