### ISSUE TITLE
NR is less than NB and NB is equal to 1

### ISSUE THREAD

**Issue by r12a** [w3c/ttml2#249]
10.2.34 tts:rubyAlign
https://www.w3.org/TR/2016/WD-ttml2-20161117/#style-attribute-rubyAlign

> otherwise, if NR is less than NB, the semantics of spaceAround or spaceBetween apply, respectively, according to whether NB is less than or equal to one (1) or is greater than one;

if NR is less than NB and NB is equal to 1, then NR has to be 0, in which case i don't see why the respectively difference is applied.  What am i missing?

**Comment by nigelmegitt** [comment]
The notes above don't clearly show this, but my sense was that we agreed to modify the text to deal with the point that the degenerate case does not exist when NR and NB are both equal to 1.

**Comment by cconcolato** [comment]
As implemented in #604, we suggest to solve the issue by removing the complex 'auto' behavior. This is related to Netflix's whitepaper in which we indicated that 'center' should be the default value.

**Comment by nigelmegitt** [comment]
@r12a please could you take a look at this proposal and the pull request linked to this issue (#604) and let us know if the proposal would resolve the issue? Cyril and I think it does; I just want to be sure. (plus it would allow us to mark the comment as "commenter-agreed", if you're happy with it)

**Comment by nigelmegitt** [comment]
Reopening pending commenter feedback.

**Comment by r12a** [comment]
This LGTM. I'll ask the i18n WG to close our tracker.

**Comment by r12a** [comment]
The i18n WG has closed its tracker for this issue.
