### ISSUE TITLE
Support for bopomofo ruby needed

### ISSUE THREAD

**Issue by r12a** [w3c/ttml2#253]
10.2.39 tts:rubyPosition
https://www.w3.org/TR/2016/WD-ttml2-20161117/#style-attribute-rubyPosition

There is no mention of support for zhuyin fuhao/bopomofo ruby, needed for Traditional Chinese.  Please add something.

For background information see http://w3c.github.io/clreq/#overview_of_positioning_of_interlinear_annotations ff

**Comment by dae-kim** [comment]
Suggest we move this to a new feature request in ttml.next

I believe we discussed this in prior meetings and agreed bopomofo is more a printed book feature, not so much a subtitle feature. The Chinese subtitle vendors we spoke with do not use bopomofo in their subtitles.

**Comment by nigelmegitt** [comment]
I consider the general feature target in TTML2 to be the ability to present text in every script, and this is something that @skynavga has confirmed is the intention previously, so if bopomofo is a presentation requirement for a script, I think it is in scope of TTML2.

**Comment by dae-kim** [comment]
To reiterate my stance on my previous comment, bopomofo is more a printed book feature than a subtitle feature.

If Chinese subtitlers do not use bopomofo currently, are not asking for bopomofo support in the near future, and no one will be able to prove implementation support of bopomofo, is this really something that needs to be solved in TTML2?

As I recall during TPAC Sapporo, the i18n group itself was at odds on whether bopomofo could be supported in a ruby context.

Do we have any subtitle-specific examples of bopomofo?

**Comment by r12a** [comment]
@bobbytung any input on this?

**Comment by nigelmegitt** [comment]
[TTWG Meeting 2017-03-09] We will await the response to @r12a 's question before taking further action on this.

**Comment by nigelmegitt** [comment]
Meeting 2017-03-09: In the absence of further data points our default position on this will be to add a note recognising current non-support of bopomofo Ruby and possibly prompting for contact if anyone needs it; if we get positive data points before we have to close this off we may address this again depending on those data points.

**Comment by skynavga** [comment]
Resolved in merge of #303, an editorial only PR.

**Comment by nigelmegitt** [comment]
@r12a Does the updated text satisfy you as a resolution to this issue? There was some discussion in the group about how important it may be to include the term "zhuyin fuhao" in addition to "bopomofo" given that bopomofo is used in CSS and Unicode. The Editor made the call to remove "zhuyin fuhao" in this case.

**Comment by r12a** [comment]
From Wikipedia:

> Zhuyin fuhao, Zhuyin or Bopomofo (pinyin: bōpōmōfō, Mandarin IPA: [pwópʰwómwófwó]) is a system of phonetic notation for the transcription of spoken Chinese, particularly the Mandarin dialect. The first two are traditional terms, whereas Bopomofo is the colloquial term, also used by the ISO and Unicode.

"Zhùyīn fúhào" is not used in the CSS spec. Clreq (chinese layout requirements) doc uses just Zhuyin. (The glossary adds Bopomofo in parens.)

I think more western people are familiar with bopomofo than with zhùyīn fúhào, so i'm not sure i have any particular objection.

It would have been nice to have hinted why it is not supported, though (ie. lack of user demand). I think that would have made it more likely for users to provide evidence of a need if it's available.

**Comment by nigelmegitt** [comment]
Thank you @r12a, I hope to raise that point in an upcoming meeting, of if we should add a hint of why it is not supported.

**Comment by skynavga** [comment]
Resolved last comment by @r12a in 10fdea62e02b422a4a1bc4cefcc782c495b364e6.

**Comment by nigelmegitt** [comment]
Thanks @skynavga assuming that's okay for everyone else I think that works - it does for me, and it appears to address @r12a 's points also - confirmation welcome!

**Comment by r12a** [comment]
lgtm, thanks

**Comment by skynavga** [comment]
[Meeting 05/11/17] Group reviewed closure. No objection or further comment.

**Comment by r12a** [comment]
Thank you for considering this issue. The i18n WG is now closing this issue in its review tracker.
