### ISSUE TITLE
Default ruby position may be on the wrong side for tblr (eg. mongolian)

### ISSUE THREAD

**Issue by r12a** [w3c/ttml2#254]
10.2.39 tts:rubyPosition
https://www.w3.org/TR/2016/WD-ttml2-20161117/#style-attribute-rubyPosition

`before` is mapped in the table to 'left' for 'tblr' writing mode (ie. Mongolian).  `before` is also the default value.  I think this is probably incorrect for tblr writing systems like Mongolian.

See an example of Mongolian ruby at https://github.com/w3c/mlreq/issues/4

**Comment by dae-kim** [comment]
Personally consider this to be a minor issue.

It's up to the author to determine that default values of any attribute do not align with their specific writing system/mode.

For example, the default value of displayAlign is "before". Given a large region, text would display towards top of screen. If authors want their text to display at bottom of any given region, they must explicitly set displayAlign to the appropriate value.

**Comment by r12a** [comment]
I can't see why this would be a minor issue. The spec is setting a default value for people using vertical writing-mode with lines progressing from left to right that is incorrect for probably everyone who will use that. It means that people whose writing system uses that orientation, ie. users of Traditional Mongolian, Manchu, Sibe, Todo, etc., have to always override the default for any text they use, and probably no-one will ever need to use the default.  I can't see how that makes sense.

Note that CSS makes a distinction between `before` and `after`, and `over` and `under` specifically to address this issue. In the case of vertical-lr, `over` means to the _right_ of the vertical line, rather than to the left. And vice versa for `under`.  In other words, things like ruby, overline, underline, etc. appear on the same side of the line for mongolian script vertical text as for CJK.

**Comment by dae-kim** [comment]
As mentioned with my example on displayAlign and the default "before" ... most implementers explicitly set displayAlign to "after". So in terms of displayAlign's default value, most authors and consumers of TTML1 (and 2) probably consider "before" to be incorrect.

This does not stop authors from explicitly setting the displayAlign value to "after" by default.

I understand the default value is not ideal, but that does not stop an author from setting the proper value and achieving the correct display does it?

**Comment by dae-kim** [comment]
To follow guidance on resolution to https://github.com/w3c/ttml2/issues/240

**Comment by nigelmegitt** [comment]
Scheduled for discussion 2017-03-23.

**Comment by nigelmegitt** [comment]
Meeting 2017-03-23: See last comment on #240 - add a note about the ability to set preferred defaults.

**Comment by dae-kim** [comment]
See https://github.com/w3c/ttml2/pull/332

**Comment by nigelmegitt** [comment]
This was a horizontal review comment and should not have been closed without feedback on the disposition from the issue raiser. @r12a does the merged pull request #332 address the issue adequately?

**Comment by dae-kim** [comment]
@nigelmegitt @r12a 
During the TTWG call Richard attended, it was stated (agreed?) this issue would be handled the way #332 is resolved.

**Comment by dae-kim** [comment]
@nigelmegitt 
Given https://github.com/w3c/ttml2/issues/254#issuecomment-308770557, I suggest we close.

**Comment by nigelmegitt** [comment]
@dae-kim are you referring to your own comment where you're not sure that there was agreement as evidence that we should close this? You may well be right, however I'd be happier if @r12a could answer my question to him in https://github.com/w3c/ttml2/issues/254#issuecomment-304304996 in which I explicitly ask if the resolution for #332 addresses this issue.

**Comment by r12a** [comment]
There's no question that it's _possible_ for Mongolian users to produce the behaviour they expect, by adding a setting to the document.

To be honest, however, i still expect that Mongolian authors, who are the natural users of tb-lr mode text, will be disappointed to have to make some effort every time, albeit small, so that the technology works in the way they would expect things to work by default. This clearly indicates to them that the technology was not designed with them in mind as primary users.

Is this enough to cause i18n to raise a formal objection? Probably not (however, i will need to defer to the i18n WG for a final decision on this). If you were to tell me that you had talked with content authors in Mongolia about their requirements, and they are not concerned, i would feel easier.  I have to admit that i haven't had much feedback from Mongolia either, though, other than to confirm what their normal expectation for positioning ruby would be. 

One practical point: https://github.com/w3c/ttml2/pull/332 is resolved by a note in 10.2.48 tts:textEmphasis.  This is about 10.2.39 tts:rubyPosition.  Are we expecting to include another similar note here?

**Comment by nigelmegitt** [comment]
Thanks for that @r12a - and yes, if we adopt the same kind of resolution as we did for #332 then we would need a similar note here.

**Comment by r12a** [comment]
Please let us know if/when you have added the note referred to above, and we will close the pointer to this issue in our review tracker. Thanks.

**Comment by skynavga** [comment]
I18N WG has accepted and closed this issue in their review tracker.

**Comment by skynavga** [comment]
Got ahead of myself here, so reopening to address adding a note as mentioned above.

**Comment by skynavga** [comment]
@r12a a note as described above has been merged to resolve this issue; please inform us of disposition in I18N WG
