### ISSUE TITLE
 Please provide more illustrations and examples for the ruby sections

### ISSUE THREAD

**Issue by r12a** [w3c/ttml2#256]
This will make it much easier to understand, and improve the quality of the review.

(Actually this is true for other sections, too.)

**Comment by dae-kim** [comment]
See: https://github.com/w3c/ttml2/pull/273

**Comment by r12a** [comment]
Thank you for the new examples and images. Very helpful.  There are one or two specific comments i have on the new material, which i'll raise as separate issues.

**Comment by dae-kim** [comment]
Closed. See https://github.com/w3c/ttml2/issues/274 and https://github.com/w3c/ttml2/issues/275

**Comment by r12a** [comment]
Thank you for considering this issue. The i18n WG is now closing the pointer to this issue in its review tracker.
