### ISSUE TITLE
Make it clearer that tts:rubyOverflow only applies to text that is at the end of a line

### ISSUE THREAD

**Issue by r12a** [w3c/ttml2#257]
10.2.36 tts:rubyOverflow
https://www.w3.org/TR/2016/WD-ttml2-20161117/#style-attribute-rubyOverflow

> If specified, the value of tts:rubyOverflow expresses how to resolve potential overflow scenarios where ruby text may otherwise overflow its containing block in line start or end edge contexts.

That sentence clarifies the intended application of this property iiuc: ie. to do with line start/end situations and _not_ about overhanging adjacent text (which is dealt with by rubyOverhang). Such scenarios are mentioned as 'an' example of use in the first para in the section, leading to ambiguity about the applicability of this property when you read the section.

I think the sentence quoted above should come at the start of the section, and the text clarified to more clearly indicate that this is all about scenarios where the annotation at the start/end of a line is wider than the base text.

**Comment by skynavga** [comment]
OBE (see #515).
