### ISSUE TITLE
 How to space base characters where shiftRuby kicks in for group ruby?

### ISSUE THREAD

**Issue by r12a** [w3c/ttml2#258]
10.2.36 tts:rubyOverflow
https://www.w3.org/TR/2016/WD-ttml2-20161117/#style-attribute-rubyOverflow

jLReq makes a distinction between (a) handling of annotation alongside a single base character, and (b) annotation alongside multiple base characters in the `shiftRuby` case. For (b), the base characters are spread evenly as in this diagram.

![img2_3_36](https://cloud.githubusercontent.com/assets/4839211/22987949/56468b9e-f3a8-11e6-9af0-f6ed06654062.png)

How would one apply that behaviour specifically to the ruby items where `shiftRuby` has been applied to prevent overflow?

**Comment by dae-kim** [comment]
I'm not sure what the diagram is showing.

Are the spaces between base characters authored that way (B A S E)?
Or are the spaces between base characters artificially inserted after the fact (BASE)?

In either case, shiftRuby will move the annotations and will not introduce artificial spacing between base characters. Whether the annotations are applied to a single base character or multiple base characters, shiftRuby will not alter base characters or the relationship/positioning between base characters.

**Comment by r12a** [comment]
> Are the spaces between base characters authored that way (B A S E)?
> Or are the spaces between base characters artificially inserted after the fact (BASE)?

The **gaps** are automatically created (in a similar way as, i assume, would happen for shiftBase in order to produce a gap at the start of the line per your diagram in 10.2.37,  or when using `rubyAlign` set to `spaceAround`).

Jlreq expects overflow to be handled as shown in your diagram in 10.2.37 when an annotation appears alongside a single character, but in the case where a group ruby annotation appears alongside multiple characters, it calls out a different behaviour:

> Group-ruby at the line head: Make adjustments so that the top of the ruby text is aligned with that of the first base character, and _add the same amount of inter-character space between the base characters and between the end of the last base character and the end of the last ruby character after the last base character_ (the method specified in JIS X 4051) (see Fig. 3.87). [which is the figure in my first comment box above] [my emphasis]

I was wondering how a content author would obtain that behaviour, if they wanted it. I assume that they would start by setting `rubyOverflow` to `shiftRuby`, and then set `rubyOverhang` to `none`, and then set `rubyAlign` to something.  However, i see two problems:
1. there doesn't seem to be a way to set `rubyAlign` so that either the start or end of both the base and annotation are aligned, but there are also gaps around the base characters.
2. i'm not sure how you'd make that apply only in the case where the group ruby happens to start or end a line, unless you put in hard line breaks and set styling explicitly for those cases.

So, i guess the answer is, you can't produce that behaviour in TTML.

**Comment by dae-kim** [comment]
> So, i guess the answer is, you can't produce that behaviour in TTML.

I don't believe you can and I don't see any need for it in a subtitle context.

**Comment by dae-kim** [comment]
Suggest we close since there is no action to be taken.
@r12a thought?

**Comment by dae-kim** [comment]
@nigelmegitt 
Given that Japanese subtitle authors and consumers do not expect this type of functionality, I suggest we close as non-issue.

**Comment by nigelmegitt** [comment]
@dae-kim Just so we understand where our basis for this comes from, is your evidence that authors and consumers do not expect this type of functionality only the lack of support for it in Lambda CAP? Or are there other data points we can use to support it?

**Comment by dae-kim** [comment]
@nigelmegitt Based on conversations with Japanese subtitle companies based in Japan, they have never heard of this requirement. Nor have their customers asked for any such functionality (even as image based subtitles). The general reaction to this feature from the Japanese subtitling industry is, "the rules for media entertainment is different from one for printing material".

**Comment by r12a** [comment]
Based on the information that this aspect of jlreq is not supported for TTML in Japan at the moment, the i18n WG is now closing the pointer to this issue in its review tracker. Thank you.

**Comment by skynavga** [comment]
In the future, a new keyword could be added to support this behavior, e.g., `shiftRubyDistributeBase`, or perhaps `shiftRubyDistribute` as a short hand. In any case, the I18N WG has closed this issue in their review tracker. I am marking as `works for me` and closing at this time.
