### ISSUE TITLE
Simplify description of shiftRuby (editorial)

### ISSUE THREAD

**Issue by r12a** [w3c/ttml2#259]
10.2.36 tts:rubyOverflow
https://www.w3.org/TR/2016/WD-ttml2-20161117/#style-attribute-rubyOverflow

Editorial (i think, unless i'm missing something – which is certainly possible).

> If the value of this attribute is shiftRuby, then overflow is prevented by relaxing the ruby text to base text alignment by inseting the ruby text while preserving base text to line edge alignment. When inseting ruby text, the semantics of tts:overHang apply for the purpose of determining whether and how much overhang is permitted between the inset ruby text and adjacent base text.
> 
> When inseting ruby text or base text in order to resolve a potential overflow scenario, only the minimum (non-negative) inset is applied.

Isn't this rather long description about insetting the ruby text just a question of saying align both ruby text and base text with the line edge?

**Comment by skynavga** [comment]
OBE (see #515).
