### ISSUE TITLE
Should rubyOverhang:allow overlap ideographs in Japanese?

### ISSUE THREAD

**Issue by r12a** [w3c/ttml2#260]
10.2.38 tts:rubyOverhangClass
https://www.w3.org/TR/2016/WD-ttml2-20161117/#style-attribute-rubyOverhangClass

My reading of jLReq is that by default it does not allow overlap of kanji characters. See the [bullet points just below Fig 136](https://w3c.github.io/jlreq/#adjustments_of_ruby_with_length_longer_than_that_of_the_base_characters).

> a. Ruby text shall not hang over the ideographic characters (cl-19) adjacent to the base characters.

Notes further down admit alternative styles, one of which allows overhang of kanji, the other forbids any overhang at all, but these seem not to be mainstream.

Therefore, i suspect that 

> If the language of the base text is specified or can be inferred as Japanese, then auto should be interpreted as if the following were specified: ideographic hiragana punctuationMarks.

should drop the `ideographic`.

**Comment by skynavga** [comment]
OBE (see #515).

**Comment by skynavga** [comment]
@r12a regarding your original comment, I had chosen what I believed to be the simplest approach for implementation purposes, which was to allow overhang on ideographs, as is depicted in Figure 139; however, now that we have decided to remove support for tts:ruby{Overflow,Overhang}, the defaults we pick will be more important, so I will double check with the group on this approach

**Comment by nigelmegitt** [comment]
@skynavga what is OBE? (Out of Bounds Error? Order of the British Empire?)

**Comment by skynavga** [comment]
On Tue, Jan 2, 2018 at 2:48 PM, Nigel Megitt <notifications@github.com>
wrote:

> @skynavga <https://github.com/skynavga> what is OBE? (Out of Bounds
> Error? Order of the British Empire?)
>
overtaken by events

**Comment by nigelmegitt** [comment]
@skynavga thank you, that one is new to me.

**Comment by nigelmegitt** [comment]
@r12a does removal of `tts:rubyOverhang` address this issue to your satisfaction? (asking for HR/WR tracking purposes - this means you have 2 weeks to respond!)

**Comment by skynavga** [comment]
No response from @r12a, so closing this issue with appropriate labels.
