### ISSUE TITLE
Use a more typical example for tts:direction

### ISSUE THREAD

**Issue by r12a** [w3c/ttml2#262]
10.2.12 tts:direction
https://w3c.github.io/ttml2/spec/ttml2.html#style-attribute-direction

Bidi overrides are very rarely used. I think it would be better to show how this can help everyday situations for people using bidi scripts, which they will absolutely need to deal with, such as getting the W3C to appear on the correct (left) side of

```
The title of the page was
نشاط التدويل، W3C
```

**Comment by palemieux** [comment]
@r12a Can you confirm that the top region in the PNG below is the proper output given the following TTML snippet?

```
<?xml version="1.0" encoding="UTF-8"?>
<tt xmlns="http://www.w3.org/ns/ttml" xmlns:tt="http://www.w3.org/ns/ttml" xmlns:ttp="http://www.w3.org/ns/ttml#parameter"
 xmlns:tts="http://www.w3.org/ns/ttml#styling" xmlns:ebuttm="urn:ebu:metadata"
 xml:lang="en" ttp:cellResolution="50 30">
	<head>
		<metadata>
			<ebuttm:documentMetadata>
				<ebuttm:conformsToStandard>urn:ebu:distribution:2014-01</ebuttm:conformsToStandard>
				<ebuttm:conformsToStandard>http://www.w3.org/ns/ttml/profile/imsc1/text</ebuttm:conformsToStandard>
			</ebuttm:documentMetadata>
		</metadata>		
		<styling>
			<style xml:id="paragraphStyle" tts:color="#ffffff" tts:backgroundColor="#000000" tts:fontSize="160%" tts:fontFamily="monospaceSerif" tts:textAlign="left" />			
			<style xml:id="embedRTL" tts:direction="rtl" tts:unicodeBidi="embed"/>
		</styling>
		<layout>
			<region xml:id="top" tts:origin="10% 10%" tts:extent="80% 80%" tts:displayAlign="before" tts:writingMode="lrtb"/>
            <region xml:id="bottom" tts:origin="10% 70%" tts:extent="80% 20%" tts:displayAlign="before" tts:writingMode="lrtb"/>
		</layout>
	</head>
	<body>
		<div>
			<p xml:id="subtitle1" region="top" begin="00:00:00.000" end="00:00:10.000" style="paragraphStyle">
				The title of the book is <span style="embedRTL" xml:lang="ar">نشاط التدويل، W3C</span>
			</p>
      <p xml:id="subtitle1" region="bottom" begin="00:00:00.000" end="00:00:10.000" style="paragraphStyle">The title of the book is نشاط التدويل، W3C</p>
		</div>
	</body>
</tt>
```
![0](https://cloud.githubusercontent.com/assets/4871350/25685929/836492de-301f-11e7-8c17-952e0fdc1d52.png)

**Comment by r12a** [comment]
@palemieux the output looks like what i'd expect to see, given the markup – it may be clearer if you add quote marks around the title, btw. (and don't forget to put those outside the span, since they are part of the surrounding text.)

Of course, in the bottom line the text is incorrectly arranged. Assuming that you meant to show broken text in the bottom region, and will explain that to the reader, i think it's correct.

**Comment by palemieux** [comment]
> it may be clearer if you add quote marks around the title, btw. (and don't forget to put those outside the span, since they are part of the surrounding text.)

Will do.

> Of course, in the bottom line the text is incorrectly arranged. Assuming that you meant to show broken text in the bottom region, and will explain that to the reader, i think it's correct.

The PR will remove the bottom region.
