### ISSUE TITLE
It should be easier to specify direction for RTL script users 

### ISSUE THREAD

**Issue by r12a** [w3c/ttml2#263]
10.2.12 tts:direction
https://w3c.github.io/ttml2/spec/ttml2.html#style-attribute-direction

I may be missing something, but is it correct to assume that a person trying to use TTML for Arabic or Hebrew or any of the many other languages using so-called RTL scripts will need to explicitly add the `tts:writing-mode` or `tts:direction` attribute to every `p` or `div`?  If so, that's a significant disincentive to use TTML for people from those regions. 

One way to approach this might be to allow a file-wide default direction to be set, like using <html dir="ltr" in HTML.

Another may be to make the default `auto`, so that tts:direction only needs to be applied when the auto-detection rules fail (ie. when text in a block begins with a character with a strong opposite directionality).

**Comment by nigelmegitt** [comment]
Hi @r12a I can't answer many of your recent issue questions but this one I think I can: 

`tts:writing-mode` applies to regions, so it is effective on all the content flowed into each region. 

`tts:direction` is inherited (see the table row heading "Inherited", value "Yes") so it can be set on a `region` or ` body` for example and will apply to all the descendants (unless overridden by being specified with a different value on some descendant part of the tree of course).

So, no it is not correct to make that assumption.

**Comment by r12a** [comment]
That's good to know. Thanks.

**Comment by palemieux** [comment]
@r12a Does the information at https://github.com/w3c/ttml2/issues/263#issuecomment-280415104 resolve your comment?

**Comment by skynavga** [comment]
[Meeting 05/11/17] Group resolves to close without action and mark as works for me.

**Comment by nigelmegitt** [comment]
Reopening and requesting confirmation from the issue raiser @r12a that the question has now been answered satisfactorily.

**Comment by skynavga** [comment]
It is not necessary that the issue remain open for the original commenter to make a comment to that effect.

**Comment by nigelmegitt** [comment]
Reopening and moved to a non-Editor's milestone.

**Comment by r12a** [comment]
I believe this has been answered satisfactorily. Thank you. The i18n WG is now closing the pointer to this issue in its review tracker.

**Comment by skynavga** [comment]
I18N WG has accepted and closed this issue in their review tracker.
