### ISSUE TITLE
Link from tts:direction to tts:writing-mode

### ISSUE THREAD

**Issue by r12a** [w3c/ttml2#264]
10.2.12 tts:direction
https://w3c.github.io/ttml2/spec/ttml2.html#style-attribute-direction

> The tts:direction attribute is used to specify a style property that defines the directionality of an embedding or override according to the Unicode bidirectional algorithm.

When i first read this, i thought that `tts:direction` was behaving like `dir` in HTML, or like (i think) `tts:writing-mode=tbrl`, and setting an embedding or override at the same time as signalling the base direction (although i couldn't see how it could do both).

Perhaps it would help to have a note that links to the tts:unicodeBidi section and explains that you need to use both together.

**Comment by palemieux** [comment]
See https://github.com/w3c/ttml2/issues/221 and https://github.com/w3c/ttml1/issues/228
