### ISSUE TITLE
No mention of isolation for directional controls

### ISSUE THREAD

**Issue by r12a** [w3c/ttml2#265]
The Unicode Consortium recommends that embeddings should always isolate the contained text from that surrounding it, to avoid the many possible spillover issues that arise otherwise.  HTML also applies isolation by default.

Isolation is not mentioned in the sections that provide bidi control.  It should be the default.

**Comment by palemieux** [comment]
UA support seems sparse so far for `isolate` seems sparse at this point (https://developer.mozilla.org/en-US/docs/Web/CSS/unicode-bidi).

What are key use cases that `embed` and `override` cannot support but `isolate` can?

**Comment by skynavga** [comment]
Please do not add a horizontal review comment to the TTML2WR milestone unless you have posted a PR.

**Comment by palemieux** [comment]
@skynavga As mentioned before, the folks from MovieLabs plan on resolving all horizontal review comments before wide review.

**Comment by skynavga** [comment]
As I said, I don't mind you adding to the WR milestone when you have posted a PR. As for when those are completely resolved, you at least have until all the other WR issues are resolved. Then it is a question to the group whether to hold up the WR if some HR issues remain open.

**Comment by r12a** [comment]
> What are key use cases that embed and override cannot support but isolate can?

There are a couple of examples at https://www.w3.org/International/articles/inline-bidi-markup/uba-basics#isolation

Before html5 added isolation, this was a constant problem for bidi text.

**Comment by skynavga** [comment]
I generally support adding isolate support, but I do agree it will require implementation and testing work.
