### ISSUE TITLE
Styling using tts:direction: there should be an `auto` value

### ISSUE THREAD

**Issue by aphillips** [w3c/ttml2#268]
https://w3c.github.io/ttml2/spec/ttml2.html#style-attribute-direction

TTML does define a direction attribute for p and span elements for use in controlling text direction (bidi). The values provided are ltr and rtl. There is not auto. Should there be?

sourced from (w3c/i18n-activity/issues/328)

**Comment by palemieux** [comment]
@aphillips What would be the semantics of `auto` and how would it be different than having an initial value specified (`ltr`)?

**Comment by aphillips** [comment]
@palemieux The semantics would be the same as for HTML: the first strong character would determine the direction.

When `dir` is not specified, the default is `ltr`. Specifying `auto` allows for several things, but the main one is: data that is inserted dynamically at runtime (such as document generation time) whose base direction cannot be known by the inserting process. This is fairly common in modern software. [Here ](https://www.w3.org/International/articles/inline-bidi-markup/#dynamicexamples) are a variety examples (given in HTML).

**Comment by palemieux** [comment]
> In this section we will look at use cases that involve injecting content into a page at run time.

I have not see this as a use case in TTML so far.

In any event, doesn't the application that inject the text (`<?php echo $theString; ?>`) know the directionality of the injected text?

**Comment by nigelmegitt** [comment]
>> In this section we will look at use cases that involve injecting content into a page at run time.
>I have not see this as a use case in TTML so far.

Well firstly TTML2 is a document format (information set) and not an in-memory model, and secondly that information set does not allow for text content injection.

However there is in fact a requirement for this feature, R205 at https://www.w3.org/TR/2006/NOTE-ttaf1-req-20060427/#content which as you can see from the table at https://w3c.github.io/ttml2/spec/ttml2.html#requirements is only currently supported in the specification for intrinsic content not extrinsic content.

In some hypothetical future version of TTML in which extrinsic content inclusion is supported, we may need an `auto` value for `tts:direction`, however that is not a currently supported requirement so strictly I do not believe we need `auto` now. It would probably not be harmful to plan ahead by adding the `auto` keyword before then, but given the large workload that we have with TTML2 I would probably defer this for now. Happy to hear (strong) counter-arguments.

**Comment by aphillips** [comment]
> Well firstly TTML2 is a document format (information set) and not an in-memory model, and secondly that information set does not allow for text content injection.

Agreed, but would you allow that TTML2 documents might themselves be generated? Most useful document formats these days do end up being generated via tools. Not all tools have direction information available. They just know that they are going to insert, say, the name of the speaker, a colon, and then what the speaker said.

**Comment by palemieux** [comment]
> Not all tools have direction information available. 

I think it is reasonable to expect subtitling generation tools to have such information available since, after all, there are specifically designed to handle localized content.

**Comment by skynavga** [comment]
CSS3 WM does not include 'auto' value.

**Comment by nigelmegitt** [comment]
Reopening and requesting confirmation from the issue raiser @aphillips that the responses provided answer the question satisfactorily.

**Comment by skynavga** [comment]
It is not necessary for the issue to remain open for the initial commenter to comment.

**Comment by nigelmegitt** [comment]
Reopening and moving to a non-Editor's milestone.
