### ISSUE TITLE
tts:textCombine and combining characters

### ISSUE THREAD

**Issue by r12a** [w3c/ttml2#278]
10.2.43 tts:textCombine
http://w3c.github.io/ttml2/spec/ttml2.html#style-attribute-textCombine

I and other members of the i18n WG found it hard to tell that this is about tate chu yoko, rather than kumimoji, until we get to the information near the bottom about the digits and all values.  It would be good to make that clearer near the top.

> This attribute has no impact on or interaction with the nominal layout of glyph areas that constitute a Unicode combining character sequence.

I'm not sure what this means. Does it mean that in vertical text where `tts:textCombine:all` is applied to the non-Japanese letters in the sequence 

お  ‎304A  HIRAGANA LETTER O
茶  ‎8336  [CJK Unified Ideographs]
は  ‎306F  HIRAGANA LETTER HA
t  ‎0074  LATIN SMALL LETTER T
e  ‎0065  LATIN SMALL LETTER E
́  ‎0301  COMBINING ACUTE ACCENT
で  ‎3067  HIRAGANA LETTER DE
す  ‎3059  HIRAGANA LETTER SU

the acute accent would be part of the horizontal text or not?

**Comment by cconcolato** [comment]
I have used your proposed wording. Can you approve the Pull Request?

**Comment by r12a** [comment]
The i18n WG has closed its tracker for this issue. Thank you for your edits.
