### ISSUE TITLE
Is rubyReserve crucial?

### ISSUE THREAD

**Issue by dae-kim** [w3c/ttml2#282]
One of the main uses for [rubyReserve](https://www.w3.org/TR/ttml2/#style-attribute-rubyReserve) is to ensure base text in any given subtitle lines up with base text with all other subtitles.

Compare the visual example of "none" against the visual examples of "auto" or "outside".

A question that came up is: can this be reliably achieved without rubyReserve?
If so, what are the advantages of rubyReserve over other methods?

**Comment by skynavga** [comment]
> A question that came up is: can this be reliably achieved without rubyReserve?

No.
