### ISSUE TITLE
Update note regarding ISOBMFF and DASH.

### ISSUE THREAD

**Issue by skynavga** [w3c/ttml2#292]
Submitted by @mikedo with blessings from @nigelmegitt, replace note and add informative reference as follows:

>For example [ISOBMFF] provides a mechanism for wrapping TTML documents as samples in segmented and non-segmented files, [MPEG DASH] provides further segmentation semantics for fragmented delivery over HTTP and MPEG-2 TS, and [CMAF] provides a specific segmentation encoding for a TTML profile.
 
>[CMAF] ISO/IEC 23000-19, Information technology — Coding of audio-visual objects — Part 19: Common media application format (CMAF) for segmented media, International Organization for Standardization (ISO). [publication expected August 2017]

**Comment by skynavga** [comment]
Resolved in 4344e321d5241d04fb42202be0def56168262278. Updated ED in 5f695d27d5eaab970d157cfbc5bba46e5fa5e40e.

**Comment by nigelmegitt** [comment]
Meeting 2017-04-20: Agreed to close.
