### ISSUE TITLE
Reference versioning

### ISSUE THREAD

**Issue by mikedo** [w3c/ttml2#293]
I note that a number of references are non-versioned.  That is, no specific version/edition/date is provided in the reference list.  Is this intentional?  If so, what does that mean in W3C?

[FYI, ISO last year started allowing non-versioned normative references, which means basically the latest in force edition.  For normative references this has some downsides, including creating non-interoperable implementations depending on what changed in the underlying specifications versus when in time one implements it. They should only be used with some confidence that updates will have no adverse consequences to implementers.]

Also, why are some references versioned, e.g. 608 and 708 (the letter suffix denotes the version) and some are not versioned, e.g. 12M (no date)?

And, some references are out of date, e.g. "12M" hasn’t been called 12M or approved by ANSI in a really long time. Although there may be cases where the latest version is not desired, in general the latest published version should be cited.

**Comment by nigelmegitt** [comment]
Meeting 2017-04-27: Agreed to prefer versioned references especially for normative reference and to include any dates in the visible text in the references section as well as in the link.

**Comment by skynavga** [comment]
Only the following normative references are undated (un-versioned):

 * [GPS]
 * [RELAX NG]
 * [SMPTE 12M]
 * [SRGB]
 * [UTC]

Does anyone think any of these need to be dated/versioned?

**Comment by skynavga** [comment]
No further comment received, so closing. If someone wishes to propose adding a version/date to one of the above references, please comment here or let me know.

**Comment by palemieux** [comment]
> Does anyone think any of these need to be dated/versioned? 

Per https://github.com/w3c/ttml2/issues/293#issuecomment-297755548, the group _prefers versioned references especially for normative reference_, so yes they should be dated.

**Comment by skynavga** [comment]
Unless someone proposes a specific date to be added, then there is no action to be taken. Please do not reopen unless you make a specific proposal.

**Comment by palemieux** [comment]
sRGB should use CEI/IEC 61966-2-1:1999

**Comment by palemieux** [comment]
SMPTE 12M does not exist anymore. You probably mean http://ieeexplore.ieee.org/document/7291029/

**Comment by palemieux** [comment]
[UTC] is probably the 2002 version at https://www.itu.int/rec/R-REC-TF.460/en

**Comment by palemieux** [comment]
@skynavga More importantly perhaps, this issue is assigned to @mikedo and not you

**Comment by skynavga** [comment]
On Sat, May 6, 2017 at 2:26 PM, Pierre-Anthony Lemieux <
notifications@github.com> wrote:

> @skynavga <https://github.com/skynavga> More importantly perhaps, this
> issue is assigned to @mikedo <https://github.com/mikedo> and not you
>
The editor is free to perform any processing on any issue regardless of
assignees.

**Comment by nigelmegitt** [comment]
@skynavga thanks for doing the prep work to highlight the references that this issue affects, as listed at https://github.com/w3c/ttml2/issues/293#issuecomment-298818711 ; please could you leave a little more time for people to respond though, especially the person to whom this issue is assigned? There weren't even 3 working days on this, assuming most people do not treat weekends as working days. Thank you @palemieux for coming up with some proposals so quickly.

@mikedo I'm going to assume that you will be picking this up and making the proposal for it as discussed.

**Comment by skynavga** [comment]
I believe we do not need to version the [UTC] reference. I'll wait for @mikedo to propose something for SMPTE 12M. I'm ok with the proposed sRGB version.
