### ISSUE TITLE
How to specify aspect ratio to understand positioning that may apply for display or video

### ISSUE THREAD

**Issue by plehegar** [w3c/ttml2#30]
See TTWG Feb 14 Meeting minutes: http://www.w3.org/2013/02/14-tt-minutes.html,text. 

How to specify aspect ratio to understand positioning that may apply for display or video.

(raised by Glenn Adams on 2013-02-21)
From tracker issue http://www.w3.org/AudioVideo/TT/tracker/issues/201

Address any outstanding comments under the following, which are hereby incorporated into this issue:

 - [x] #27 interpreting pixel measure
 - [x] #162 need parameter to express storage aspect ratio

**Comment by skynavga** [comment]
Change the draft ttp:storageAspectRatio to ttp:displayAspectRatio. Deal with over-constrained parameters in the case that DAR, PAR, and extent are all specified.

**Comment by nigelmegitt** [comment]
For information only right now, I'm expecting a related but hopefully orthogonal contribution from an external group on this issue.

**Comment by skynavga** [comment]
Leave open pending review at upcoming F2F.

**Comment by palemieux** [comment]
http://services.w3.org/htmldiff?doc1=https%3A%2F%2Fraw.githubusercontent.com%2Fw3c%2Fttml2%2F2cc5eefe8618342d8648eb90ee259d96ab092cc8%2Fspec%2Fttml2.html&doc2=https%3A%2F%2Fraw.githubusercontent.com%2Fw3c%2Fttml2%2Fgh-pages%2Fspec%2Fttml2.html#root-container-region-semantics

**Comment by palemieux** [comment]
When compositing a document where all lengths are in "%" and which does not specified a PAR, DAR or SAR, against a related video object with DAR=16:9 but a SAR=4:3:

- the root container PAR is computed to "1" (default)
- the root container SAR is computed to "4:3" (related video object)
- the root container DAR is therefore computed to be "4:3"

I would think the default display aspect ratio should be that of the related video object, i.e. the aspect ratio against which the timed text is authored, regardless of the storage aspect ratio that the related video object might use.

**Comment by skynavga** [comment]
On Fri, Jan 6, 2017 at 12:12 PM, Pierre-Anthony Lemieux <
notifications@github.com> wrote:

> When compositing a document where all lengths are in "%" and which does
> not specified a PAR, DAR or SAR, against a related video object with
> DAR=16:9 but a SAR=4:3:
>
>    - the root container PAR is computed to "1" (default)
>    - the root container SAR is computed to "4:3" (related video object)
>    - the root container DAR is therefore computed to be "4:3"
>
> I would think the default display aspect ratio should be that of the
> related video object, i.e. the aspect ratio against which the timed text is
> authored, regardless of the storage aspect ratio that the related video
> object might use.
>
Sounds like a friendly amendment. I'll make that change.

**Comment by palemieux** [comment]
What is the "resolved resolution of the root container region"?

**Comment by skynavga** [comment]
On Fri, Jan 6, 2017 at 12:28 PM, Pierre-Anthony Lemieux <
notifications@github.com> wrote:

> What is the "resolved resolution of the root container region"?
>
For this case (no tts:extent), the language I wrote into the WD [1] is:

If the value of the tts:extent
> <https://www.w3.org/TR/ttml2/#style-attribute-extent> attribute is
> specified on the tt
> <https://www.w3.org/TR/ttml2/#document-structure-vocabulary-tt> element
> and consists of two pixel-valued <length>
> <https://www.w3.org/TR/ttml2/#style-value-length> expressions, then these
> two expressions denote the width
> <https://www.w3.org/TR/ttml2/#terms-width> and height
> <https://www.w3.org/TR/ttml2/#terms-height> of the root container region,
> and, consequently, determine its resolution. Otherwise, if a related
> media object <https://www.w3.org/TR/ttml2/#terms-related-media-object> exists,
> then the resolution of the root container region is the resolution of the related
> media object <https://www.w3.org/TR/ttml2/#terms-related-media-object>,
> or, if no related media object
> <https://www.w3.org/TR/ttml2/#terms-related-media-object> exists, then
> the resolution of the root container region is determined by the document
> processing context
> <https://www.w3.org/TR/ttml2/#terms-document-processing-context>.


[1] https://www.w3.org/TR/ttml2/#root-container-region-semantics-resolution

**Comment by palemieux** [comment]
> is the resolution of the related media object <https://www.w3.org/TR/ttml2/#terms-related-media-object>

Stored resolution or displayed resolution?

I think something like tts:fontSize="18px" can only be undefined unless tts:extent is specified (or provided by an external context).

**Comment by skynavga** [comment]
Let's discuss this at the F2F.

**Comment by skynavga** [comment]
Address any outstanding comments under the following, which are hereby incorporated into this issue:

 - [ ] #27 interpreting pixel measure
 - [ ] #162 need parameter to express storage aspect ratio

**Comment by skynavga** [comment]
Closing with merge from #321.
