### ISSUE TITLE
The value tts:extent="contain" is not defined when applied to <tt>.

### ISSUE THREAD

**Issue by palemieux** [w3c/ttml2#329]
Section 10.2.16 specifies: _if the property applies to the tt element, then `contain` is interpreted as specified in H Root Container Region Semantics_

H Root Container Region Semantics does not however defined the semantics of `contain`

**Comment by skynavga** [comment]
@palemieux step (2) under H.1 __storage aspect ratio__ sub-heading says

>otherwise (the computed value is contain), the storage aspect ratio is considered to be unspecified and is inferred using other information described below

so, it is defined

**Comment by palemieux** [comment]
Agree with proposed "Works for Me" disposition
