### ISSUE TITLE
Deprecate use of pixel units unless tts:extent on root element is in pixels.

### ISSUE THREAD

**Issue by skynavga** [w3c/ttml2#330]
At present, TTML1 allows a document to use pixel units when expressing ``<length>`` terms, even when the author has not defined the resolution of the document coordinate space by specifying a pixel based ``tts:extent`` on the ``<tt>`` element. I propose that this behavior be deprecated in TTML2, as it leads to potential interoperability problems when presenting TTML content. Note that a number of profiles, including IMSC1 and EBU-TT, require that a pixel based ``tts:extent`` be present when pixel units are used in content.

**Comment by palemieux** [comment]
`ttp:pixelAspectRatio` should be similarly deprecated when `tts:extent` is not specified in `px` on `tt`

**Comment by skynavga** [comment]
OMG, we are in agreement!
