### ISSUE TITLE
Revert deprecation of ttp:profile on root element.

### ISSUE THREAD

**Issue by skynavga** [w3c/ttml2#331]
Upon further consideration, I believe my earlier suggestions to deprecate ``ttp:profile`` (in favor of ``ttp:processorProfiles``), which suggestion as already been implemented, may have been premature. I recommend the group consider restoring the use of ``ttp:profile`` which can serve as a shorthand for ``ttp:processorProfiles`` in the common case that only one processor profile applies.

**Comment by mikedo** [comment]
I support this.

**Comment by nigelmegitt** [comment]
It is unclear to me that only one processor profile applying is in fact the common case; I rather think it is the other way around, that it is the unusual case.

Can we modify ttp:profile to allow a short code profile as per the registry, including combinatorial operators, and get the best of both worlds?

**Comment by mikedo** [comment]
What would be the purpose of extending ttp:profile beyond TTML1 syntax AND defining a new TTML2 ttp:processorProfile? The entire purpose of keeping the former is for backwards compatibility to TTML1 document syntax.  If indeed both TTML1 syntax and TTML2 syntax for processor profiles can be disambiguated in such a new TTML2 ttp:profile, then we should remove ttp:processorProfiles from TTML2. I assumed that was not possible. If so, then extending two separate attributes to do the exact same thing would be odd and confusing.

**Comment by skynavga** [comment]
On Thu, May 25, 2017 at 10:28 AM, Michael A Dolan <notifications@github.com>
wrote:

> What would be the purpose of extending ttp:profile beyond TTML1 syntax AND
> defining a new TTML2 ttp:processorProfile? The entire purpose of keeping
> the former is for backwards compatibility to TTML1 document syntax. If
> indeed both TTML1 syntax and TTML2 syntax for processor profiles can be
> disambiguated in such a new TTML2 ttp:profile, then we should remove
> ttp:processorProfiles from TTML2. I assumed that was not possible. If so,
> then extending two separate attributes to do the exact same thing would be
> odd and confusing.
>
I made exactly this same point on today's call. I agree it would be
confusing and a generally bad idea to extend ttp:profile in this manner.
And further, any such extension would be orthogonal to considering whether
to revert the deprecation.

**Comment by nigelmegitt** [comment]
OK, I'm persuaded! Let's not try to change the syntax of the `ttp:profile` attribute. I don't mind having it for backward compatibility as long as there is a precedence rule for TTML2 processors if processorProfiles is also defined.

**Comment by skynavga** [comment]
Addressed reviewer comments and closing.
