### ISSUE TITLE
Add example fragments and images.

### ISSUE THREAD

**Issue by skynavga** [w3c/ttml2#359]
- ~~ttp:profile (as root element)~~
- [x] tts:backgroundClip
- [x] tts:backgroundExtent
- [x] tts:backgroundImage
- [x] tts:backgroundOrigin
- [x] tts:backgroundPosition
- [x] tts:backgroundRepeat
- [x] tts:fontKerning
- [x] tts:fontVariant
- [x] tts:letterSpacing
- [x] tts:opacity (on content elements)
- [x] tts:position
- [x] tts:textOrientation
- ~~tt:animate~~
- ~~tt:set~~
- ~~isd:isdSequence, isd:isd~~
- ~~tts:position with absolute units~~

Moving some items forward to 2e (see strikethrough above and #1001), as examples are not essential at this time.

**Comment by dae-kim** [comment]
@skynavga I'll take:

tts:backgroundClip
tts:backgroundExtent
tts:backgroundImage
tts:backgroundOrigin
tts:backgroundPosition
tts:backgroundRepeat
tts:border
tts:fontKerning
tts:letterSpacing
tts:opacity
tts:position
tts:textOrientation

**Comment by skynavga** [comment]
Handing off to @cconcolato.

**Comment by cconcolato** [comment]
per #429 fillLineGap will be removed from the spec
per #238 ipd, bpd are marked at Risk
per https://github.com/w3c/imsc/issues/278, inlineAreaBreak will be removed from the spec

**Comment by cconcolato** [comment]
There is already a fragment for ttp:profile and no need for an image.

**Comment by skynavga** [comment]
All items completed that have not been moved to #1001, so closing this umbrella issue as tasks satisfied.
