### ISSUE TITLE
Require support for DFXP transformation and presentation profiles.

### ISSUE THREAD

**Issue by skynavga** [w3c/ttml2#364]
Add requirement to support DFXP transformation and presentation profiles for TTML1 backward compatibility.

Editorial note from 2014-07-31.

**Comment by skynavga** [comment]
Discussed by myself, @cconcolato and @palemieux, who agree to require support for DFXP profiles by TTML2 processor.

**Comment by nigelmegitt** [comment]
What does this mean, "require support for"? Do you mean that the DFXP profiles should continue to be listed in TTML2, or that some processor class is required to support DFXP as a subset of TTML2?

**Comment by cconcolato** [comment]
I'm trying to apply this resolution but I'm not sure that what change is actually needed:
* Section G.1 (https://w3c.github.io/ttml2/#profile-ttml2-full) already says: 
> This profile is a superset of the DFXP Full Profile.

* Section G.2 (https://w3c.github.io/ttml2/#profile-ttml2-presentation) also says:
> This profile is a superset of the DFXP Presentation Profile: it requires support for the #processorProfiles and #version features.

* and Section G.3 (https://w3c.github.io/ttml2/#profile-ttml2-transformation) too:
> This profile is a superset of the DFXP Transformation Profile: it requires support for the #processorProfiles and #version features.

I would simply remove the parts after the ':' as there are (or will be) more than those 2 feature designators added in TTML2 compared to TTML1.

**Comment by skynavga** [comment]
Nope. Allow me a try.

**Comment by nigelmegitt** [comment]
@cconcolato That was the point I made at the f2f, and the response was that the dfxp profile URI needed to be mentioned explicitly as needing support. Does that help?
