### ISSUE TITLE
Enhance font selection semantics.

### ISSUE THREAD

**Issue by skynavga** [w3c/ttml2#371]
Define ``tts:fontSelectionStrategy`` style property based on                                                                                 
the XSL 1.1 font-selection-strategy property and [TTWG ML thread](http://lists.w3.org/Archives/Public/public-tt/2014Nov/0051.html).

Specify font selection semantics, including how multiple author defined font resources combine                 
with (local) platform defined font resources to obtain an ordered list of font resources for performing character to glyph mapping.

Editorial note from 2014-11-21.

**Comment by nigelmegitt** [comment]
In line with #406 and the general feedback to use CSS as the basis of semantics where possible I propose using CSS Fonts Level 3 https://www.w3.org/TR/css-fonts-3/ as the basis for this semantic if at all possible. For example see §5.3 Cluster Matching in that document.

CSS Fonts Level 3 is part of the CSS 2017 Snapshot.

**Comment by skynavga** [comment]
Changing this to editorial, as we had already included ``tts:fontSelectionStrategy`` for some time now, including a feature #fontSelectionStrategy.

**Comment by nigelmegitt** [comment]
@skynavga the current ED and the published WD each have an empty placeholder sections for the tts:fontSelectionStrategy style attribute, empty except for an issue note, so this issue by definition cannot be resolved without the creation of normative text. I cannot see how that is editorial and not substantive. Certainly by Process rules it must be substantive.

**Comment by skynavga** [comment]
@nigelmegitt I don't have such a black and white view as you express here. For me it depends on the context and nature of the change. There is plenty of gray area to consider. However, as it turns out, the PR makes schema changes, which is a sufficient criteria in my mind to warrant a substantive label. If it hadn't, I would have argued for editorial, but that is neither here nor there at this juncture.

**Comment by nigelmegitt** [comment]
I will propose in our call later today that we defer this issue to ttml.next on the grounds that the feature is complex, so a full review cycle is needed, and that we have scant input suggesting that the feature is needed. Leaving the behaviour as implementation defined seems adequate at the moment, given our strongly expressed desire to move ahead to CR.

The practical implication of deferring would be that we will need a pull request to remove `tts:fontSelectionStrategy` from TTML2.
