### ISSUE TITLE
Merge informative media timing material into Appendix I.

### ISSUE THREAD

**Issue by skynavga** [w3c/ttml2#378]
Generalize and rename Appendix I *Time Expression Semantics* to Root Container Region Semantics. Merge informative material from 12.4.1 *Media Timing* into Appendix I, updating this material as needed.

Editorial note from 2016-03-13.

**Comment by nigelmegitt** [comment]
I would prefer to move the appendix into section 12 rather than the other way around, since it is both normative and useful.

**Comment by nigelmegitt** [comment]
I think this move has been accepted in principle in TTML1, and now just needs to be implemented here. It's editorial only.

**Comment by nigelmegitt** [comment]
Pull request #616 moves the media timing informative section to the appendix, but does not generalise or rename appendix I as proposed in this issue.
