### ISSUE TITLE
The values for alpha in rgba() don't correspond to CSS3 Color definitions.

### ISSUE THREAD

**Issue by plehegar** [w3c/ttml2#38]
As presently defined, we allow the alpha value in an rgba() tuple to take a value from 0 to 255, rather than 0.0 to 1.0 (or 0% to 100%) as defined in CSS3 Color. On the other hand, we do use the CSS3 Color alpha values of 0.0 to 1.0 for opacity. This creates a bit of an anomaly if we should want to define tts:color in terms of CSS3 Color's definition of 'color'.

I'm presently marking this for TTML1.0, if we want to address in TTML10SE. Otherwise, we should push out to TTML.next.

(raised by Glenn Adams on 2013-05-15)
From tracker issue http://www.w3.org/AudioVideo/TT/tracker/issues/210

**Comment by nigelmegitt** [comment]
0-255 range alpha values are now in use for TTML1 and libraries that convert to CSS seem to be able to map them to 0.0-1.0 range without difficulty. Can we close this?

**Comment by skynavga** [comment]
+1 to close

**Comment by nigelmegitt** [comment]
[Meeting 2016-12-22] Agreed to close.
