### ISSUE TITLE
Update vocabulary derivation tables in Appendix N.

### ISSUE THREAD

**Issue by skynavga** [w3c/ttml2#380]
Add or update element and attribute vocabulary derivation information.

Editorial note from 2015-01-14.

**Comment by skynavga** [comment]
Note that attributes have been updated via #470; however, elements still need to be updated.

**Comment by nigelmegitt** [comment]
I didn't think there were any element derivations that needed updating - what is the task here?

**Comment by nigelmegitt** [comment]
@skynavga I've begun work on this, in the branch [`issue-0380-element-vocabulary-derivation` ](https://github.com/w3c/ttml2/tree/issue-0380-element-vocabulary-derivation) (commit 9e6a8c8), adding rows for the newly introduced elements. I'm not at all sure how to populate those rows however, other than for `audio` and `source`, which I have made a start on. Do you want to pick it up from here? Failing that, if you can point me at the sources for the elements:

* `tt:chunk`
* `tt:data`
* `tt:font`
* `tt:image`
* `ttm:item`
* `resources`

then I can try to complete this. Happy for @cconcolato to take a look too, of course.
