### ISSUE TITLE
Add CT708 mapping information.

### ISSUE THREAD

**Issue by skynavga** [w3c/ttml2#381]
Either fill in CT708 mapping information in Appendix T or remove this appendix.

Editorial note from 2014-03-06.

**Comment by mikedo** [comment]
[Appendix R at this writing] It should probably just defer informatively to SMPTE RP2052-11 "SMPTE Recommended Practice - Conversion from CEA-708 Caption Data to SMPTE-TT" at http://ieeexplore.ieee.org/document/7290363
and 
"SMPTE 24TB Technical Report Internet Caption Technical Requirements for SMPTE Timed Text" at https://www.smpte.org/sites/default/files/24TB-FCC-Technical-Requirements-20120908.pdf 
These were for TTML1, but still apply except for omitting the new tts:textShadow. A sentence could be added for that.

**Comment by nigelmegitt** [comment]
Looks like Appendix T to me in the ED at https://w3c.github.io/ttml2/spec/ttml2.html#cea708-mapping. I would support removing this and publishing any such mapping as a WG Note if someone works on it. The section is intended to be non-normative anyway so there would be no difference in status.
