### ISSUE TITLE
Appendix R (streaming) does not represent current practice.

### ISSUE THREAD

**Issue by mikedo** [w3c/ttml2#384]
Streaming TTML today consists of short complete TTML documents, not document fragments.  If we want an Appendix like this it should better document how, e.g. FFMPEG, actually works today, not just a theoretical fragmenting mechanism as its example.

And, if we for some reason want to keep this fragmentation example, then the definition of the properties of a progressively decodable document are over constrained, including:

1. the constraint: "does not require dereferencing (and subsequent loading) of any resources other than TTML Content (i.e., no embedded URIs);" is overly constraining and does not consider bundled resources such as the ISO BMFF sample packaging of URI image resources defined in ISO 14496-30.

2. it is not clear why this constraint is necessary: "does not support alternative content forms (e.g., different language, graphics formats, time bases) in a single document;", e.g. what about this example model makes it unable to easily handle alternative content, e.g. tts:altText?

And, overall, why is this definition of "progressively decodable" at odds with IMSC1 6.7.2?

**Comment by nigelmegitt** [comment]
See also w3c/ttml1#208 which is closely related/equivalent.

I have been involved in conversations about this appendix before in which people have certainly been confused about the best approach, and I would say even misled by TTML1 Appendix L. So I very much support modifying this (actually it has been on my mind to make a pull request to address it for a while).

Another data point is EBU-TT Live, [Tech3370](https://tech.ebu.ch/publications/tech3370), which defines a wrapper-free streaming model for the EBU-TT Live profile of TTML. That was designed to be sufficiently general to be applicable to other profiles of TTML also.

I would remove all mention of "progressively decodable", by the way.

**Comment by skynavga** [comment]
Notwithstanding your comments, the approach outlined in TTML1 Appendix L remains a viable option, just not one that has been pursued by industry. I don't mind adding information about the approaches adopted by industry, but I wouldn't want to remove the description of the progressively decodable option. Note that this sort of progressive delivery of XML is implemented in MPEG-7 and other contexts that use the BiM encoding of XML [1].

[1] http://mpeg.chiariglione.org/standards/mpeg-b/binary-mpeg-format-xml

**Comment by mikedo** [comment]
I did not say it was not viable.  Lots of random things are viable.  Given the TTML-based deployments today, this Appendix, as crafted, is at best misleading. If it is not modified to include and emphasize current best practice, it should be deleted. I look forward to Nigel's pull request.

**Comment by skynavga** [comment]
If someone can craft new language to add, then I'll add it; otherwise, this will have to wait a while.
