### ISSUE TITLE
[Jun 5 ED 10.2.14] example has extent on style rather than region

### ISSUE THREAD

**Issue by mikedo** [w3c/ttml2#388]

**Comment by skynavga** [comment]
This is permitted, i.e., regions can use either a child ``<style>`` element (as is the case in this example) as well as a ``@style`` to reference ``<style>`` elements specified as children of a preceding ``<styling>`` element. Where and how a style is specified is unrelated to whether the style applies to an element.

**Comment by mikedo** [comment]
Well, TTXV flagged it as an error, so I believed it :-)

**Comment by skynavga** [comment]
are you validating against the ttml2 model or imsc1 model? send me the
input test and output log and I'll take a look; it is possible there is an
issue with TTV

**Comment by mikedo** [comment]
IMSC1 (it is also example 8.2.5 in TTML1). Details sent via email.
