### ISSUE TITLE
Support text placement in 3D coordinate spaces (not zIndex compositing)

### ISSUE THREAD

**Issue by plehegar** [w3c/ttml2#40]
[The following is extracted from the liaison received from SMPTE at https://lists.w3.org/Archives/Member/w3c-archive/2012Sep/0214.html]

See Sections 6.1.2, 6.3.6 and 6.3.7 at ST 428-7.

A zValue style parameter shall be applicable to individual <p> elements for the purpose of defining the rendering of the element in terms of left- and right-eye stereoscopic images. 

zValue shall be the horizontal distance between the origin of the element as rendered in the left eye and right eye images. Half of the zValue shall correspond to the horizontal distance between the origin of the element as rendered in either the left or right images, and the origin of the element in the absence of a zValue. Positive (negative) zValue values shall move the element away from (closer to) the viewer.

zValue shall be a signed decimal number and shall be expressed as a percentage of the width of the root container region.

The vertical position of the element shall be unchanged by the application of zValue, and shall be identical in both left- and right-eye images.

zValue shall apply to the entire content of the <p> element.

The zValue style parameter shall be animatable, without interpolation. In order to avoid markup duplication, it shall be possible to define a given sequence of <set  tts:zValue="..."> elements once and apply it to multiple <p> elements.

(raised by Pierre-Anthony Lemieux on 2013-05-30)
From tracker issue http://www.w3.org/AudioVideo/TT/tracker/issues/224

**Comment by nigelmegitt** [comment]
[Meeting 2016-06-30] Want to close the tracker equivalent issue, but note that some preparatory work was done in Mercurial:

> Proposal in branch issue-224 at https://dvcs.w3.org/hg/ttml/rev/19905fe73a06

Otherwise, the `disparity` attribute is in the current TTML2 draft and can be reviewed.

**Comment by skynavga** [comment]
Closing this as tts:disparity has been added to TTML2 to address this functionality.

**Comment by nigelmegitt** [comment]
Commit ref 31447e4
