### ISSUE TITLE
Feedback on HDR compositing

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/ttml2#400]
Filing on behalf of Lars Haglund of SVT, who asked me to send this on his behalf (I have slightly edited it to make it more applicable as an issue on this repo but kept the substantive comments untouched):

SVT has not been involved in any W3C-work regarding subtitles, but has looked at the HDR compositing section in TTML2 (i.e. W3C’s initial work on timed text markup which will be used for UHDTV Subtitles).
 
As you can see, W3C’s plans are to use the sRGB colour space and transfer function to transmit subtitles and then to transform them in device for display on the relevant screen. As such, the transform needs to be simple enough to use in a consumer devices graphics plane processor.
 
There are two example transforms, for PQ and HLG, given in the W3C document, but to me/SVT there are problems with the PQ-transform.
 
1) DVB, in TS 101 154, has chosen 10-bit Narrow Range (64-940), not Full Range (0-1023), for PQ-based transmissions, hence it is likely a problem that W3C describes its example transform based on Full Range (0-1023).

I.e. if a CE-manufacturer is following that recommendation, then a pre-scaling (a stretch) of the received video from 64-940 to 0-1023 would be needed that in any bit-depth limited processing would introduce quantisation-errors.

Perhaps instead: Keep the narrow range video as it is received; instead squeeze-scale the subtitles' full range values (0-255 in 8-bit) into narrow range values (16-235 in 8-bit, hence 64-940 in 10-bit) before compositing. Note: if compositing in ‘linear light’, then processing in very high bit-depth (ideally ‘float’) is needed to not loose nuance-steps.
 
2) As the subtitles range, in the W3C recommended formulas, seems to be mapped to potentially cover the complete PQ range – i.e. subtitles possible to be as crazy bright as 10 000 cd/m2 (why?) – then “tts:luminanceGain” is actually not about “gain”, but always about “attenuation”. I.e. why isn't this dynamic metadata called “tts:luminanceAttenuation”?
 
2.1) As subtitles/graphics in relation to ‘Constrained PQ’ video (constrained by upcoming ITU recommended production practises) most often will stay at the very same luminance levels as for SDR subtitles/graphics inside the 0-100 cd/m2 portion of the extreme 0-10 000 cd/m2 range: the W3C recommendation regarding “tts:luminanceGain” may give too coarse level-steps for each metadata-value (creatively/authoring-wise), when always attenuating from the extreme 10 000 cd/m2 and by that initial step losing a lot of the available metadata values?

Perhaps instead: If the metadata values are too few, map the subtitles narrow range into a moderate realistic portion of PQ's complete range as a default bundled with a default attenuation?
(Example without knowing how “tts:luminanceGain” is defined or works, here exemplified as percentage: An example default mapping into a maximum 0-3200 cd/m2 portion bundled with a “tts:luminanceGain” at 3.125% gives a default compositing into the legacy 0-100 cd/m2 portion and a possibility to reach a subtitle luminance 5 stops brighter when needed for readability, because of bright video background area, by releasing the attenuation up to 100%, in this example, corresponding to 3200 cd/m2).

**Comment by nigelmegitt** [comment]
Since this wide review comment is about the PQ appendix, which was mainly contributed by @palemieux , reassigning to him for comments.

**Comment by palemieux** [comment]
> then “tts:luminanceGain” is actually not about “gain”, but always about “attenuation”.

This is not accurate. As specified at https://www.w3.org/TR/ttml2/#style-attribute-luminanceGain, the linear optical output values `(Cr, Cg, Cb)` of the components of a pixel of a region are defined as `80 ∙ tts:luminanceGain ∙ (r, g, b)`, and thus `tts:luminanceGain` is a gain. For example, the peak linear output is only 80 nits (and not 10,000 nits) if `tts:luminanceGain` is equal to 1, and `tts:luminanceGain` would need to be equal to 125 for the peak linear output to reach 10,000 nits.

**Comment by palemieux** [comment]
> hence it is likely a problem that W3C describes its example transform based on Full Range (0-1023).

Appendix Q.1 is just an example, which is targeted to full-scale computer graphics.

Other examples are possible.

**Comment by palemieux** [comment]
> the W3C recommendation regarding “tts:luminanceGain” may give too coarse level-steps for each metadata-value (creatively/authoring-wise), when always attenuating from the extreme 10 000 cd/m2 

As indicated at https://github.com/w3c/ttml2/issues/400#issuecomment-355483488, `tts:luminanceGain=1` in fact yields 80 nits, which means that `tts:luminanceGain` will likely be around unity in practice. For instance, in existing Blu Ray practice, `tts:luminanceGain` would be around 3-4.

**Comment by nigelmegitt** [comment]
@palemieux to draft a response

**Comment by palemieux** [comment]
I do not think this can be closed because the commenter has not been informed... or has he?

**Comment by nigelmegitt** [comment]
@palemieux Indeed he has not - it looks like you volunteered to draft the response.

**Comment by palemieux** [comment]
Dear Lars,

Thank you for your feedback on [IMSC 1.1 FPWD](https://www.w3.org/TR/2017/WD-ttml-imsc1.1-20171017/). 

Regarding your comment that _`tts:luminanceGain` is actually not about "gain", but always about "attenuation"_, the TTWG notes that, as specified at https://www.w3.org/TR/ttml2/#style-attribute-luminanceGain, the linear optical output values `(Cr, Cg, Cb)` of the components of a pixel are defined as `80 ∙ tts:luminanceGain ∙ (r, g, b)`, and thus `tts:luminanceGain` is a gain. For example, the peak linear output is only 80 nits if `tts:luminanceGain` is equal to 1, and `tts:luminanceGain` would need to be equal to 125 for the peak linear output to reach 10,000 nits. As result, TTWG does not believe that `tts:luminanceGain` would be better described as an attenuation.

Regarding your comment that _it is likely a problem that W3C describes its example transform based on Full Range (0-1023)_, the TTWG notes that Appendix Q.1 is just one example, which is targeted to full-scale computer graphics common on the web. TTWG does not believe additional examples are necessary, but would consider additional examples if contributed to TTWG.

Regarding your comment that _`tts:luminanceGain` may give too coarse level-steps for each metadata-value (creatively/authoring-wise), when always attenuating from the extreme 10 000 cd/m^2_, TTWG notes that, as described above, `tts:luminanceGain=1` in fact yields 80 nits (and not 10,000 nits), which means that `tts:luminanceGain` will likely be around unity in practice. For instance, in existing Blu Ray practice, `tts:luminanceGain` would be around 3-4.

Regards,

/s/

**Comment by nigelmegitt** [comment]
Thank you @palemieux , that looks good to me. Let's confirm on Thursday's call, if there have been no other views in the intervening period.

**Comment by nigelmegitt** [comment]
Feedback sent on 13th February, archived at https://lists.w3.org/Archives/Member/member-tt/2018Feb/0001.html (members only).
