### ISSUE TITLE
Security and privacy re external resources

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/ttml2#403]
Privacy IG feedback: add text in similar to the IMSC 1.0.1 section on security and privacy relating to external image fetching. Warn/inform that an implementation that does just-in-time loading of external images, say, may give information about media consumption progress to the origin.

**Comment by nigelmegitt** [comment]
I need to feed back the changes to the PING before we can close this.

**Comment by skynavga** [comment]
@nigelmegitt have you sent feedback? can we close?

**Comment by nigelmegitt** [comment]
No.

**Comment by nigelmegitt** [comment]
Reminder to me: I really need to send this feedback.

**Comment by nigelmegitt** [comment]
Feedback sent, archived at: https://lists.w3.org/Archives/Public/public-privacy/2018JanMar/0022.html 

Propose to label this as commenter-no-response and close this issue if there's no response in 2 weeks, otherwise to take action depending on the response.
