### ISSUE TITLE
Add equivalent CSS properties to style attributes

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/ttml2#406]
CSS WG and TAG review feedback: semantics defined only in terms of XSL-FO should be replaced with CSS semantics where possible; if similar but different semantics are available in CSS properties mention them at least informatively.

Use the most recent CSS Snapshot as the source of usable CSS property definitions. This is currently https://www.w3.org/TR/css-2017/

**Comment by skynavga** [comment]
This is not an actionable issue without specific suggested changes. I suggest closing this with no action, other than perhaps a "we will take under advisement" message to TAG.

**Comment by skynavga** [comment]
Please do not create any more issues requesting that we change references from XSL to CSS. We do not have agreement on such an action, and I will actively oppose it.

**Comment by nigelmegitt** [comment]
On the contrary, we have received very clear feedback from both WG members, TAG and CSS WG that this is appropriate and would constitute an improvement. Further, we have discussed this and you were there in the meeting @skynavga and asked for this to be turned into concrete actions along these lines - I'm merely doing the action that you asked for (as an alternative to closing this issue with no change). Previously you said you could accept it if someone else did the work. Well here I am doing the work and you're not accepting it - I am baffled.

**Comment by skynavga** [comment]
We did not fully discuss or agree on specific actions, and if you had suggested this wholesale replacement of references when it came up I would have certainly not agreed. The only possible actions that I see as reasonable are:

* add informative text that points to similar CSS functionality as a strategy for implementers that wish to map to CSS; however, where/how to do this is still open in my mind, as I did state (on the call) that this would create additional spec clutter, and that doing this in an appendix might be better;

* when there are particular technical issues regarding CSS functional mapping, then those would probably warrant a note, either inline in the relevant section or in an appendix like the above;

**Comment by nigelmegitt** [comment]
I think the words used before were "at least informatively", and since all the semantic references are in Notes in the spec, it seemed quite reasonable for me to to bring them up to date by replacement. However I would not object to keeping the old XSL references and saying "originally based on XSL 1.1 m.n, now equivalently based on CSS xyz" or some other wording to get us over any objections.

However I am certainly not going to allow these issues to remain closed given that they are the granular actions resulting from the HR and WR feedback on TTML2. I don't mind changing the wording in the issues to reflect a slightly different cause of action if we can agree one.

It would be much more useful right now to focus on the detail of any mapping I'm proposing that is in fact semantically not equivalent, if I've made any errors there.

**Comment by skynavga** [comment]
I would not agree to a statement of "equivalence" absent some proof of such
assertion. If we do something like this, I would like to see it collected
in an appendix, and not inline. But I do not want to see an issue opened
for every property you think needs to be treated.

**Comment by nigelmegitt** [comment]
Well it is too late regarding the granular issues - and anyway they're all referenced back to this umbrella issue.

The proof of the assertion, where it's complex, is based in implementation - I've used imscjs as the basis for the flex layout for example, which deals with displayAlign. Where it's simple I assert the equivalence based on the XSL 1.1 text that also asserts it.

**Comment by nigelmegitt** [comment]
Further style attributes that need some consideration but that I haven't opened issues for yet:

#### textDecoration

This is slightly complicated because XSL 1.1 adds differences relative to the CSS version that it references - it could be that those differences have now been absorbed into CSS, or something else has changed. Also XSL does not provide for this to be inherited, whereas TTML does.

#### visibility

This looks like a straight mapping to the CSS 2.1 visibility property. TTML defines the initial value anyhow, which is the only difference relative to CSS.

#### zIndex

This is a straight mapping to the CSS 2.1 z-index property with no special variance mentioned in XSL.

**Comment by skynavga** [comment]
@nigelmegitt and I have discussed and agreed on an approach we believe will address this issue and its sub-issues, namely, to create an informative appendix, with references from specific properties to this appendix, where the appendix collects both XSL-FO and CSS references together;

**Comment by nigelmegitt** [comment]
Currently missing an issue for `tts:wrapOption` mapping to CSS.

**Comment by cconcolato** [comment]
How is the mapping of fontShear done? The [wiki](https://www.w3.org/wiki/TimedText/CSSRequirements#fontShear) says there is no mapping, but apparently transform:skewY seems to achieve similar effect, is that correct?

**Comment by nigelmegitt** [comment]
Good spot @cconcolato, it certainly looks like it. It looks like the function depends on the inline progression dimension: if it corresponds to the X axis then `skewX()` would apply, but if in the Y axis then it would be `skewY()`. Note that in the 2017 CSS snapshot the CSS3-TRANSFORMS spec is shown as ["approved for wide release"](https://www.w3.org/TR/css-2017/#experimental) despite being in WD only, as an exception. 

This means that the CSS WG considers it as safe for wide release but that we cannot reference it normatively (W3C rules say the spec must be in CR for normative referencing).

Would you like to open an issue describing the mapping and reference this here issue in the description for tracking?

**Comment by skynavga** [comment]
Fixed in 924d6cd47f0e36daa5b13fef95c6aa9ac6b88d72.
