### ISSUE TITLE
Reference CSS justify-content semantic

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/ttml2#415]
Part of umbrella #406 

Current semantic based on: XSL 1.1 §7.14.4 https://www.w3.org/TR/2006/REC-xsl11-20061205/#display-align
Current CSS snapshot version of a similar semantic: CSS Flexible Box Layout Module Level 1 §8.2 https://www.w3.org/TR/css-flexbox-1/#justify-content-property

The XSL spec defines this semantic without reference to CSS. CSS has no simple mapping here, since this functionality depends on the layout used. Proposal is to use a flex layout for region, setting main axis to vertical top to bottom (`display: flex; flex-direction: column; position: absolute;`) and map displayAlign to the `justify-content` property, where:

| displayAlign value | justify-content value |
|-------------------|--------------------|
| before | flex-start |
| center | center |
| after | flex-end |
| justify | space-between |

Note: this approach has been shown to work by https://github.com/sandflow/imscJS

Action to take: add to XSL spec reference the proposed equivalent CSS snapshot spec reference as an alternative.

**Comment by skynavga** [comment]
No.

**Comment by palemieux** [comment]
>  justify-content rather than just using align-content?

Probably because "[align-content] applies tomulti-line flex containers" [2]

[2] https://developer.mozilla.org/en-US/docs/Web/CSS/align-content

**Comment by palemieux** [comment]
>  flex-direction: column

Maybe because "the main-start and main-end points are the same as
the before and after points of the writing-mode." [1]

[1] https://developer.mozilla.org/en-US/docs/Web/CSS/flex-direction

**Comment by skynavga** [comment]
Fixed in 924d6cd47f0e36daa5b13fef95c6aa9ac6b88d72.
