### ISSUE TITLE
Reference CSS font-weight semantic

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/ttml2#419]
Part of umbrella #406 

Current semantic based on: XSL 1.1 §7.9.9 https://www.w3.org/TR/2006/REC-xsl11-20061205/#font-weight
Current CSS snapshot version of this semantic: CSS 2.1 §15.6 https://www.w3.org/TR/2011/REC-CSS2-20110607/fonts.html#propdef-font-weight

The XSL spec references an earlier CSS spec to define the semantic.

Action to take: replace XSL spec reference with CSS snapshot spec reference.

**Comment by skynavga** [comment]
This is a frivolous and unnecessary change. I will not make it.

**Comment by skynavga** [comment]
Fixed in 924d6cd47f0e36daa5b13fef95c6aa9ac6b88d72.
