### ISSUE TITLE
Reference CSS line-height semantic

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/ttml2#420]
Part of umbrella #406 

Current semantic based on: XSL 1.1 §7.16.4 https://www.w3.org/TR/2006/REC-xsl11-20061205/#line-height
Current CSS snapshot version of this semantic: CSS 2.1 §10.8 https://www.w3.org/TR/2011/REC-CSS2-20110607/visudet.html#propdef-line-height

The XSL spec references an earlier CSS spec to define the semantic.

Action to take: replace XSL spec reference with CSS snapshot spec reference to clarify that not only is it the _intention_ to match the CSS line stacking strategy, but that is actually defined as the correct behaviour.

**Comment by skynavga** [comment]
No.

**Comment by skynavga** [comment]
Fixed in 924d6cd47f0e36daa5b13fef95c6aa9ac6b88d72.
