### ISSUE TITLE
Reference CSS padding semantic

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/ttml2#422]
Part of umbrella #406 

Current semantic based on: XSL 1.1 §7.31.15 https://www.w3.org/TR/2006/REC-xsl11-20061205/#padding with writing mode relative padding values

Current CSS snapshot version of this semantic: CSS 2.1 §8.4 https://www.w3.org/TR/2011/REC-CSS2-20110607/box.html#padding-properties

The XSL spec references an earlier CSS spec to define the semantic. CSS does not use writing mode and direction dependent edge specifications, so we need to state that the following equivalents exist as defined at https://www.w3.org/TR/css-writing-modes-3/#logical-directions:

|TTML/XSL edge descriptor|CSS flow-relative edge descriptor|
|---------------------------|-----------------------------|
|before| block-start |
|end| inline-end|
|after| block-end|
|start| inline-start|

Actions to take: 

* replace XSL spec reference with CSS snapshot spec reference.
* describe that the edges in the TTML padding property are abstract edge equivalents as in the table above.
* include text to state that the abstract to physical mappings in https://www.w3.org/TR/css-writing-modes-3/#logical-to-physical apply, so that calculating the equivalent to, say, `padding-top` depends on the writing mode and the direction that apply locally.

**Comment by skynavga** [comment]
No.

**Comment by skynavga** [comment]
Fixed in 924d6cd47f0e36daa5b13fef95c6aa9ac6b88d72.
