### ISSUE TITLE
Reference CSS text-align semantic

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/ttml2#423]
Part of umbrella #406 

Current semantic based on: XSL 1.1 §7.16.9 https://www.w3.org/TR/2006/REC-xsl11-20061205/#text-align
Current CSS snapshot version of this semantic: CSS 2.1 §16.2 https://www.w3.org/TR/2011/REC-CSS2-20110607/text.html#alignment-prop

The XSL spec references an earlier CSS spec to define the semantic. TTML also references XSL text-align-last, and requires it to be set to "relative". This has the same defined behaviour in CSS Text Module Level 3, and is presumably the normally implemented CSS behaviour.

Action to take: replace XSL spec reference with CSS snapshot spec reference.

**Comment by skynavga** [comment]
This is a frivolous and unnecessary change. I will not make it.

**Comment by skynavga** [comment]
Fixed in 924d6cd47f0e36daa5b13fef95c6aa9ac6b88d72.
