### ISSUE TITLE
Reference CSS z-index property

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/ttml2#425]
Part of umbrella #406 

Current semantic based on: XSL 1.1 §7.30.18 https://www.w3.org/TR/2006/REC-xsl11-20061205/#z-index
Current CSS snapshot version of this semantic: CSS 2.1 §9.9.1 https://www.w3.org/TR/2011/REC-CSS2-20110607/visuren.html#z-index

The XSL spec references the CSS spec to define the semantic, with no changes.

Action to take: Add CSS spec reference XSL spec reference

**Comment by skynavga** [comment]
Fixed in 924d6cd47f0e36daa5b13fef95c6aa9ac6b88d72.
