### ISSUE TITLE
Reference CSS text-decoration property

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/ttml2#426]
Part of umbrella #406 

Current semantic based on: XSL 1.1 §7.17.4 https://www.w3.org/TR/2006/REC-xsl11-20061205/#text-decoration
Current CSS snapshot version of this semantic: CSS 2.1 §16.3.1 https://www.w3.org/TR/2011/REC-CSS2-20110607/text.html#propdef-text-decoration

The XSL spec references the CSS spec to define the semantic, with changes to specify the position of underlines, especially based on language.

Action to take: Add CSS spec reference XSL spec reference and highlight the additional semantic in XSL for determining the position of underlines.

**Comment by skynavga** [comment]
Fixed in 924d6cd47f0e36daa5b13fef95c6aa9ac6b88d72.
