### ISSUE TITLE
Appendix on semantic basis of styles.

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/ttml2#427]
Part of umbrella issue #406.

First stage of editing for this issue:

* [x] Add appendix for containing the semantic bases
* [x] Include semantic bases for each style attribute already based on CSS
* [x] Add table row to style attributes in section §10 of TTML2 to point towards the informative semantic basis
* [x] Tidy up/remove/move the existing derivation section in appendix N.2.

**Comment by skynavga** [comment]
Fixed in 924d6cd47f0e36daa5b13fef95c6aa9ac6b88d72.
