### ISSUE TITLE
Definition of [external data resource] does not include src attribute on image element.

### ISSUE THREAD

**Issue by palemieux** [w3c/ttml2#436]
The definition of [external data resource] does not seem to allow for the possibility of a `src` attribute on an `image` element.
 
_A data resource external to a timed text content document instance, referenced by means of a source element or a src attribute of a source element or embedded content element._

**Comment by skynavga** [comment]
@palemieux the following text (you cite above) covers @src on {audio,data,font,image}, since these are embedded content elements

>a src attribute of a source element or embedded content element

**Comment by palemieux** [comment]
@skynavga Ok. I was tripped up by _[embedded content element]_, which implies that that the content is embedded in the document itself, which is not the case. What about  _[media content element]_?

**Comment by nigelmegitt** [comment]
RESOLUTION: We will not make a change here because we have insufficient willingness to find and implement a different name.

**Comment by palemieux** [comment]
Commenter agrees
