### ISSUE TITLE
Change summary not up to date.

### ISSUE THREAD

**Issue by tairt** [w3c/ttml2#437]
The added vocabulary between TTML1 and TTML2 is well documented. Other changes are documented in a [detailed changelog](https://w3c.github.io/ttml2/spec/ttml2-changes.html). This changelog has no date when it was last updated. It should either:
* have a date when it was last updated,
* link to the draft it refers to,

or 

* be completely integrated in the TTML 2 draft as appendix.

The last option may not be practical because it requires updating the changelog after every substantial edit (even if the document is just published as editors draft).

**Comment by nigelmegitt** [comment]
I propose:

* change the section 1.1 title "Changes from TTML1 (2nd Ed.) to TTML2 Working Draft (Latest Revision)" so that the "TTML2 Working Draft" part is a link to the dated version of the document to which it applied, and replace "(Latest Revision)" with "([date of revision])".

**Comment by tairt** [comment]
Did not review the change made yet and therefore re-open the issue.

**Comment by tairt** [comment]
#527 partly addresses this issue. A change that points to the editors draft needs also be made in Appendix U of TTML2. Also the link to the changes document ([https://w3c.github.io/ttml2/spec/ttml2-changes.html](https://w3c.github.io/ttml2/spec/ttml2-changes.html) and also the link from the TTML2 working draft to the TTML2 editors draft do not work.

**Comment by skynavga** [comment]
@nigelmegitt please update the build script to copy the ttml2-changes.html file to the same directory that contains the index.html file

**Comment by nigelmegitt** [comment]
@skynavga done in 0e1fc19 (whose commit message accidentally referred to the wrong issue).
