### ISSUE TITLE
Duplicated text for attributes in TT Style Namespace.

### ISSUE THREAD

**Issue by tairt** [w3c/ttml2#438]
The following text is repeated for all 55 attributes of the TT Style Namespace:

>This attribute may be specified by any element type that permits use of attributes in the TT Style Namespaces; however, this attribute applies as a style property only to those element types indicated in the following table.

This text should be just defined once in e.g. as below:

"Attribute from the TT Style Namespace may be specified by any element type that permits use of attributes in the TT Style Namespaces; however, attributes apply as a style property only to those element types indicated in the corresponding table for that attribute."

This should also be changed for attributes in the TT Audio Style Namespace.

**Comment by nigelmegitt** [comment]
I support this change, and note that there is existing text in §10.2 Styling Attribute Vocabulary:

> Unless explicitly permitted by an element type definition, an attribute in the TT Style Namespace should not be specified on an element unless it either applies to that element or denotes an inheritable style property. If it does not apply to that element and does not denote an inheritable style property, then it must be ignored for the purpose of non-validation processing. In the case of validation processing, such usage should be reported as a warning, or, if strict validation is performed, as an error.

It would make sense to precede this statement by the one that @tairt suggested.

**Comment by tairt** [comment]
From my side this issue is addressed and can be closed when #526 is merged.
