### ISSUE TITLE
Foreign namespace elements not reflected in syntax.

### ISSUE THREAD

**Issue by tairt** [w3c/ttml2#439]
### Section 5.3.2 

> In addition to standardized extension vocabulary, a conforming document instance may contain arbitrary namespace qualified elements that reside in any namespace other than those namespaces defined for use with this specification.

This option seems not reflected in the content model description of TTML elements.

**Comment by skynavga** [comment]
We have discussed this before [reference needed], and concluded that foreign elements are indeed supported and need not be explicitly marked in content models. The reason for this is that those content models apply only to Abstract Document Types after pruning vocabulary from foreign namespaces (see https://w3c.github.io/ttml2/spec/ttml2.html#doctypes).

**Comment by skynavga** [comment]
See also #358, specifically, https://github.com/w3c/ttml1/issues/196.

**Comment by tairt** [comment]
Thanks for the pointers to the other issue. You are right that this has been discussed before. I will go back and check our discussion before I respond.

**Comment by skynavga** [comment]
@tairt please comment further if action is necessary; otherwise, please close

**Comment by tairt** [comment]
I checked the links but I could not find a hint, that the allowance of foreign namespace elements need not to be reflected in the element content models. I can not see the difference why this is different from the allowance of foreign namespace attributes.

**Comment by skynavga** [comment]
Remove ``{any attribute not in default or any TT Namespace}`` should be removed on each element information item.

**Comment by skynavga** [comment]
Also update 14.1.1 element information item and add notes explaining that an implementation may or may not prune foreign vocabulary (but must do so for the purpose of validation processing).
