### ISSUE TITLE
Condition attribute missing in Core catalog.

### ISSUE THREAD

**Issue by tairt** [w3c/ttml2#440]
The attribute condition needs to be listed in Table 5 of section 5.3.1.

**Comment by skynavga** [comment]
Resolved in b8efe6bef44a30a848903fdea302062751feec2b.

**Comment by tairt** [comment]
Thanks, looks good!

**Comment by tmichel07** [comment]
Andreas,

As you seem to be satisfied with the WG resolution and spec update, so I labelled your issue as "agreed by comenter". 
Let me know if it is the case and I will close this issue.

**Comment by nigelmegitt** [comment]
@tairt ping?

**Comment by tairt** [comment]
Can we agree on the following procedure?

"If the commenter comments in an issue he opened that a PR has been resolved his issue (e.g. by saying "this looks good to me"), than this issue can be closed as soon the PR has been merged."

To request a second confirmation seems to add overhead without any benefits.

I will close this issue as my comment has been addressed.

**Comment by nigelmegitt** [comment]
@tairt I'm happy with that procedure as long as the issue is labelled appropriately and @tmichel07 is happy with this for recording purposes.
