### ISSUE TITLE
Clarify use of whitespace in style attribute values.

### ISSUE THREAD

**Issue by tairt** [w3c/ttml2#441]
To clarify the permitted use of whitespace in style attribute values, the following text in section 8.2 ...

> Unless explicitly stated otherwise, linear white-space (LWSP) must appear between adjacent non-terminal components of a value of a TT Style property value unless some other delimiter is permitted and used.

...should be extended with...

**If other delimiters are permitted LWSP may appear between these delimiters and non-terminal components of a value of a TT Style property.**

**Comment by palemieux** [comment]
@tairt The qualifier "If other delimiters are permitted" seems to apply only to the COMMA in the value `tts:fontFamily`... or are there other style values where it would apply?

**Comment by skynavga** [comment]
not in TTML1, but in TTML2, e.g., semicolon in <animation-value-list>, <key-splines>, <key-times>, etc.

**Comment by tairt** [comment]
@palemieux I think that the expression for rgb component values is a similar case:

```
<color>
  :
 ... 
| "rgb" "(" r-value "," g-value "," b-value ")"
| "rgba" "(" r-value "," g-value "," b-value "," a-value ")"
 ....  
```

**Comment by palemieux** [comment]
@tairt Thanks for clarifying your understanding. As indicated at https://github.com/w3c/ttml2/issues/315 , I object to adding support for LWSP in `<color>` and other style value expressions.

**Comment by tairt** [comment]
Ok, thanks for the point to #315. I could not remember in which issue we discussed this and back then it seems that I also had concerns in adding LWSP for `<color>`. Let me check. Possibly I will close this issue after review of #315.

**Comment by skynavga** [comment]
Please note that LWSP is permitted in rgb() and other function expressions in TTML2. However, for TTML1, I'm find with leaving LWSP out of rgb() and rgba().

**Comment by palemieux** [comment]
> Please note that LWSP is permitted in rgb() and other function expressions in TTML2. 

... in the current draft.

**Comment by tairt** [comment]
I failed to notice that there was already an issue open on the handling of LWSP in style values (#315) and I also did not take into account the comments in this issue. I therefore withdraw my Wide Review comment and close this issue.

**Comment by skynavga** [comment]
On Thu, Jan 4, 2018 at 12:30 PM, Pierre-Anthony Lemieux <
notifications@github.com> wrote:

> Please note that LWSP is permitted in rgb() and other function expressions
> in TTML2.
>
> ... in the current draft.
>
If by current draft you mean the current working draft (as opposed to ED),
then you are correct. The current WD, which has been accepted by the WG,
allows space around COMMA in rgb(), etc., by step (3) under the whitespace
rules in the prologue of 10.4 [1].

[1] https://www.w3.org/TR/ttml2/#styling-style-value-expressions
