### ISSUE TITLE
Make backward compatibility normative.

### ISSUE THREAD

**Issue by tairt** [w3c/ttml2#442]
Section 3.4.2 

> A conforming TTML1 content document instance is intended to be a conforming TTML2 content document instance.
A conforming TTML2 processor should be able to process a TTML1 content document instance; however, it may emit warnings if it encounters deprecated features.

Should be changed to

"A conforming TTML1 content document instance **is a** conforming TTML2 content document instance.

A conforming TTML2 processor **must** be able to process a TTML1 content document instance; however, a **validating processor** may emit warnings if it encounters deprecated features."

**Comment by nigelmegitt** [comment]
It does seem sensible to treat this as a duplicate of #458 and deal with both sets of comments in a single pull request. @tairt would that work for you?

**Comment by tairt** [comment]
This issue was opened as WR comment before #458, so it is actually the other way around. But I see that there has been a longer discussion in #458 so I am fine if this issue is resolved in a single pull request. This issue should stay open until it is resolved by that PR.

**Comment by tairt** [comment]
I uncheck the label duplicate after reading through #458. The comment in this issue requests normative language. Discussion and PR for #458 do not address this.

**Comment by skynavga** [comment]
I believe this issue has been addressed by #521. @tait please confirm.

**Comment by tairt** [comment]
Yes, this has been addressed by #521 and closing therefore this issue.
