### ISSUE TITLE
3GPP review of TTML2

### ISSUE THREAD

**Issue by tmichel07** [w3c/ttml2#447]
Comment sent by Paolo Usai privately and to 
https://lists.w3.org/Archives/Team/team-liaisons/2017Jul/0033.html
A second email was sent
https://lists.w3.org/Archives/Team/team-liaisons/2017Aug/0061.html
-----------------------------------
Please do NOT discuss this issue on github, this email is not public.

For your convenience I have forwarded the email to W3C member restricted space

https://lists.w3.org/Archives/Member/member-tt/2017Oct/0004.html
https://lists.w3.org/Archives/Member/member-tt/2017Oct/0002.html

**Comment by skynavga** [comment]
Having reviewed the indicated comments, there is no actionable issue indicated (either substantive or editorial), so I am closing with no action and marking as WR-resolved.

**Comment by dwsinger** [comment]
There's no actionable reply yet because 3GPP SA4 has not yet met. Perhaps it would be wise to wait and see if they have comments before closing?

**Comment by skynavga** [comment]
We need to discuss how much time we will permit for potential review input after the stated deadline (2017-09-30).

**Comment by nigelmegitt** [comment]
We failed to discuss this at the Burlingame TPAC face to face (sorry!), but we did discuss timelines for TTML2. I think in practice we are likely to consider comments received in roughly the next 2-4 weeks before @skynavga commences his next major editing round, and before the seasonal break.
