### ISSUE TITLE
 ITU-T Group 16 IPTV r review of TTML2

### ISSUE THREAD

**Issue by tmichel07** [w3c/ttml2#448]
Comment sent by TSB SG16 Secretariat, ITU <tsbsg16@itu.int>
Date: Wed, 12 Jul 2017 13:25:55 +0000
https://lists.w3.org/Archives/Team/team-liaisons/2017Jul/0032.html
______________________________________________
Please do NOT discuss this issue on github, this email is not public.

For your convenience I have forwarded the email to W3C member restricted space
https://lists.w3.org/Archives/Member/member-tt/2017Oct/0006.html

**Comment by skynavga** [comment]
Having reviewed the comments, there is no actionable issue indicated (either substantive or editorial), so I am closing with no action and marking as WR-resolved.

**Comment by skynavga** [comment]
We need to discuss how much time we will permit for potential review input after the stated deadline (2017-09-30).

**Comment by nigelmegitt** [comment]
We failed to discuss this at the Burlingame TPAC face to face (sorry!), but we did discuss timelines for TTML2. I think in practice we are likely to consider comments received in roughly the next 2-4 weeks before @skynavga commences his next major editing round, and before the seasonal break.
