### ISSUE TITLE
Missing ruby attributes from list of styling attributes

### ISSUE THREAD

**Issue by cconcolato** [w3c/ttml2#454]
In section 10.2 Styling Attribute Vocabulary, there is a long list of all styling attributes. It is missing:
10.2.39 tts:rubyOverflow
10.2.40 tts:rubyOverhang
10.2.41 tts:rubyOverhangClass

and the following are listed in the wrong order
10.2.21 tts:fontShear
10.2.20 tts:fontSelectionStrategy

**Comment by skynavga** [comment]
Resolved in 2eb7d54c3ad9c7aca373f701b6455419d43d65cb.

**Comment by tmichel07** [comment]
Cyril,

Can you approve the WG response to you issue and spec update, so we can mark this issue as "comenter agreed" and close it.
Thanks

**Comment by cconcolato** [comment]
Approved.

On Oct 5, 2017 09:47, "tmichel07" <notifications@github.com> wrote:

Cyril,

Can you approve the WG response to you issue and spec update, so we can
mark this issue as "comenter agreed" and close it.
Thanks

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/w3c/ttml2/issues/454#issuecomment-334524295>, or mute
the thread
