### ISSUE TITLE
Individual character rotation

### ISSUE THREAD

**Issue by plehegar** [w3c/ttml2#47]
[The following is extracted from the liaison received from SMPTE at https://lists.w3.org/Archives/Member/w3c-archive/2012Sep/0214.html]

See Section 6.11 at ST 428-7.
It shall be possible to specify that each rendered character within a <span> element be individually rotated right or left around its center by 90 degrees.
Note: This is most common for special characters in an Asian text string that is being displayed vertically.

(raised by Pierre-Anthony Lemieux on 2013-05-30)
From tracker issue http://www.w3.org/AudioVideo/TT/tracker/issues/231

**Comment by nigelmegitt** [comment]
It appears that this is handled by [`tts:textOrientation`](https://www.w3.org/TR/ttml2/#style-attribute-textOrientation) - can this issue now be closed?

**Comment by skynavga** [comment]
yes

**Comment by nigelmegitt** [comment]
[Meeting 2016-12-22] Agreed to close since textOrientation meets the requirement.

@skynavga notes that completely arbitrary rotation is not possible but the common use case as in the note is met, if it is only intended to handle character rotation in Asian text strings.
