### ISSUE TITLE
ttp:profile has been extended from TTML1, but no new feature has been defined

### ISSUE THREAD

**Issue by palemieux** [w3c/ttml2#473]
A feature that expresses support for the following attributes (not present in TTML1) is necessary:

- combine
- designator
- type

**Comment by skynavga** [comment]
This refers to the ``ttp:profile`` element, not the attribute.

**Comment by nigelmegitt** [comment]
Would it make sense to include `ttp:contentProfileCombination` and `ttp:processorProfileCombination` attributes here too?
