### ISSUE TITLE
Delimiters in URI references possibly ambiguous

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/ttml2#474]
The delimiter used to separate profile designators in `ttp:contentProfiles` and `ttp:processorProfiles` is `<lwsp>` which includes space characters, however according to the reference https://www.w3.org/TR/xmlschema-2/#anyURI the `xsd:anyURI` type can contain non-percent-encoded spaces in their lexical representation, albeit they are discouraged.

Therefore the delimiter as defined at present may result in false separation of URIs where it is not intended.

I would resolve this either by changing the delimiter, or preferably, by requiring percent encoding of the URIs which results in them no longer containing space characters.

**Comment by skynavga** [comment]
I'm not sure this [can include space characters] is true. I have certainly been operating under the presumption that it is not.

For example, the definition of xsd:anyURI you cite refers to https://www.w3.org/TR/2001/REC-xlink-20010627/#link-locators, which says:

>Some characters are disallowed in URI references, even if they are allowed in XML; the disallowed characters include all non-ASCII characters, plus the excluded characters listed in Section 2.4 of [IETF RFC 2396], except for the number sign (#) and percent sign (%) and the square bracket characters re-allowed in [IETF RFC 2732]. Disallowed characters must be escaped as ...

And http://www.ietf.org/rfc/rfc2396.txt says (2.4.3. Excluded US-ASCII Characters):

>The space character is excluded because significant spaces may disappear and insignificant spaces may be introduced when URI are transcribed or typeset or subjected to the treatment of word-processing programs.  Whitespace is also used to delimit URI in many contexts.

**Comment by nigelmegitt** [comment]
Thanks @skynavga I've double checked those links too and I agree that the note in https://www.w3.org/TR/xmlschema-2/#anyURI §3.2.17.1:
> Note:  Spaces are, in principle, allowed in the ·lexical space· of anyURI, however, their use is highly discouraged (unless they are encoded by %20).

is misleading here. I also see that the current RFC for URI, [rfc3986](https://tools.ietf.org/html/rfc3986), is not the one referenced by the (older) specs we normatively reference, although most users would expect any URI permitted in RFC3986 to be usable in this context also. That spec _does_ permit percent encoded space characters (look for the definition of `pchar`), but does not consider unescaped white space to be part of the URI. 

I would propose that we add an "avoidance of doubt" note along the lines:

> Note: for the avoidance of doubt URIs as defined by [RFC3986] can be used, and URIs must be percent encoded once before use in contexts that permit an `xsd:anyURI`.

Looking a bit more widely, `xsd:anyURI` is used many times throughout the spec, and each time is defined with text like:

> If specified, the value of this attribute must adhere to the following syntax where the designator adheres to the `xsd:anyURI` data type defined by [XML Schema Part 2], §3.2.17

so it is probably worth factoring this out into a generic definition of a `<uri>` syntax component and collecting the information about that component in a single place, modulo any additional constraints applied in specific cases (such as "and, further, must specify a profile designator in accordance with 5.2 Profiling." etc).
