### ISSUE TITLE
ittp:aspectRatio should be added to TTML2

### ISSUE THREAD

**Issue by palemieux** [w3c/ttml2#477]
`ittp:aspectRatio` is currently in use, by way of IMSC1, and should either:

1. be added to TTML2, and deprecated in favor of `ttp:displayAspectRatio`. 
2. be added to TTML2, where it would replace`ttp:displayAspectRatio`. 

Both options allow IMSC 1.1 to be a clean subset of TTML2. Option (1) introduces specification gymnastics in TTML2, i.e. two attributes with identical semantics. Option (2) simplifies upgrade of IMSC1 implementations to IMSC 1.1, but introduces an additional namespace in TTML2.

**Comment by skynavga** [comment]
I disagree (with the proposal). TTML2 should not incorporate non-TTML namespace vocabulary. Further, there is no requirement that TTML2 be a syntactic superset of industry profiles.

**Comment by skynavga** [comment]
I believe we agreed at today's F2F that we would not add ittp:aspectRatio to TTML2. Is this correct? If so, then the reporter close this?
