### ISSUE TITLE
 <ttm:item name='altText'> should be <ttm:altText> or <ittm:altText>

### ISSUE THREAD

**Issue by palemieux** [w3c/ttml2#479]
This allows a straightforward upgrade path from IMSC1, and follows pattern established by other metadata items such as actor, agent, copyright, etc...

**Comment by skynavga** [comment]
I disagree (with the proposal). TTML2 should not incorporate non-TTML namespace vocabulary. Further, there is no requirement that TTML2 be a syntactic superset of industry profiles. Finally, we agreed in the past to not add new named metadata items as independent vocabulary, and, instead, to use the more extensible ``ttm:item`` mechanism.

**Comment by skynavga** [comment]
I believe we agreed at today's F2F that we would not add ``ittm:altText`` to TTML2. However, we will add ``@ttm:alt`` as a metadata attribute item that is semantically equivalent to the already defined ``<ttm:item name='alt'>...</ttm:item>. Is this correct? Can we close this an open a new issue to add ttm:alt?
