### ISSUE TITLE
Add ebutts:linePadding vocabulary to TTML2

### ISSUE THREAD

**Issue by palemieux** [w3c/ttml2#480]
`ebutts:linePadding` as specified in EBU-TT-D and referenced by IMSC 1.0.1 has been adopted by the industry.

TTML2 provides similar capabilities by adding support for padding on span (see https://www.w3.org/TR/ttml2/#style-attribute-padding). This approach however has a number of drawbacks:

- it uses a syntax that is significantly different than that of `ebutts:linePadding`, complicating the life of users and implementers alike, without improved CSS support (since CSS does not support the proposed TTML2 syntax)
- it is significantly more complex to implement than `ebutts:linePadding` (since each span can have a different value) without having demonstrated why such complexity is needed for subtitles/captions (or timed text in general)

The `ebutts:linePadding` vocabulary and syntax should be added to TTML2.

**Comment by skynavga** [comment]
I believe we agreed at today's F2F that we would not add ebutts:linePadding to TTML2. Is this correct? If so, then could the reporter close this?
