### ISSUE TITLE
Remove annotation-position "auto" used with ruby position and text emphasis.

### ISSUE THREAD

**Issue by palemieux** [w3c/ttml2#481]
According to https://lists.w3.org/Archives/Public/public-tt/2017Nov/0007.html , `rubyPosition="auto"` should take same behavior as `'outside'`.

**Comment by nigelmegitt** [comment]
@cconcolato is this your position also, that we should change the auto behaviour?

**Comment by cconcolato** [comment]
As indicated in our white paper:
> the behavior of 'auto' is only specified for exactly two-line events, which will not cover the use case of unanticipated wrapping of a two-line event. We believe that that the current behavior described for 'outside' is the correct model, and that 'auto' should have the same behavior as 'outside'.

**Comment by skynavga** [comment]
Note that the same logic that asks for this change applies to the ``<emphasis-position>`` component of ``tts:textEmphasis``.

**Comment by palemieux** [comment]
@cconcolato Do you concur with https://github.com/w3c/ttml2/issues/481#issuecomment-354365360?

**Comment by palemieux** [comment]
@skynavga The white paper mentioned at https://github.com/w3c/ttml2/issues/481#issue-271362209 only recommends defaults for `tts:rubyPosition`, and this issue was opened specifically to tackle the latter. I have no objection to also correcting the initial value for text emphasis, but the author of the white paper should confirm.

**Comment by skynavga** [comment]
@cconcolato please respond to above comment

**Comment by cconcolato** [comment]
Yes, we do want the positioning of boutens (textEmphasis) to behave like rubies.
