### ISSUE TITLE
condition="parameter(forced)==true" does not match the behavior of itts:forcedDisplay

### ISSUE THREAD

**Issue by palemieux** [w3c/ttml2#482]
TTML2 states:

> For the purpose of presentation processing, if an element specifies a condition attribute, and the its <condition> expression value evaluates to false, then the semantics of the element and its descendant elements must be ignored unless explicitly specified otherwise.

In contrast, IMSC1 states:

> a content element with a itts:forcedDisplay computed value of "false" shall not produce any visible rendering, but still affect layout, regardless of the computed value of tts:visibility.

It is therefore not possible to achieve the `itts:forcedDisplay` using `condition="forced"`.

**Comment by nigelmegitt** [comment]
I don't think this is correct - you could refer to a `style` element that conditionally sets `tts:visibility` since this achieves the same effect. It's the `style` element whose semantics are modified not the content that refers to it.

The "regardless of the computed value of tts:visibility" is misleading, in terms of the final effect, if I've understood right.

**Comment by palemieux** [comment]
> you could refer to a style element that conditionally sets tts:visibility since this achieves the same effect. 

Can you provide an example of how this would work?

**Comment by nigelmegitt** [comment]
Something like this, which might be simplifiable:

```xml
<style xml:id="forcedStyleFalse" condition="parameter(forced)==false" tts:visibility="false"/>
<style xml:id="forcedStyleTrue" condition="parameter(forced)==true" tts:visibility="true"/>
<style xml:id="forcedStyle" style="forcedStyleFalse,forcedStyleTrue"/>
...

<p style="forcedStyle">This text is only visible if forced==true</p>
```

**Comment by palemieux** [comment]
It is an extremely cumbersome alternative to the simple `itts:forcedDisplay` attribute. Does the approach above bring any capability to forced subtitles beyond those offered by  `itts:forcedDisplay`?

**Comment by nigelmegitt** [comment]
@palemieux that's a whole other question! I was just answering that I believe it is possible to reproduce the functionality. If you're looking for a benefit, at the least, it gives more flexibility, for example if people don't want the exact visibility behaviour for forced subtitles, they could choose to use, say `tts:display` instead, or whatever other approach they want to take.

**Comment by palemieux** [comment]
>  I was just answering that I believe it is possible to reproduce the functionality.

You have answered it! Closing the issue.

**Comment by skynavga** [comment]
BTW, TTPE maps ``itts:forcedDisplay`` to ``condition="parameter(forced)"`` in order to present IMSC1 documents with the defined IMSC forced display semantics by using TTML2 mechanisms. See the following directory for tests used by TTPE to verify this functionality

https://github.com/skynav/ttt/tree/master/ttt-ttpe/src/test/resources/com/skynav/ttpe/imsc1

**Comment by palemieux** [comment]
@skynavga Won't this remove the element from flow?

**Comment by skynavga** [comment]
When processing IMSC documents, TTPE (or, to be more accurate, TTXV) transforms the IMSC document into a TTML2 document from which formatting/presentation occurs. During this process, it translates from IMSC mechanisms to the functionally equivalent TTML2 mechanism.

Here, ``itts:forcedDisplay`` is mapped to a conditional style specification which is added to the list of styles references by the original IMSC content element that specified ``itts:forcedDisplay``, and which takes the following form:

```
<style condition="parameter('forced')" xml:id="s3" tts:visibility="visible"/>
```

BTW, condition never removes the element from the abstract document instance; rather, it causes its semantics to be conditionally processed.

See the following for more details:

[test.zip](https://github.com/w3c/ttml2/files/1449003/test.zip)
