### ISSUE TITLE
All ISDs must end, but not all TTML documents must end

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/ttml2#484]
It is possible to construct a TTML document with an ISD that has an indefinite end time but it is not possible to express this in an isd:isd document, because the end attribute on the root element is required and <timeExpression> does not permit a value equivalent to the SMIL keyword "indefinite" - I will raise that as a separate issue.

For example what ISD should be created for a TTML document with no `begin` or `end` attributes present at all?:

```xml
<tt>
<head/>
<body>
<div>
<p>some text that is visible from 0s forever</p>
</div>
</body>
</tt>
```

I propose:

* Make the `isd:isd/@end` attribute optional, so that its absence means "no end time".
* Add a note that the restriction on `isd:sequence` that prevents overlapping ISDs means that an ISD with no `end` attribute must be the final ISD in the sequence.

**Comment by nigelmegitt** [comment]
Not sure why Glenn's reply didn't appear here, but @skynavga said:

> Please consider the semantics of ``ttp:mediaDuration`` as may impact this issue.
> https://w3c.github.io/ttml2/spec/ttml2.html#parameter-attribute-mediaDuration

I had a look and the semantic appears to be orthogonal in that the media duration and the TTML duration are independent of each other. However we could reuse the syntax and allow the `/isd:isd/@end` attribute to take either a `<timeExpression>` or `"indefinite"`. That would work for me too as an alternative proposal.

The restriction on this only appearing in the final ISD in the sequence would still apply.

Is that what you meant @skynavga ?

**Comment by skynavga** [comment]
Yes. I will add an indefinite value.
