### ISSUE TITLE
Typo in backgroundClip

### ISSUE THREAD

**Issue by cconcolato** [w3c/ttml2#487]
The table defining [backgroundClip](https://www.w3.org/TR/ttml2/#style-attribute-backgroundClip) has an extra "|".

**Comment by cconcolato** [comment]
Same thing for [backgroundOrigin](https://www.w3.org/TR/ttml2/#style-attribute-backgroundOrigin)

**Comment by skynavga** [comment]
Fixed in c7951ca12751c1c1d376cad4b3c29717e5f9b2e0.
