### ISSUE TITLE
Clarify use of altText named metadata item.

### ISSUE THREAD

**Issue by skynavga** [w3c/ttml2#490]
See also #479.

**Comment by skynavga** [comment]
@palemieux regarding your comment https://github.com/w3c/ttml2/issues/490#issuecomment-343627783, there are no normative semantics defined for ittm:altText

**Comment by palemieux** [comment]
@skynavga The prose for `ttm:alt` need to match the prose of https://www.w3.org/TR/ttml-imsc1.1/#ittm-altText, including the various notes within the body of the specification. Much time and effort was spent making them accurate.

**Comment by skynavga** [comment]
As written, the prose you cite does not have any normative processing requirements, therefore, the semantics are the empty set.

**Comment by palemieux** [comment]
@skynavga IMSC1, TTML1 and TTML2 state "All content of this specification that is not explicitly marked as non-normative is considered to be normative", therefore all prose at https://www.w3.org/TR/ttml-imsc1.1/#ittm-altText is normative.

**Comment by nigelmegitt** [comment]
It is not possible for the `ttm:alt` _attribute_ to match the semantics of the `ittm:altText` _element_ since the latter can be extended with other attributes and can contain the attributes:

```
  xml:id = ID
  xml:lang = string
  xml:space = (default|preserve)
```

It would be overly complex to try to factor those attributes into an attribute value; in that case the option of `ttm:item name="altText"` remains available.

**Comment by skynavga** [comment]
Based on discussion among myself, @cconcolato and @palemieux, propose following addition to "altText" item under 14.3.2:

(1) add Note as follows "This text equivalent may be used to support indexing of the content and also facilitate quality checking of the document during authoring."

(2) add Note as follows: "In contrast to the common use of alt attributes in [HTML5], the content of the altText item is not intended to be displayed in place of the element if the element is not loaded. The ittm:altText attribute content can however be read and used by assistive technologies."

(3) do not add new @ttm:alt attribute (as suggested by this issue).

**Comment by skynavga** [comment]
Update title and change to editorial to reflect agreed resolution.
