### ISSUE TITLE
Defer ruby overflow and ruby overhang to TTML3

### ISSUE THREAD

**Issue by skynavga** [w3c/ttml2#494]
Having discussed the currently specified features tts:ruby{Overhang,Overflow}* with a number of potential users of these features, it appears that there is insufficient demand for them in TTML2 to justify the necessary refinement of their specification, implementation, and testing. Therefore, I propose they be removed from TTML2 and marked as a possible addition for TTML3.

**Comment by nigelmegitt** [comment]
I'm still awaiting information from some people about internationalisation requirements, but I would be surprised if I get significant demand for these features, so I will support this deferral until I hear otherwise.

**Comment by skynavga** [comment]
@nigelmegitt do you have any update on https://github.com/w3c/ttml2/issues/494#issuecomment-344738426? if not, then can we move forward with a PR to remove these features?

**Comment by nigelmegitt** [comment]
@skynavga No, please go ahead.

**Comment by skynavga** [comment]
@nigelmegitt wilco; and will leave some text in spec (at relevant position) that defines fall back default behavior in the absence of implementation specific behavior (for overhang/overlap scenarios);
