### ISSUE TITLE
Does showBackground="always" apply outside a region's begin and end times?

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/ttml2#498]
The following recently was raised in face to face discussions. In an example like:

```xml
...
<region xml:id="r1" tts:showBackground="always" tts:backgroundColor="red" 
        tts:position="..." tts:extent="..." 
        begin="10s" end="20s"/>
...
```

does the red background show only during 10s to 20s or also at other times?

**Comment by skynavga** [comment]
No.

**Comment by nigelmegitt** [comment]
@skynavga it was an either/or question

**Comment by skynavga** [comment]
The question in the title wasn't.

**Comment by palemieux** [comment]
> does the red background show only during 10s to 20s or also at other times?

I would say it shows only from 10s to 20s: at other times, the region does not exist.

**Comment by nigelmegitt** [comment]
> I would say it shows only from 10s to 20s: at other times, the region does not exist.

I think that's the same as @skynavga 's answer.

Then the next question is, within the period defined by the region's `begin` and `end` times, when is it _not_ active?

**Comment by palemieux** [comment]
> Then the next question is, within the period defined by the region's begin and end times, when is it not active?

When no content is flowed into the region.

**Comment by nigelmegitt** [comment]
That's logical, but currently we have:

> If the value of this attribute is always, then the background color of a region is always rendered when performing presentation processing on a visual medium; if the value is whenActive, then the background color of a region is rendered only when some content is flowed into the region.

The answers to my question, which both TTML1 editors agree on, suggest the first clause before the semicolon is wrong - `"always"` means "always rendered while the region is active" and `"whenActive"` means "when some content is flowed into the region", i.e. no change.

I propose that we amend the first sentence to be:

> If the value of this attribute is always, then the background color of a region is rendered either during the interval defined by its `begin`, `end` and `dur` attributes, if specified, or for the document's root temporal extent, when performing presentation processing on a visual medium.

There may be a more elegant way to phrase it.

**Comment by palemieux** [comment]
See the following at 9.1.2:

_For the purpose of determining the semantics of presentation processing, a region that is temporally inactive must not produce any visible marks when presented on a visual medium._

**Comment by nigelmegitt** [comment]
Okay, but that is not the same as "always", and if you instead in the tts:showBackground section refer to the period during which a region is "temporally active" then it is doubly confusing about what "whenActive" refers to.

**Comment by palemieux** [comment]
@nigelmegitt I think we should avoid bringing timing vocabulary in showBackground. What about:

_If the value of this attribute is always, then the background color of a region is always rendered when the region is temporally active; if the value is whenActive, then the background color of a region is rendered only when some content is flowed into the region._

**Comment by nigelmegitt** [comment]
@palemieux I like it, with the reservations that this sensible logic is not reflected in the keywords used. It's probably too late to fix that though. Rather than normatively bringing timing vocabulary in I think it would be worth adding an informative note:

_NOTE: A region may be temporally active when no content is flowed into it if it specifies any of the `begin`, `dur` or `end` attributes._

**Comment by palemieux** [comment]
@nigelmegitt What do you mean by "this sensible logic is not reflected in the keywords used"? Does temporally active have a meaning other than the period of time indicated by the begin, dur or end attributes?

**Comment by nigelmegitt** [comment]
@palemieux I mean that in your proposed language the keyword `always` maps to "temporally active" but `whenActive` maps to "when content is flowed in". 

It would be more intuitive if `whenActive` mapped to "temporally active", `always` didn't exist, and there were a different term for "when content is flowed in". We're too late to change that now though.

**Comment by skynavga** [comment]
I suggest we simply add prose that clarifies the interpretation of
whenActive and always, since we can't change these values.

**Comment by nigelmegitt** [comment]
@skynavga I think that's exactly what we're trying to craft here.

**Comment by skynavga** [comment]
This is neither a bug nor does it require a substantive change, since a mere editorial change is sufficient to resolve the potential ambiguity.
