### ISSUE TITLE
Computed active time of <p> with multiple <span> children in relation to showBackground="whenActive"

### ISSUE THREAD

**Issue by michlord** [w3c/ttml2#499]
Hello. I have a region with `tts:showBackground="whenActive"`
and content:
```html
<tt:div begin="00:00:00.000" end="00:00:10.000">
	<tt:p xml:id="subtitle1" region="bottom" style="paragraphAlign">
		<tt:span style="textWhite" begin="00:00:00.000" end="00:00:01.000">first</tt:span>
		<tt:span style="textWhite" begin="00:00:03.000" end="00:00:04.000">second</tt:span>
	</tt:p>
</tt:div>
```
There is a one-second gap between `first` and `second`. What is the active duration of the `<p>` element? Should I see the background between 00:00:01 and 00:00:03? My guess is that I should.

I can't find anything about this in the ttml2 specification.
I also tried looking at siml3 and it seems like I should be looking at the `endsync` attribute which is `all` by default. From this I conclude that active duration of `<p>` should be defined by a minimum of begin attributes and maximum of end attributes of the span elements.

Is this correct?

**Comment by nigelmegitt** [comment]
The `<p>` becomes active between 00:00:00 and 00:00:01 and then is not active from 00:00:00 until 00:00:03, when it become active again until 00:00:04.

**Comment by michlord** [comment]
Thank you for the quick response. I guess the time `<p>` is not active is a typo and it should be 00:00:01-00:00:03. I am curious how you were able to deduce this. Could you provide a quote from the specification?

**Comment by nigelmegitt** [comment]
Thanks, comment fixed. This result originates from SMIL - I don't think there is likely to be a single quick quote but you could look at https://www.w3.org/TR/SMIL20/smil-timing.html#Timing-EvaluationOfBeginEndTimeLists - each element has a list of begin and end times, not just a single begin and end time.

**Comment by michlord** [comment]
Thanks! It seems I will have to do some more reading but your argument is convincing. I think that this issue can be closed.
