### ISSUE TITLE
Begin times being relative to the root temporal extent can be wrong.

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/ttml2#512]
The term "root temporal extent" is used in several places in TTML2 as a reference point for the beginning of the document. However the root temporal extent itself is defined as:

> The temporal extent (interval) defined by the temporal beginning and ending of a document instance in relationship with some external application or presentation context.

This seems problematic to me. I think it would be clearer to relate unstated begin times, of e.g. `<body>` elements and `isd:isd` documents, to the applicable origin for the document's timebase. This frees up the root temporal extent also to begin at a time related to that same origin, and makes more sense especially in the context of §12.4.1 Media Timing Semantics, which goes into further detail about one consequence of the above definition, that the root temporal extent may be truncated at the beginning by the external application or presentation context. I would not expect the times in `isd:isd` documents for example to require offsetting to accommodate such a truncation - rather, they would remain the same relative to a fixed origin.

**Comment by nigelmegitt** [comment]
I just noticed also that begin times on ISDs are not fully defined in the case of smpte discontinuous mode. Presumably they should either be permitted as labels or the ISD times need further elaboration to explain that mapping to offset times is assumed to have happened already. @skynavga how do you want to treat this?

**Comment by nigelmegitt** [comment]
I have not addressed the smpte discontinuous issue on ISD but have addressed the initial point on the issue. I do not believe any semantic change is intended here so I have labelled it as editorial: it's a restructuring for clarity.

**Comment by skynavga** [comment]
Marking as a substantive (in the weak sense) as it may be construed to resolve (or change) possibly ambiguous semantics around the notion of a document's temporal extent and its relation to some other possible external time lines.
