### ISSUE TITLE
Consider removal of `<font-format>` in favour of top level MIME types

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/ttml2#543]
Proposed by @cconcolato 

Now that IANA has a registry for font/ at https://www.iana.org/assignments/media-types/media-types.xhtml#font we do not need `<font-format>`.

**Comment by skynavga** [comment]
SKYNAV formally objects to this proposal.

**Comment by dwsinger** [comment]
Now that there is a formal MIME registry for fonts, the spec. needs to be clear how to handle them, and we need to discuss how to handle this gracefully going ahead.

**Comment by skynavga** [comment]
Duplicates #544.
