### ISSUE TITLE
Media time relation assumption is incomplete.

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/ttml2#550]
The TTML1 text (reintroduced at https://github.com/w3c/ttml2/pull/536/files#diff-5ac39ab39265717d36dfd789d254ce1aR24385) states an assumption about the begin time in media timebase relating to the begin of the related media object. However this is incomplete.

> The above formalisms assumes that the Root Temporal Extent corresponds with the beginning of a related media object. If this assumption doesn't hold, then an additional offset that accounts for the difference may be introduced when computing media time M.

The full assumption is that the origin coordinates match, for example:

_The above formalisms assume that the zero point of the time coordinates corresponds with the zero point of the time coordinates of the related media object. If this assumption doesn't hold, then an additional offset that accounts for the difference may be introduced by the Document Processing Context when computing media time M._

I have also clarified above that the difference is out of scope of the document instance.

**Comment by skynavga** [comment]
Merger https://github.com/w3c/ttml2/pull/616 resolves closes this issue.

**Comment by skynavga** [comment]
Marking as a substantive (in the weak sense) as it may be construed to resolve (or change) possibly ambiguous semantics around the notion of a document's temporal extent and its relation to some other possible external time lines.
