### ISSUE TITLE
Regarding smpte:information (source material information)

### ISSUE THREAD

**Issue by plehegar** [w3c/ttml2#59]
[The following is extracted from the liaison received from SMPTE at https://lists.w3.org/Archives/Member/w3c-archive/2012Sep/0213.html]

The information element shall record details about the conversion process, including the type of data from which the document was translated.

See 5.7.4 at ST 2052-1 (https://www.smpte.org/sites/default/files/st2052-1-2010.pdf)

(raised by Pierre-Anthony Lemieux on 2013-05-30)
From tracker issue http://www.w3.org/AudioVideo/TT/tracker/issues/243

**Comment by skynavga** [comment]
With the introduction of namespace qualified named metadata items, this can be accommodated outside the scope of TTML2 proper. Absent a concrete proposal to define something, I am labelinig this as ttml.next and closing.
