### ISSUE TITLE
Rename and refactor module subsections.

### ISSUE THREAD

**Issue by palemieux** [w3c/ttml2#591]
Suggest renaming `<Module Name> Element Vocabulary` section titles to `Element Vocabulary`, since `<Module Name>` is already in the title of the parent section.

Same with `<Module Name> Element Vocabulary` and `<Module Name> Value Expressions`.

Also move `10.2.[2-53]` underneath a `10.2.2 Visual Attribute Vocabulary` and `10.3` under `10.2.3 Audio Attribute Vocabulary` such that Section 10.2.1 applies to both.

**Comment by skynavga** [comment]
No.

**Comment by nigelmegitt** [comment]
I think this change would make sense. We do not need the duplication of essentially identical text applying to tts namespace styling attributes and tta namespace audio styling, so making them peer subsections of a bigger 10.2 would be an improvement.

**Comment by skynavga** [comment]
I strongly disagree, and have already wasted enough time on this non-issue.

**Comment by skynavga** [comment]
Another reason this is a bad idea, and this will be my last comment on this issue, is that it removes important distinguishing information from ``<specref/>`` links, which, if this proposal were adopted, would create ambiguity in the text due to there being multiple sections so referenced that would no longer be distinguishable upon observation.

**Comment by nigelmegitt** [comment]
@skynavga that makes no sense to me. In the XML source the `specref` links have `href` attributes pointing to fragment IDs that are specified by `id` attributes on the relevant `div[n]` elements. In the unlikely case that readers of the built specification are inspecting the fragment IDs and attempting to extract meaning from them, we could continue to use the existing `id` values whilst still implementing this restructure. The `id` attributes have to be unique, so there can be no ambiguity.

**Comment by skynavga** [comment]
@nigelmegitt I am not talking about the ids, but the text.

**Comment by nigelmegitt** [comment]
@skynavga Ah, I see what you mean. However I think there remains merit in the second part of the issue:

> Also move 10.2.[2-53] underneath a 10.2.2 Visual Attribute Vocabulary and 10.3 under 10.2.3 Audio Attribute Vocabulary such that Section 10.2.1 applies to both.
