### ISSUE TITLE
Use of "may be derived from".

### ISSUE THREAD

**Issue by skynavga** [w3c/ttml2#630]
All uses of "may be derived from" (or equivalent) in Appendix N need to change to "is/are derived from". There is no choice involved here, since this section is describing how specification features are derived, and not how implementations may be constructed.

**Comment by skynavga** [comment]
Note that I am marking this for POST CR1, since it is strictly editorial.

**Comment by nigelmegitt** [comment]
I wrote it that way following WG's phone discussion about this. In my view there is a choice, since a reader wishing to understand the basis of the semantics can either go to the XSL source or the CSS source, with equivalent results. However I agree that in general the derivation section is supposed to describe the history. For me this is fine as is but I could accept another wording. 

@skynavga  how you intend to treat equivalent derivations?

**Comment by skynavga** [comment]
On Mon, Feb 5, 2018 at 3:57 AM, Nigel Megitt <notifications@github.com>
wrote:

> I wrote it that way following WG's phone discussion about this. In my view
> there is a choice, since a reader wishing to understand the basis of the
> semantics can either go to the XSL source or the CSS source, with
> equivalent results. However I agree that in general the derivation section
> is supposed to describe the history. For me this is fine as is but I could
> accept another wording.
>
First, I would not agree that they are not always equivalent, or, if they
are not equivalent, then XSL-FO semantics wins. Actually, I can't say when
they are equivalent. The most accurate description of derivation we could
give would go something like:

XX is based primarily on XSL-FO semantics, except in those cases where it
is based on CSS semantics, except in those cases where it is based on
neither. Furthermore "based on" should be understood to be intentionally
ambiguous, because TTML departs from these bases to a greater or lesser
extent.

**Comment by nigelmegitt** [comment]
> I can't say when they are equivalent.

@skynavga _All_ of the XSL based semantics that I added a CSS equivalent for are of the form where when you look up the XSL spec it simply refers to the CSS as its own semantic basis. That is the reason why I am confident that they are always equivalent: the spec we are referencing states the equivalence.
