### ISSUE TITLE
Revert <set> to single attribute and remove @fill and @repeatCount attributes

### ISSUE THREAD

**Issue by palemieux** [w3c/ttml2#635]
The syntax of `set` was expanded to support setting multiple style properties and the `fill` and `repeatCount` attributes, without defining new feature designators.

Propose removing these new capabilities unless use cases can be provided.

**Comment by skynavga** [comment]
I object to removing fill and repeat support, as that creates asymmetry with ``animate``. We can add feature designators ``#set-fill`` and ``#set-repeat``, and then exclude them from ``#animation`` and add them to ``#animation-version-2``.

**Comment by palemieux** [comment]
Defining additional features work as well. Please modify the PR or create a separate PR.

**Comment by skynavga** [comment]
OK, I will update this PR then.

**Comment by skynavga** [comment]
@palemieux this is intended to replace the part of #636 that deals with ``fill`` and ``repeatCount`` attributes on ``set``, as well as improve animation relation feature designators

**Comment by skynavga** [comment]
@palemieux please review #639 which you indicate will satisfy this issue
