### ISSUE TITLE
@animate in TTML1 diff

### ISSUE THREAD

**Issue by spoeschel** [w3c/ttml2#643]
In annex U.2.1 the attribute `animate` is mentioned as `@animate`, including the abbreviated XPath attribute axis `@`. As the other attributes in annex U do not include it, I assume this is a typo.

**Comment by cconcolato** [comment]
There are cases where we have the same name for an element and an attribute, e.g. `ttm:agent`, `region` or `animate`. The use of `@` in front of the name is to remove the ambiguity, see for example https://w3c.github.io/ttml2/#feature-layout or https://w3c.github.io/ttml2/#feature-metadata. However, in the particular section you are indicating, the title of the section talks about attribute, so we could remove it but it is not a type per se.

**Comment by skynavga** [comment]
As we use this convention elsewhere in the spec, this is intentional. Closing as works for me.

**Comment by spoeschel** [comment]
OK, this makes sense.
