### ISSUE TITLE
Metadata has no presentation semantics.

### ISSUE THREAD

**Issue by skynavga** [w3c/ttml2#656]
Need to formally state that metadata has no presentation semantics.

**Comment by palemieux** [comment]
Well, `usesForced` indicates that `@condition` is used, so it has indirect presentation semantics as specified in TTML2. This is in contrast to `altText` that has no presentation semantics.

**Comment by skynavga** [comment]
@palemieux By "has presentation semantics" I mean causes or can cause a difference in presentation be means of defined semantics. That ``usesForced`` is defined in terms of having used ``condition`` in no way produces a result in presentation.

**Comment by nigelmegitt** [comment]
Unless "fatal" we should defer this to post-CR1. I do not think it requires an urgent fix now.

**Comment by palemieux** [comment]
@skynavga The description of the issue does not state the problem that it is trying to solve. For instance, I am not sure why the line is being drawn at _no presentation semantics_ since one the metadata items `usesForced` actually has conformance implications. In any case, it does not look fatal, and so can be deferred until after CR.

**Comment by skynavga** [comment]
@palemieux the only conformance implementations are content conformance; there is no conformance implications for presentation processing; however, you seem to think there are, so please say what they are (since I don't know)

**Comment by palemieux** [comment]
@skynavga The `usesForced` item is tied to the presence of attributes within the document: _If [forced bound-parameter is] used in a document instance, then a usesForced named metadata item should be specified as a child of the head element._ More importantly, I do not understand the problem that this note is trying to solve.

**Comment by skynavga** [comment]
@palemieux ok, but so what? how does that create conformance implications for presentation processing?

**Comment by palemieux** [comment]
@skynavga I am not sure why presentation processor is any more or less relevant than conformance in determining what qualifies as a metadata item. What problem are you trying to solve?

**Comment by skynavga** [comment]
@palemieux there is nothing about this issue that pertains to what qualifies as a metadata item; this issue is merely documenting a long-standing fact: that, by design, metadata has no affect on standard presentation semantics as far as TTML is concerned; this can also be viewed as a promise that no future version of TTML will assign presentation semantics to metadata, which also means that metadata can be completely ignored by a presentation processor
