### ISSUE TITLE
Define missing feature designators.

### ISSUE THREAD

**Issue by skynavga** [w3c/ttml2#657]
Ensure that all new features are covered by at least one feature designator, adding as needed to the following task list:

- [x] ``#condition-media`` - media function used with ``condition``
- [ ] ``#display-inlineBlock`` - use of ``tts:display='inlineBlock'``
- [ ] ``#fontFamily-p`` - ``tts:fontFamily`` applies to ``p``
- [ ] ``#fontSize-p`` - ``tts:fontSize`` applies to ``p``
- [ ] ``#fontStyle-p`` - ``tts:fontStyle`` applies to ``p``
- [ ] ``#fontWeight-p`` - ``tts:fontWeight`` applies to ``p``
- [x] ``#set-multiple-styles`` - use of multiple style properties on ``set``

A checked box above means that the feature has been added into a PR associated with this issue.

Note that the level of granularity for defining feature designators is not fixed. Some _features_ may be defined at a finer degree of granularity than others. For example, in general, defining a feature designator for every possible value of a syntactic feature is not recommended.

**Comment by nigelmegitt** [comment]
@skynavga Please could you raise each of these as a separate issue & pull request or resolve all the points in a single pull request? Tracking and reviewing multiple partial fixes in separate pull requests is extremely inefficient.

**Comment by skynavga** [comment]
@nigelmegitt do you want to wait up until the last day before we are ready to go to CR and then discover another missing feature designator, open a new substantive PR, and start a new 14 day review period? that is what you are asking for; we can't afford such delays

**Comment by nigelmegitt** [comment]
> we can't afford such delays

@skynavga indeed we cannot - however opening a pull request before it is ready just to begin the 14 day period is merely gaming the system, and has no advantage relative to separate pull requests.

**Comment by skynavga** [comment]
See https://lists.w3.org/Archives/Public/public-tt/2018May/0103.html regarding possible reason not to define `fontFamily-p`, `fontSize-p`, `fontStyle-p`, and `fontWeight-p`.
