### ISSUE TITLE
Check changes document and new vocabulary appendix.

### ISSUE THREAD

**Issue by skynavga** [w3c/ttml2#658]
Ensure that changes document and new vocabulary appendix are accurate and adequately complete.

**Comment by nigelmegitt** [comment]
Changes has: 

```
* Change convention for labeling and citing definitions to use "[lower case]"
  in definitions and hyperlinked "lower case" in citations.
```

but I think "definitions" and "citations" are the wrong way round there.

**Comment by nigelmegitt** [comment]
Spotted a couple more:

* In Appendix I.2, add a sections describing the relationship of media time to document time.

* In 2.2, add "document temporal coordinate space".

**Comment by skynavga** [comment]
@nigelmegitt 

>but I think "definitions" and "citations" are the wrong way round there.

nope, it is correct
