### ISSUE TITLE
Compile and list at-risk features in SoTD.

### ISSUE THREAD

**Issue by skynavga** [w3c/ttml2#662]
The following features are currently marked for or should be marked for at-risk. Please edit this comment as needed to add additional features.

- [x] ``#animation-version-2``
- [x] ``#bpd``
- [x] ``#display-inlineBlock``
- [x] ``#extent-measure``
- [x] ``#font``
- [x] ``#fontSelectionStrategy-character``
- [x] ``#ipd``
- [x] ``#rubyAlign-withBase``
- [x] ``#textOrientation-sideways-LR``
- [ ] ``#validation``

For each at-risk feature, there should be a feature designator and an entry in the SoTD citing that designator. Checking one of the above means that these conditions are satisfied in some PR.

**Comment by nigelmegitt** [comment]
Request adding `#validation`, which I consider to be at risk because of being introduced very recently and because there is very weak consensus to include `ttp:validation` and `ttp:validationAction`.

**Comment by skynavga** [comment]
@nigelmegitt added and addressed in PR
