### ISSUE TITLE
Determine and specify CR exit criteria in SoTD.

### ISSUE THREAD

**Issue by skynavga** [w3c/ttml2#663]
I propose the following exit criteria:

>For every designated feature added in TTML2, the following conditions must be satisfied:
>1. at least one implementation of a transformation processor must support the feature, an example of which is a validating transformation processor that maps use of the feature to an output that indicates successful validation;
>2. at least two implementations of a presentation processors must support each mandatory feature that has defined presentation semantics;
>3. at least one implementation of a presentation processor must support each optional feature that has defined presentation semantics.

**Comment by cconcolato** [comment]
For the record, this was already discussed during the last F2F, see: https://www.w3.org/2018/01/10-tt-minutes.html#item48

**Comment by palemieux** [comment]
A pull request is needed for us to consider this tomorrow.

**Comment by nigelmegitt** [comment]
Thanks for the reminder @cconcolato - here's what we agreed:

> RESOLUTION: WG agrees TTML2 CR Exit Criteria are to have at least two independent implementations of each feature introduced in TTML2 where for presentation features at least one of those implementations is a presentation processor.

Having looked at it a bit further, we restructured validation processing in TTML2 so I think we need a slight tweak:

> For each feature not defined in TTML1:
>
> 1. At least two independent implementations must support the feature. If both transformation semantics and presentation semantics are defined for the feature, than at least one implementation must be a transformation processor and at least one implementation must be a presentation processor.
> 2. At least one of those implementations must be a validating processor that successfully verifies valid or invalid use of the feature as applicable;

I'll draft a pull request matching this, for discussion later.
