### ISSUE TITLE
Typo in <text-combine>, "auto" should read "all".

### ISSUE THREAD

**Issue by cconcolato** [w3c/ttml2#666]
The [textCombine semantics](https://w3c.github.io/ttml2/#style-attribute-textCombine) use the value `all` and not `auto` while the [`<text-combine>`](https://w3c.github.io/ttml2/#style-value-text-combine) type defines only `auto`. The latter should be changed to use `all` for consistency and to align with CSS.

**Comment by nigelmegitt** [comment]
I agree, it looks like we need to change `auto` to `all` in `<text-combine>`.

**Comment by skynavga** [comment]
Looks like this was a copy/paste error.

**Comment by skynavga** [comment]
Duplicate of #724. Closing.

**Comment by nigelmegitt** [comment]
Actually #724 was a duplicate of this, but let's not split hairs...
