### ISSUE TITLE
Document processing context should be able to override ttp:validationAction="abort".

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/ttml2#672]
See https://github.com/w3c/ttml2/pull/594#discussion_r169065047

**Comment by skynavga** [comment]
In my mind, this is a NO-OP; namely, unless there is spec text that prevents the implementation (= document processing context) from doing something, it can do it. We can't possibly document every case where the the implementation can do something that isn't precluded by the spec. Therefore, I'm marking this as works for me. I wouldn't object, however, to adding a note the points out the obvious, though that is just one more source of spec clutter.

**Comment by palemieux** [comment]
In what scenario would an author set `ttp:validationAction="abort"`?

**Comment by skynavga** [comment]
Duh. When they want to abort. For example, many processing chains have policies about validity enforcement.
