### ISSUE TITLE
Generic processor conformance too strict.

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/ttml2#673]
See https://github.com/w3c/ttml2/pull/594#discussion_r169063694

**Comment by skynavga** [comment]
@nigelmegitt this is not a problem; see https://github.com/w3c/ttml2/pull/594#discussion_r188835864

**Comment by nigelmegitt** [comment]
@skynavga I can see why you thought that, please see additional explanatory https://github.com/w3c/ttml2/pull/594#discussion_r188942681
