### ISSUE TITLE
Profile related features should be optional

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/ttml2#683]
In the transformation and processor profiles, the following feature designators should be marked as optional rather than required:

* `#contentProfiles`
* `#inferProcessorProfile`
* `#permitFeatureNarrowing`
* `#permitFeatureWidening`
* `#profile-version-2`

Rationale: It is reasonable for processors to support TTML2 in processing contexts where profile processing is not required and to omit support for those features.

**Comment by skynavga** [comment]
@nigelmegitt TTML1 mandates support for ``#profile`` for minimum compliance (which means EBU-TT is not compliant) of both transformation and presentation processors; why shouldn't TTML2 do the same (at least)? further TTML2 defines at least three essential new profile related features, without which the TTML2 profile system will not work:

* ``#contentProfiles``
* ``#processorProfiles``

I am open to not mandating some of the other profile related features currently included in ``#profile-version-2``, however, I cannot accept optionality for ``#contentProfiles`` and ``#processorProfiles``.

**Comment by nigelmegitt** [comment]
> without which the TTML2 profile system will not work

@skynavga my point is that not all processors need to operate the TTML2 profile system.

> TTML1 mandates support for `#profile` for minimum compliance

Yes, and with hindsight that also looks like an error.

**Comment by skynavga** [comment]
@nigelmegitt that's arguable, as this is the first suggestion that it should not be as it is since TTML1 1e was published (AFAIK)

**Comment by skynavga** [comment]
@nigelmegitt btw, I distinctly remember the WG deciding that all TTML2 documents should specify a profile binding, and @palemieux was particularly supportive of this requirement; I do, however, note that here we are talking about mandating processor support for profile binding, but it seems very odd indeed to require documents to specify a binding and give implementations a pass to ignore it
