### ISSUE TITLE
Exclude #rubyAlign-withBase from #rubyAlign.

### ISSUE THREAD

**Issue by palemieux** [w3c/ttml2#688]
`tts:rubyAlign-withBase` attribute does not exist

It is also not clear if `#rubyAlign` includes support for the value `withBase`

Suggest that `#rubyAlign` exclude support for value `withBase`

**Comment by skynavga** [comment]
This issue is conflating two distinct issues. Please try to use separate issues in the future. The first is an editorial issue, already being dealt with in #681. Therefore, I will modify the title and description of this issue to address only the comment about ``#rubyAlign``.

**Comment by skynavga** [comment]
Merged early per WG resolution.
