### ISSUE TITLE
Move processor conformance out of #validation

### ISSUE THREAD

**Issue by palemieux** [w3c/ttml2#689]
The definition of a validating processor should be moved to Section 3.2, and the statement _is a validating content processor_ removed.

**Comment by skynavga** [comment]
Section E.1.217 ``#validation`` does not define validating processor. Further, why should _is a validating content processor_ be removed?

**Comment by palemieux** [comment]
What does prohibiting “is a valid content processor” mean when #validation is prohibited?

**Comment by skynavga** [comment]
@palemieux first, the ``prohibited`` value applies only to content profiles, and it means:

>if the value of the value attribute is prohibited, then the feature must not appear in a document that claims conformance with that profile;

it has nothing to do with whether the feature is supported or not by a processor

**Comment by nigelmegitt** [comment]
See #672 regarding documents prohibiting validation.

**Comment by skynavga** [comment]
@palemieux is there any action you wish taken on this issue? if not, then please close

**Comment by palemieux** [comment]
@skynavga Apologies for the delay. I have been busy with IMSC and TTML1. Will get back to this soon. Is it blocking anything?

**Comment by skynavga** [comment]
@palemieux no, not blocking, just processing open issues

**Comment by skynavga** [comment]
@palemieux ping

**Comment by palemieux** [comment]
@skynavga Stepping back: "Transformation Processor" and "Presentation Processor" are defined in 3.2. Where is "Validation Processor Defined"?

**Comment by skynavga** [comment]
@palemieux It is not defined. Validation is an optional sub-processing step of a content processor, whether it is a transformation processor or a presentation processor. The semantics of validation as a sub-processing step is defined by Section 5.3. See also definition of term [validating content processor].

**Comment by tairt** [comment]
>  Glenn: There is no such thing as a validation processor, though I did discover two non-normative
>.. uses of that in the Introduction, which I can remove. A validating processor is a sub-processing
> .. step of a content processor, either a transformation or a presentation processor.

I do not share this view. IRT is developing a service which sole purpose is to validate TTML.  It quite common to have QC processors that do just checks of constraints of format definitions.

**Comment by skynavga** [comment]
@tairt I understand, and TTV is the same type of processor. However, from the TTML nomenclature we have employed, both the IRT and TTV processors would be validating transformation processors, where the output of the transformation is one bit expressing validity (or not). In this fashion, we can view validation processing as an optional component of our currently defined TTML Transformation or TTML Presentation Processors. Note also the analog in the `#speech` feature which is defined in terms of an optional speech processing component.
