### ISSUE TITLE
The #extent-measure designation includes the value auto.

### ISSUE THREAD

**Issue by palemieux** [w3c/ttml2#690]
The value `auto` should be removed from `#extent-measure` since `auto` is supported in TTML1, and presumably prohibiting `#extent-measure` is intended to achieve parity with TTML1

**Comment by skynavga** [comment]
The value ``auto`` in a measure expression is not the same thing as the value ``auto`` for ``tts:extent``.  The former is defined in section 10.4.24, while the latter is defined in 10.2.16.

**Comment by nigelmegitt** [comment]
Specifically with regards to `tts:extent` a single `<measure>` is not permitted, so it is syntactically unambiguous whether an `auto` corresponds to a possible value of `<extent>` or to one of a pair of `<measure>`s separated by `<lwsp>`.

**Comment by cconcolato** [comment]
That means that `auto` would not be equivalent to `auto auto`! One of the `auto` should probably be renamed to avoid confusion.

**Comment by skynavga** [comment]
That's correct. I think the best we can do is add a note pointing out this
oddity.

**Comment by nigelmegitt** [comment]
Tracing through `auto` and `auto auto` on `tts:extent` for each element it can apply to, I think they actually do resolve to the same thing. They wouldn't for `tt:tt@tts:extent` however `auto auto` is an illegal value there, so the situation doesn't arise.

**Comment by skynavga** [comment]
@palemieux @nigelmegitt is any further action required on this issue? if not, then please close

**Comment by palemieux** [comment]
@skynavga Apologies for the delay. I have been busy with IMSC and TTML1. Will get back to this soon. Is it blocking anything?

**Comment by skynavga** [comment]
@palemieux no, not blocking at this time

**Comment by nigelmegitt** [comment]
@palemieux if you are happy to close this, that would be fine for me - I don't believe any action is needed.

**Comment by palemieux** [comment]
> That's correct. I think the best we can do is add a note pointing out this oddity.

That would be good, and address my concern.
