### ISSUE TITLE
Use of PNG image format.

### ISSUE THREAD

**Issue by mikedo** [w3c/ttml2#694]
There are 16 uses of "PNG" in examples, yet it is not mentioned in the text and there is no citation to its definition.  Is PNG preferred?  We should probably at least add an informative reference.

**Comment by skynavga** [comment]
Suggest we define a new feature, ``#image-format-png``, the support of which requires support for some published format specification (possibly subsetted) to be referenced.

**Comment by skynavga** [comment]
Marking for agenda, as I need WG input to proceed.
