### ISSUE TITLE
Animate @calcMode value displace{,d} should read paced.

### ISSUE THREAD

**Issue by skynavga** [w3c/ttml2#699]
Typo in both XSD and RNC schemas where ``paced`` is written as ``displace{,d}`` as well as in section 13.3.3 ``<calculation-mode>``,  where ``paced`` is missing.

**Comment by nigelmegitt** [comment]
This is a substantive change since it introduces new syntax not previously included, even if that omission was unintended - I certainly had no idea that it was anyone's intention to include `paced`.

**Comment by skynavga** [comment]
@nigelmegitt I was torn on how to label it, so that is fine. Its absence is clearly an oversight, and was intended to be there (as indicated by the schema, though it wasn't correctly specified there either). In any case, we should make a determination on its inclusion, since I did not intend to exclude it and AFAIK, we have not discussed it in the group. My intent for ``<animate>`` was to have functional parity with SVG 1.1 which, in turn, is based on SMIL 3.0. That being said, I would not object to deferring support for ``paced`` to TTML3, etc. However, we expect that TTPE will support it in the TTML2 CR(s) time frame.

**Comment by nigelmegitt** [comment]
@skynavga I'll add this to the agenda so we can discuss it before making a determination.
