### ISSUE TITLE
Inline styling on tt:body

### ISSUE THREAD

**Issue by spoeschel** [w3c/ttml2#702]
Compared to TTML1 the `tt:body` element ([8.1.3](https://www.w3.org/TR/ttml2/#document-structure-vocabulary-body)) no longer allows inline styling on it i.e. `{any attribute in TT Style Namespaces}`. I guess this is just by mistake...

**Comment by skynavga** [comment]
Yes, a mistake. Good catch.

**Comment by skynavga** [comment]
Marking this as editorial as it was apparently a merge error.
