### ISSUE TITLE
Remove @condition from animation, head, layout, resources, styling, tt elements.

### ISSUE THREAD

**Issue by skynavga** [w3c/ttml2#704]
At present, the ``@condition`` attribute can apply conditionalization to the grouping elements ``animation``, ``head``, ``layout``, ``resources`` and ``styling``. However, only one of each of these grouping elements are permitted, and, consequently, a false condition on any of these would, respectively, remove all out-of-line animations, all out-of-line regions, all referential styling, etc., as a whole.

I am at a loss to find any concrete use case for such conditionalization scenarios to offset the complexity of supporting ``@condition`` in these contexts. Therefore, I propose we drop ``@condition`` from these element types.

**Comment by nigelmegitt** [comment]
What about the `tt` element itself?

**Comment by nigelmegitt** [comment]
I think this is right, but would like to double check with the WG before approving.
