### ISSUE TITLE
Derivations missing for tts:{disparity,luminanceGain,rubyReserve}

### ISSUE THREAD

**Issue by palemieux** [w3c/ttml2#709]
See [N.2.1.36 tts:rubyReserve](https://w3c.github.io/ttml2/index.html#derivation-rubyReserve)

**Comment by skynavga** [comment]
See [N.2.1.12 tts:disparity](https://w3c.github.io/ttml2/index.html#derivation-disparity).
See [N.2.1.27 tts:luminanceGain](https://w3c.github.io/ttml2/index.html#derivation-luminanceGain).

**Comment by nigelmegitt** [comment]
I didn't have the data available to complete those sections when I added the derivations. There may be some usable references for disparity based on the ETSI specifications referenced in the discussion of that feature but I would not be able to provide them for rubyReserve and luminanceGain.

We have these options:

1. Complete the derivation details if we know them
2. State in the derivation section that no derivation is available. This is the "lazy option" relative to the next one:
3. Remove the empty derivation section and replace the link from the table in the style attribute with "None".

Do we have the details to complete the sections?

**Comment by skynavga** [comment]
My intent is to say something equivalent to option #2.

**Comment by nigelmegitt** [comment]
For `tts:disparity` would anyone object to adding a note to the derivation to say that it is equivalent to twice (+2 *) the value of the disparity value as specified in [EN 300 743 v1.5.1](http://www.etsi.org/deliver/etsi_en/300700_300799/300743/01.05.01_60/en_300743v010501p.pdf) ? It's not exactly a derivation, but that is certainly referenceable prior work that signals effectively the same thing.

**Comment by palemieux** [comment]
@mikedo What is the CEA reference?
