### ISSUE TITLE
Disallow <length> {left,right} position syntax.

### ISSUE THREAD

**Issue by palemieux** [w3c/ttml2#711]
`<length> left` and `<length> right` are permitted syntax of `<position>` but their semantics are missing from _Two Component Equivalents_

**Comment by palemieux** [comment]
Note that CSS states "Note that a pair of keywords can be reordered while a combination of keyword and length or percentage cannot. So center left is valid while 50% left is not."

So I do not think the following are valid:

-  `<length> left`
- `<length> right`
- `top <length>`
- `bottom <length>`

This constraint allows the computation of the first length value without parsing the second component.

**Comment by palemieux** [comment]
See for instance the following snippet at https://jigsaw.w3.org/css-validator/#validate_by_input+with_options

```
body {
background-position: 50% left ;
}
```

**Comment by skynavga** [comment]
I am confused. Are you saying they are permitted but simply missing from the equivalence table (about which I agree). Or are you saying they should not be permitted, and therefore, should be removed from the syntax as possible expressions.

I would note that there is no ambiguity on parsing except in the case that both are length expressions, which we already deal with.

**Comment by palemieux** [comment]
@skynavga I think they should be removed since they (a) make parsing more complex and (b) is not consistent with CSS, which disallows them.

**Comment by skynavga** [comment]
@palemieux btw, they were defined in earlier CSS docs, which is where this syntax came from (I didn't invent any of it)

**Comment by palemieux** [comment]
@skynavga I believe you. They are no longer supported however... perhaps because it makes parsing more complicated.

**Comment by skynavga** [comment]
At present, the syntax allows reversing the horizontal and vertical components for 2-component values, i.e.,

```
<position>
  : offset-position-h <lwsp> offset-position-v    // two component values
  | offset-position-v <lwsp> offset-position-h    // two component values
  ...
```

so when you say

>This constraint allows the implementation to always assign the first length to a horizontal position and the second length to a vertical position.

what is it you mean?

Regarding mixing a keyword and length, there is obviously no ambiguity when an edge keyword (left, right, top, bottom) is used. That leaves only `center <length>` and `<length> center`, which are ambiguous unless we add an additional rule, such as,

_If the value consists of exactly two components, one of which is `center` and the other `<length>`, then the first component is interpreted as the horizontal offset position and the second component is interpreted as the vertical offset position._

Implementing such a rule seems trivial to me, and I believe that TTPE already does as much (though I need to confirm).

**Comment by nigelmegitt** [comment]
In the absence of any other data points I think we should be aiming for convergence with the current CSS specs on this.

**Comment by palemieux** [comment]
> That leaves only center <length> and <length> center, which are ambiguous unless we add an additional
> rule, such as,

The point is to avoid this ambiguity altogether by constraining the syntax, which matches CSS and simplifies implementations.

**Comment by nigelmegitt** [comment]
See #809 also - @skynavga you might want to handle that in the same pull request as the one that addresses this issue.
