### ISSUE TITLE
Bad internal links.

### ISSUE THREAD

**Issue by spoeschel** [w3c/ttml2#713]
The two feature designations [`#border-radii-1`](https://w3c.github.io/ttml2/#feature-border-radii-1) and [`#border-radii-2`](https://w3c.github.io/ttml2/#feature-border-radii-2) contain links to the `tts:border` attribute definition. However these links currently refer to the `tts:backgroundClip` attribute by mistake.

**Comment by spoeschel** [comment]
Furthermore the links of the [`#core`](https://w3c.github.io/ttml2/#feature-core) feature are affected; all three links refer to the `xml:id` definition. This also affects TTML1.

**Comment by skynavga** [comment]
Thanks. Please also file an issue against ttml1.

**Comment by spoeschel** [comment]
In the table of the [`tts:fontShear` definition](https://w3c.github.io/ttml2/#style-attribute-fontShear), the `<percentage>` link refers to `<length>`.

**Comment by spoeschel** [comment]
Also in the table of the [`tts:luminanceGain` definition](https://w3c.github.io/ttml2/#style-attribute-luminanceGain), the `<non-negative-number>` link refers to `<number>`.
