### ISSUE TITLE
Definition of implicit inline region

### ISSUE THREAD

**Issue by spoeschel** [w3c/ttml2#727]
The [feature `#region-inline-implicit`](https://www.w3.org/TR/ttml2/#feature-region-inline-implicit) refers to the definition of the `tt:region` element ([11.1.2](https://w3c.github.io/ttml2/#layout-vocabulary-region)). However it is defined neither in 11.1.2 nor anywhere else in chapter 11. The only definition I can find is in [2.2](https://w3c.github.io/ttml2/#terms) as part of the "inline region" term definition.

**Comment by nigelmegitt** [comment]
This needs to be refactored to point to [11.1.2.1](https://www.w3.org/TR/ttml2/#layout-vocabulary-region-special-inline-animation-semantics) since we changed "implicit inline regions" to be special cases of inline animation rather than being inline regions.
