### ISSUE TITLE
Feature #extent-measure also affects <length>

### ISSUE THREAD

**Issue by spoeschel** [w3c/ttml2#730]
When someone wants to set the `tts:extent` attribute to a `<length>` value, support of the [`#extent-measure` feature](https://w3c.github.io/ttml2/#feature-extent-measure) is required. The reason is that one can only get to `<length>` through `<measure>` here. 

As IMSC 1.1 currently prohibits the mentioned feature, thus also the usage of `<length>` is prohibited!

So it should be possible to allow the usage of `<length>` and prohibit the other values of `<measure>` at the same time. To address this e.g. the `#extent-measure` feature could be splitted somehow.

**Comment by nigelmegitt** [comment]
Further to this, `#extent` is defined in TTML1 as semantic support for `tts:extent` which only allows `auto | <length> <length>`, and allows them on `tt` and `region`. In TTML2 this has been refactored to be support for `#extent-region` and `#extent-root` - that does cover the elements they apply to but does _not_ subset the allowed syntax, which now also allows `contain`, `cover`, and other values specified under `<measure>` than `<length>`.

One step further, and `<length>` in TTML2 now allows `rw` and `rh` units that are not present in TTML1.

I suggest that this can most simply be resolved by adding a constraint to the definition of `#extent` to specify the permitted syntax such that it matches the TTML1 definition, e.g. append:

> where the support includes the keyword `auto` or two `<length>` values, and where `<length>` values with units include the units `px`, `em` or `c`.

**Comment by nigelmegitt** [comment]
I've just realised that #718 is relevant here too since it splits out the `rw` and `rh` unit support in `<length>`. I'm not quite sure how the two fit together though - it would be nice to find an elegant way to formulate `#extent` to make use of `#length` as defined in TTML1 as per #718.

**Comment by spoeschel** [comment]
I think we should definitely not restrict `rw` and `rh` here (but instead as part of addressing #718), as this would introduce unnecessary redundandy - and for consistency reasons require to exclude the two units also from any other usage of `<length>`.

Keeping such things seperated is also already the case in the TTML1 universe: In IMSC 1.0 `#extent` is permitted and at the same time `#length-negative` is prohibited.

**Comment by nigelmegitt** [comment]
See also #693 which impacts this issue.
