### ISSUE TITLE
Semantics of tts:rubyReserve length component.

### ISSUE THREAD

**Issue by palemieux** [w3c/ttml2#779]
The stated purpose of `tts:rubyReserve` is to space lines within a `p` as if ruby text annotations were present, regardless of the presence or absence of ruby text annotations.

The increase of spacing between lines in the presence of ruby text annotations is implementation dependent, and depends on the font size of the ruby text annotations.

The `length` component should therefore specify the font size of these hypothetical ruby text annotations, instead of specifying the absolute _amount by which the before or (and) after leading(s) of an affected line area are increased_. The absence of a `length` component should trigger the `tts:fontSize` special semantics (10.2.21.1 Special Semantics).

**Comment by skynavga** [comment]
Absent a conclusive demonstration that the current specification of this feature is substantially broken, I believe it is too late in the process to suggest the feature be re-designed as suggested. I am marking this as works for me for the time being and marking for the agenda for WG discussion. However, given the target of doing a CfC on CR2 by the end of the month, there would not be time to make a substantive change of this sort without sacrificing schedule.

**Comment by palemieux** [comment]
In absence of `tts:rubyReserve`, the author does not need to reserve/specify line space for ruby annotations: the presentation processor automatically adds an unknown (but appropriate) amount of space to each line to accommodate the ruby annotations. The authors' only involvement is to specify the font properties (size, family, etc.) of the ruby annotations.

How should the author determine the absolute incremental line space when using `tts:rubyReserve` as currently specified?

**Comment by skynavga** [comment]
@palemieux in the absence of a `<length>` specification, the implied length of 1/2 the paragraph's `normal` line height applies; if a `<length>` specification is present, that value is used; in this sense, an author faces the same challenge that applies to specifying an explicit `lineHeight` that is not `normal`; namely, will the specified value be too much, enough, or not enough; in this respect, `rubyReserve` suffers from the problem that the author doesn't know which fonts or font metrics are used by a presentation engine;

so the answer to your question, is the author should experiment to see what works...

in any case, the current definition is well defined and readily implemented

**Comment by nigelmegitt** [comment]
@palemieux I think your question at https://github.com/w3c/ttml2/issues/779#issuecomment-395292717 is about _non-use_ of `tts:rubyReserve` as opposed to default value processing - if so it seems like it's a different issue to this one. 

> How should the author determine the absolute incremental line space when using tts:rubyReserve as currently specified?

If you do want to raise that separately then it would be useful to explain the use case in which the author needs to determine this in advance.
