### ISSUE TITLE
Clarify no preceding sibling case on ruby delimiter.

### ISSUE THREAD

**Issue by spoeschel** [w3c/ttml2#788]
The issue of #787 also affects the "delimiter" case i.e. the following constraint (as TTML2 also allows delimiters with complex ruby, while the W3C ruby recommendation only allows delimiters when simple ruby is used):

"If the computed value of tts:ruby is delimiter, then the computed value of tts:ruby of its preceding sibling is base or text."

In addition ruby text content must not occur before a ruby delimiter, so the value "text" has to be removed from the constraint, too.

Proposal to change to:

"If the computed value of tts:ruby is delimiter, then its preceding sibling is either null (i.e., no preceding sibling) or the computed value of tts:ruby of its preceding sibling is base."

**Comment by spoeschel** [comment]
Sorry, forget about removing "text", as this will affect the second of the two delimiter within a text container.

So proposal to change to:
"If the computed value of tts:ruby is delimiter, then its preceding sibling is either null (i.e., no preceding sibling) or the computed value of tts:ruby of its preceding sibling is base or text."

**Comment by skynavga** [comment]
If there is no preceding sibling, then the constraint doesn't apply. There is no such thing as a null preceding sibling.

**Comment by spoeschel** [comment]
(see https://github.com/w3c/ttml2/issues/787#issuecomment-391289234)
