### ISSUE TITLE
Refactor #condition features.

### ISSUE THREAD

**Issue by skynavga** [w3c/ttml2#790]
The current definition of `#condition` related features is quite awkward, and needs refactored as:

`#condition-no-media` = condition expressions without media() function
`#condition-media` = condition expressions with media() function
`#condition` = `#condition-no-media` + `#condition-media`

**Comment by nigelmegitt** [comment]
Sorry I've had no time to catch up with this and comment on it, but I don't agree that `#condition` should be refactored in a way that introduces a negative feature designator. I _do_ agree that `#condition` should be refactored though, just that it should be the sum of a set of positive features, specifically:

* `#condition-fn-media` - supports `<media-function>`
* `#condition-fn-parameter` - supports `<parameter-function>`
* `#condition-fn-supports` - supports `<supports-function>`
* `#condition-primary` - supports primary (non function) expressions.
