### ISSUE TITLE
Clarify that tts:luminanceGain shall not apply unless absolute HDR scheme used.

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/ttml2#796]
It is not entirely clear that `tts:luminanceGain` must be ignored if the HDR scheme being used does not require absolute luminance values. In practice it would be actively dangerous to apply `tts:luminanceGain` for scene relative HDR schemes, but there is a use case where content providers want to specify `tts:luminanceGain` but have it only apply when, for example, PQ is used, and not apply for HLG, say.

I propose that we add a clarifying normative statement to back up the introductory clause: _, and when that presentation requires an absolute luminance value._ to make this a shall/shall not.

By the way, the test for if it should be applied is based on the qualities of the related media object, not on the content. So for example I expect `tts:luminanceGain` to be applied even to the images in a region and even if those images are already, say, PQ PNG images. We should probably advise not putting PQ images in `region`s that set `tts:luminanceGain` to anything other than 1.

**Comment by nigelmegitt** [comment]
@palemieux I'd appreciate your thoughts on how to avoid applying some luminance gain processing to a region if the output presentation requirement is absolute luminance pixels. The text:

> When applying `tts:luminanceGain`, the linear optical output values `(Cr, Cg, Cb)` of the components of a pixel of a region are defined as `80 ∙ tts:luminanceGain ∙ (r, g, b)`, where `(r, g, b)` are the normalized linear sRGB components of the pixel. 

and the fact that `tts:luminanceGain` has a default value of 1.0, appears to mean that there is no way to avoid multiplying the pixel values by 80 even when `tts:luminanceGain` is not specified on a region. This means that a PQ PNG image cannot avoid further processing even though it already generates absolute luminance pixels, since it cannot be placed outside any region.

Options I can see:

1. Except PQ images from luminanceGain processing
2. Allow a `none` keyword for luminanceGain, and make that the default. The syntax would therefore be `none | <non-negative-number>`

I've started working on the pull request to resolve this issue, but this particular point is blocking me from making further progress.

**Comment by palemieux** [comment]
> Except PQ images from luminanceGain processing

I think that is a good starting point: `tts:luminanceGain` shall apply (a) only when compositing onto absolute luminance presentation and (b) only to sRGB elements, whether text or images.

**Comment by nigelmegitt** [comment]
@palemieux agreed, I'll update to state that. We may need a processor feature to indicate that the processor supports detection of output pixels being sRGB or some other colour space on an element by element basis to enable that, I'm mulling it over. We discussed that in yesterday's call - one consequence would be that we no longer would need to reference the WG Note on PQ HDR in PNG but could reference the ITU HDR specifications directly.

**Comment by skynavga** [comment]
Merged early per WG resolution.
