### ISSUE TITLE
Use of maximum descendant font size in normal line height computation.

### ISSUE THREAD

**Issue by skynavga** [w3c/ttml2#806]
It appears that when we reworked the algorithm for resolving the value of ``normal`` line height that the language regarding use of maximum descendant font size was inadvertently left out.

TTML1 (8.2.12) says

>If the value of this attribute is ``normal``, then the computed value of the style property must be considered to be no less than the size of the largest font size that applies to the element and its descendant elements in the intermediate synchronic document as determined by 9.3.3 Intermediate Synchronic Document Construction.

As it turns out, this language, which was intended to be compatible with XSL-FO and CSS2, does not in fact yield the correct result because it takes the maximum descendant font size for the paragraph and assigns that value as a single value to the every line area generated by the paragraph. In contrast, the definition of **per-inline-height-rectangle**, which XSL-FO states is compatible with CSS2, makes use of the maximum font size of the inline areas on a per-line-area basis, not for all line areas in the paragraph, and, further, factors in the ascent, descent, and leading for individual inline area descendants of a line area.

XSL-FO 1.1 (4.5) says

>The extent of the per-inline-height-rectangle in the block-progression-direction is then defined to be the minimum required to enclose both the expanded-nominal-requested-line-rectangle and the expanded-rectangles of all the inline-areas stacked within the line-area; this may vary depending on the descendants of the line-area.

The defining language in CSS2 can be found in section 10.8, which has evolved (mainly via clarification and additional prose) from CSS2 (1998) to the current draft of [CSS2.2](https://www.w3.org/TR/CSS22/visudet.html#line-height).

Taken together, I conclude that, as presently written:
- TTML1 semantics for `normal` do not match either CSS2 or XSL-FO;
- TTML2 semantics for `normal` do not say anything (at present) about taking the maximum of descendants, and, therefore, match none of TTML1, CSS, nor XSL-FO;

To resolve this, we need to clarify/refine the algorithmic language found in [TTML2 10.2.27](file:///Users/glenn/work/ttml2/spec/ttml2.html#style-attribute-lineHeight). We also need to back port the essential clarifications to TTML1.

I am going to mark this as a a bug, and requiring substantive changes, even though one might (marginally) argue that it is editorial since our intentions were to match CSS2/XSL-FO in the first place. However, to resolve this, we will need to introduce new normative algorithmic language which can affect conformance.

**Comment by nigelmegitt** [comment]
See also comments on #799. Specifically, when there's an embedded inline area that has a different writing direction, e.g. _tate chu yoko_  horizontal text within vertical text, any attributes that affect the inline dimension extent of the embedded inline area potentially affects the line height of the containing text. These include `tts:fontShear`, `tts:fontKerning`, `tts:fontStyle`, `tts:fontWeight`, `tts:letterSpacing` for example - there may be others but those are the ones I could find on a first pass scan.

We could:

1. ignore this as an edge case that implementations can choose to handle as they see fit
2. explicitly include this in the calculation of line height
3. explicitly exclude this from the calculation of line height (potentially resulting in overlapping text on adjacent lines)

**Comment by skynavga** [comment]
@nigelmegitt it will have to be option (2), since the use of tate-chu-yoko already implies a requirement to adjust line height (i.e., bpd of line area) in order to fit longer horizontal segments; e.g., two half-width digits set horizontally in a vertical line will fit into a single kanji cell, but four digits will not, and thus expands the bpd; this is what is implemented in TTPE at present, and common in advanced typesetters; however, this is based on use of `normal` lineHeight; if a fixed length is specified for lineHeight, then option (3) applies

**Comment by skynavga** [comment]
I have removed the bug and substantive labels, as it may not be as bad as I thought, and perhaps a few informative notes can clear up possible ambiguity in reading. I will propose a PR soon.

**Comment by skynavga** [comment]
@palemieux raise issues as needed with CSSWG regarding `line-height` value `normal` semantics in CSS
