### ISSUE TITLE
Disallow `offset-position-v` as a one component position

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/ttml2#809]
See also #711 and #769.

Currently two options are available for one component `<position>` values:

```
<position>
  : offset-position-h                             // single component value
  | offset-position-v                             // single component value

...

offset-position-h
  : position-keyword-h
  | <length>

offset-position-v
  : position-keyword-v
  | <length>

...

position-keyword-h
  : "center"
  | edge-keyword-h

position-keyword-v
  : "center"
  | edge-keyword-v

edge-keyword-h
  : "left"
  | "right"

edge-keyword-v
  : "top"
  | "bottom"
```

And the table explaining the equivalents of the one component values maps:
* `center` -> `center center`
* `<length>` -> `<length> center`

Both of those mappings indicates that a valid value for an `offset-position-v` of `center` or `<length>` will be interpreted as an `offset-position-h`. So in those cases the spec is actively misleading in suggesting that a vertical offset value can be used on its own.

The only one component values that are unambiguously vertical positions are `top` and `bottom`. Rather than handling those two specific values (which I guess would be rarely used because mostly authors leave a gap at the top or the bottom of the root container region), for simplicity I propose that we remove `offset-position-v` from the permitted set of one component values.

**Comment by skynavga** [comment]
Rather than dropping single value `top` and `bottom`, I suggest we replace `offset-position-v` with
`edge-keyword-v` in this context, which will make this an editorial change only.
