### ISSUE TITLE
Eliminate references to around and between in tts:rubyReserve.

### ISSUE THREAD

**Issue by cconcolato** [w3c/ttml2#811]
https://github.com/w3c/ttml2/issues/783 was addressed by https://github.com/w3c/ttml2/pull/800 and the `around` and `between` values where removed for the syntax, but the semantics for `around` and `between` remained, and `around` is referenced by `auto`.

Also, the semantics are hard to read because of all the if conditions.

**Comment by skynavga** [comment]
Merged early per WG resolution.
