### ISSUE TITLE
Applicability of tts:rubyPosition when tts:ruby="text".

### ISSUE THREAD

**Issue by palemieux** [w3c/ttml2#832]
If a ruby text is not a child of a ruby textContainer, then `tts:rubyPosition` specified on the ruby text applies to the implicit parent ruby textContainer.

If a ruby text is a child of a ruby textContainer that specifies `tts:rubyPosition`, then `tts:rubyPosition` cannot be specified on the ruby text.

What happens if `tts:rubyPosition` is specified on ruby text is the child of a ruby textContainer for which `tts:rubyPosition` is not specified? Does it override the computed value of `tts:rubyPosition` on the parent ruby textContainer? What happens if different children of a ruby textContainer specify different `tts:rubyPosition` values -- which one applies the parent ruby textContainer?

Suggest expanding the rule to state that `tts:rubyPosition` cannot be specified on a ruby text that has an explicit parent ruby textContainer.

**Comment by palemieux** [comment]
Note also that CSS `ruby-position` applies only to _ruby annotations containers_

**Comment by nigelmegitt** [comment]
A "cannot be specified" rule sounds normative, and we will find that difficult to change at PR stage. Adding to the agenda for today's meeting: if we need to make this change then we need to get it into CR2 as soon as possible, which I might treat as group review feedback on the CfC in order not to add further delay.

**Comment by skynavga** [comment]
Pending WG approval for merger of #833 prior to publishing CR2.

**Comment by skynavga** [comment]
Merged early per WG resolution.
