### ISSUE TITLE
Make #extent-length and #extent-measure complementary.

### ISSUE THREAD

**Issue by palemieux** [w3c/ttml2#846]
... otherwise a content profile cannot prohibit all `<measure>` expressions but `<length>` values

**Comment by nigelmegitt** [comment]
Expanding slightly, am I right in understanding that the problem if that if you specify a content profile with:
* `#extent-length` permitted
* `#extent-measure` prohibited

then the prohibition for the `<length>` component of a `<measure>` from `#extent-measure` would contradict the permission for it from `#extent-length`?

**Comment by skynavga** [comment]
Merged early per WG resolution.

**Comment by nigelmegitt** [comment]
We've somehow lost `#length-root-container-relative` from `#extent-xxx` since it is now neither in `#extent-measure` nor in `#extent-length`. I'll raise a separate issue for adding `#extent-length-version-2` to reference `<length>` as defined in TTML2.
