### ISSUE TITLE
Add `#extent-length-version-2`

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/ttml2#853]
As mentioned at https://github.com/w3c/ttml2/issues/846#issuecomment-399470199

We've somehow lost `#length-root-container-relative` from `#extent-xxx` since it is now neither in `#extent-measure` nor in `#extent-length`.  Suggest adding `#extent-length-version-2` to either:

1. reference `<length>` as defined in TTML2 or 
2. extend `#extent-length` to include support for `#length-root-container-relative` as applied to `tts:extent`.

**Comment by skynavga** [comment]
Merged early per WG resolution.
