### ISSUE TITLE
Deterministic text wrapping and presentation

### ISSUE THREAD

**Issue by plehegar** [w3c/ttml2#86]
There's a complex interaction between lineHeight, fontSize, overflow and wrapOption that determines, for the font that the display processor chooses, how much text will fit on a line and whether any text that doesn't fit overflows or is truncated. This creates a problem for document authors if they can not be certain of the metrics of the font used to present their content.

The goal from an audience perspective is that the on-screen text is readable and complete. Nobody wants missing words (that could change the editorial meaning) or text that is visible but unreadable.

TTML offers little by way of solution to this real world problem at the moment. The IMSC submission presents a 'reference font' mechanism, which should be considered. Is there anything more that we can do natively in TTML to allow deterministic rendering to be defined at the point of authoring?

Raising this issue for discussion at TPAC.

Note that there are related issues (to be filed separately) around lineHeight=normal being related to the height of the text actually flowed onto a line (is it? or is it related to the descendent elements of the <p>?) and being set to a percentage of the font size - should it be 100%, 120%, 125% etc. for compatibility with CSS etc.

(raised by Nigel Megitt on 2013-10-10)
From tracker issue http://www.w3.org/AudioVideo/TT/tracker/issues/283

**Comment by nigelmegitt** [comment]
I consider that the ability to reference or include fonts directly in TTML2 using the [font](https://www.w3.org/TR/ttml2/#embedded-content-vocabulary-font) element, as well as other discussions and clarifications is sufficient to deal with this issue, and that any more specific questions are logged as individual issues. Closing.
