### ISSUE TITLE
Schemas are missing tts:display 'inlineBlock' value.

### ISSUE THREAD

**Issue by skynavga** [w3c/ttml2#874]
This is an editorial change since isolate is already defined in spec, which is takes precedence.

In addition, update EOL convention in RNC schemas to use unix EOLs.

**Comment by cconcolato** [comment]
> This is an editorial change since isolate is already defined in spec, which is takes precedence.

I think you meant "inlineBlock" not "isolate".

**Comment by skynavga** [comment]
@cconcolato that was already fixed in github

**Comment by cconcolato** [comment]
I meant in https://github.com/w3c/ttml2/issues/874#issue-337301805. It is still there.

**Comment by skynavga** [comment]
@cconcolato ok, but in the future, you can just edit the comment to fix it directly
