### ISSUE TITLE
Cardinality of style properties in <set> incorrect

### ISSUE THREAD

**Issue by palemieux** [w3c/ttml2#877]
[`set`](https://w3c.github.io/ttml2/index.html#animation-vocabulary-set) currently specifies `{any attribute in TT Style Namespaces}` whereas it should be `{a single attribute in TT Style namespace}`, matching [TTML1](https://www.w3.org/TR/ttml1/#animation-vocabulary-set)

**Comment by skynavga** [comment]
It is not incorrect. That change was made intentionally as a result of [Change Proposal 1](https://www.w3.org/wiki/TTML/changeProposal001).

**Comment by skynavga** [comment]
See also https://www.w3.org/AudioVideo/TT/tracker/issues/165.

**Comment by skynavga** [comment]
Note further that we already defined a feature to cover multiple styles on `set`: `#set-multiple-styles` [1].

[1] file:///Users/glenn/work/ttml2/spec/ttml2.html#feature-set-multiple-styles
