### ISSUE TITLE
Unicode bidi should probably not be animatable.

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/ttml2#881]
See https://github.com/w3c/csswg-drafts/issues/2751#issuecomment-402604609 where this conversation has just happened in CSS WG.

**Comment by skynavga** [comment]
I agree, but that would probably be a normative change, which we have agreed to not undertake in CR2 unless the specification is radically broken. I suggest marking this as ttml.next and closing without further action.

**Comment by skynavga** [comment]
If we should decide that changing the animatability of a property is not normative, then we should probably scale back animation on a number of other properties as well in TTML2. In such a case, I would propose that continuous animation (linear, paced, spline) modes apply only to a small number of properties, none of which can trigger re-layout. This set would include color, position, and opacity, and perhaps no others.

**Comment by skynavga** [comment]
If we are going to remove discrete animation from `unicodeBidi` then we need to do the same with `direction`. Furthermore, we can only deprecate and not eliminate discrete animation, since we allow discrete animation of these properties in TTML1.

**Comment by nigelmegitt** [comment]
I'm not so concerned about discrete animation, since it is effectively a shorthand for generating a new ISD with different styling, which can be done without any animation at all as a straightforward transformation. I think the CSS concern was more about continuous animation. I think we can leave discrete animation in place for `unicodeBidi` and `direction`, whether we deprecate it or not.

**Comment by nigelmegitt** [comment]
The CSS WG's current view on animatable properties is captured at https://drafts.csswg.org/css-transitions/#interpolated-types - should we be adopting the same semantic inline with that spec?

**Comment by nigelmegitt** [comment]
OK that's a reasonable filter to use. Arguably we could support more animation of text shadows though I don't have any particular use case for that in mind.

**Comment by skynavga** [comment]
Merged early per WG resolution to move to CR3 CfC.
