### ISSUE TITLE
Two text containers with same tts:rubyPosition (not "outside").

### ISSUE THREAD

**Issue by spoeschel** [w3c/ttml2#882]
When a ruby annotation with two text containers is used, currently each text container could use the same `tts:rubyPosition` value different to `outside` (e.g. `after`). In that case the two containers would have to be rendered on the same side of the actual ruby base text.

Is this case intended? If so, which of the two text containers will be the one rendered adjacent to the base text?

**Comment by skynavga** [comment]
Merged early per WG resolution to move forward with CR3 CfC.
