### ISSUE TITLE
Add #opacity-image feature.

### ISSUE THREAD

**Issue by spoeschel** [w3c/ttml2#883]
The TTML2 features related to the `tts:opacity` attribute currently don't cover the case that this attribute can also apply to an `image` element. So a respective feature has to be added, e.g. `#opacity-image`.

**Comment by skynavga** [comment]
Note, we are no longer permitting substantive changes in CR2 unless the specification is radically broken, which does not cover this suggestion. In any case, I believe this proposal is arguable, i.e., such a necessity does not exist in fact.

**Comment by skynavga** [comment]
Suggest marking this as ttml.next and closing without further action.

**Comment by spoeschel** [comment]
> Note, we are no longer permitting substantive changes in CR2 unless the specification is radically broken, which does not cover this suggestion.

OK, I see. This issue was just for the sake of consisteny of the spec. I don't have an actual requirement for this feature.

> In any case, I believe this proposal is arguable, i.e., such a necessity does not exist in fact.

Hmm, what would be the alternative to require support for this attribute on `image`?

> Suggest marking this as ttml.next and closing without further action.

Yes, absolutely fine.

**Comment by skynavga** [comment]
@spoeschel if I were designing a profile, then I would (1) specify that both `#opacity` and `#image` are required, and (2) add prose to the text of an associated profile definition document such as:

>An implementation of this profile is required to support the semantics of `tts:opacity` when applied to an `image` element.

**Comment by skynavga** [comment]
@spoeschel actually strike the last (though that would work as well); in reviewing the `#opacity*` features, I see we have to features that would cover its use with `image`, namely, `#opacity-block` and `#opacity-inline`.

**Comment by spoeschel** [comment]
I previously asked myself whether `#opacity-block` or `#opacity-inline` would already cover this. But that features refer just to content elements, which are `body`, `br`, `div`, `p`, `span`, according to the definition of the content elements term and table 5-3.

**Comment by skynavga** [comment]
Given the existence of `#visibility-{block,image,inline,region}`, it seems reasonable to add `#opacity-image` to provide consistency with `#visibility-*`. Removing ttml.next label and marking this for TTML2 2e milestone.

**Comment by skynavga** [comment]
Marking this issue as a bug since the omission of `#opacity-image` was an oversight.
