### ISSUE TITLE
Change note to normative text regarding inheritance of 'normal' line height.

### ISSUE THREAD

**Issue by skynavga** [w3c/ttml2#888]

**Comment by skynavga** [comment]
Closing after logging this ttml.next issue. May reopen in this repository for subsequent ttml.next processing.

**Comment by skynavga** [comment]
Closing this for future possible processing under ttml.next.

**Comment by nigelmegitt** [comment]
This was done in #946, effectively a duplicate, since we had the opportunity to do it in CR3, so I will remove the ttml.next label.
