### ISSUE TITLE
Role parameters support

### ISSUE THREAD

**Issue by plehegar** [w3c/ttml2#9]
Interoperability with current practice in US captioning has been expressed as a desirable goal, however CEA 708 offers parameterised role, roles in DFXP are single valued.

Should role parameters be added to DFXP?

(raised by Philippe Le Hégaret on 2008-12-05)
From tracker issue http://www.w3.org/AudioVideo/TT/tracker/issues/25

**Comment by skynavga** [comment]
Absent a concrete proposal, I am labeling this as ttml.next and closing.
