### ISSUE TITLE
Rules for splitting and accumulating documents

### ISSUE THREAD

**Issue by plehegar** [w3c/ttml2#91]
EBU Liaison has requested: "Document segmentation: rules for breaking up a document into arbitrary smaller chunks or samples each with a specified time range, likely to be used for streaming e.g. in MPEG Dash or similar carriage mechanisms; for assembling a series of smaller documents into larger ones, e.g. for archive purposes; for combining these activities to create new samples with different temporal extents."

An EBU document describing such rules has been circulated in draft form but is not openly available. For those with access to the EBU XMLSubtitles workspace it can be found at http://workspace.ebu.ch/download/attachments/11998865/mim-xmlsubs0133r05.EBU-TT_Segmentation.pdf or can be sent directly to those who request it - contact Nigel Megitt.

One option presented by the proposal is that documents may contain content that extends beyond its temporal extent without extending the document's overall temporal extent. This simplifies the splitting and accumulating tasks.

(raised by Nigel Megitt on 2013-10-23)
From tracker issue http://www.w3.org/AudioVideo/TT/tracker/issues/288

**Comment by skynavga** [comment]
The WG has decided that this is effectively an external application of TTML, and that it should not be defined in TTML proper. Instead, an extension specification may be developed and published that builds on TTML2 and defines this as extension functionality.
