### ISSUE TITLE
Remove xml:base and @condition from chunk.

### ISSUE THREAD

**Issue by skynavga** [w3c/ttml2#961]
An `xml:base` attribute was inadvertently defined for use on the `chunk` element. However, the `chunk` element does not permit any child elements or metadata attributes to which an `xml:base` attribute could potentially apply. This is currently reflected in the schemas as well which do not define use of `xml:base`.

**Comment by nigelmegitt** [comment]
What's the harm in having `xml:base` here even though it has no current use?

**Comment by skynavga** [comment]
Well, I was going to cite the language under xml:base (below), but I now notice that chunk allows `@condition` (which is questionable), so it looks like it might have a use for `xml:base`:

>The xml:base attribute may be used with any element in the core vocabulary catalog that admits (1) a condition attribute, (2) a descendant element in the Metadata.class element group, or (3) a descendant element that admits an xml:base attribute.

Now that I have noticed this, we can either remove `@condition` as well or leave it alone, retaining both `@condition` and `xml:base`.

**Comment by skynavga** [comment]
I prefer removing both  `@condition` and `xml:base` from chunk, as the former is quite dangerous (how are you going to express a data resource with conditionalized segments?), and the latter is a no-op. I am also upgrading this issue (and PR) to substantive.

N.B. If we do not take this action now, then we will need to deprecate these in TTML2 2e.

**Comment by nigelmegitt** [comment]
To my mind the use of `@condition` on `chunk` is indistinguishable from its use on `source`, except in one case the data is embedded and in the other it is external. This is outside of the review scope for CR3 CfC, I vote to defer this and not make any changes for now, since making changes seems to be opening up a larger "can of worms". It isn't even clear to me that deprecating it in a future edition is what we'd want to do.

**Comment by skynavga** [comment]
@nigelmegitt there is a very big difference between chunk and source; in the case of chunk, all chunk children of data apply and are composed in order to create the data resource; in the case of source, only one source child is chosen; the only reason one might want to use chunk is to conditionally include or exclude a segment of bytes in a data resource; I rather have to stretch my imagination as to when one would actually use such a technique, but I suppose it is possible; my preference would be to exclude this now until we come up with a real use case, but if you insist, I can accept deferring this to TTML2 2e where we might deprecate it

**Comment by nigelmegitt** [comment]
Thanks @skynavga for being willing to defer, we have consensus to do that at this moment, whereas we don't have time to conclude on a resolution for this now, given it is out of the scope of our CfC review.

Please follow your normal procedure for deferring an issue.

**Comment by skynavga** [comment]
Defer to ttml.next.

**Comment by skynavga** [comment]
Removing ttml.next, leaving here for ttml2 2e processing.

**Comment by skynavga** [comment]
Marking this issue as a bug since the inclusion of `xml:base` and `@condition` on `chunk` was an oversight.
