### ISSUE TITLE
Special inheritance rule of font size for ruby text content is contradictory.

### ISSUE THREAD

**Issue by palemieux** [w3c/ttml2#967]
Given the following example:

```
        <span tts:ruby="container" tts:fontSize="0.1rv">
         <span tts:ruby="baseContainer"><span tts:ruby="base">base</span></span>
          <span tts:ruby="textContainer"><span tts:ruby="text">text</span></span>
        </span>
```

The computed font size at _text_ will be 25% of `0.1rv` since Section 10.2.21.1 specifies that the computed font size for the text container is 50% of that the container, and the computed font size for the text is 50% of that of the text container.

Given the following example:

```
        <span tts:ruby="container" tts:fontSize="0.1rv">
         <span tts:ruby="base">base</span>
          <span tts:ruby="text">text</span>
        </span>
```

The computed font size at _text_ will be 50% of `0.1rv` since Section 10.2.21.1 specifies that the computed font size for the text is 50% of that of the text container.

Is that intended, i.e. that the font size of _text_ is different?

**Comment by skynavga** [comment]
So, the intent is not to apply the 50% rule twice, ending up with 25%. But I can see that the language in the last paragraph of 10.2.21.1 is problematic:

>A span element for which the computed value of tts:ruby is text does not inherit tts:fontSize unless its parent is a span element for which the computed value of tts:ruby is textContainer. Instead, if no tts:fontSize attribute is specified on the ruby text span element, a value equal to 50% of the value of the computed value of tts:fontSize on the nearest ancestor span element for which the computed value of tts:ruby is textContainer or container is used, whichever is most immediate to the ruby text span element; otherwise, the specified value is used.

The first sentence says that the ruby text content inherits font size from its ruby text container, which by my thinking, means it uses the ruby text containers computed font size without change.

But then, what does the second sentence mean? First, what is meant by "Instead"? I take this to mean _otherwise_, which means the second sentence deals with the case where the parent of the ruby text content is not a ruby text container, which means it must be a ruby container (using the shorthand syntax, and without considering the possible insertion of an implied ruby text container). But then the second sentence goes on to talk about using 50% of the computed font size from the nearest **ruby text container** or ruby container ancestor. So either (1) _instead_ doesn't mean what we think or (2) the remainder of the second sentence shouldn't include a ruby text container, but only include the ruby container.

I am inclined to prefer option (2) as an approach to a fix (and substitute _otherwise_ for _instead_.

Alternatively, we could rewrite the last two paragraphs to explicitly take into account an implied ruby text container, in which case we have the following scenarios:

Scenario # 1 - Explicit Ruby Text Container

```
<span tts:ruby="container" tts:fontSize="24px">
  ...
  <span tts:ruby="textContainer">  <!-- explicit text container -->
    <span tts:ruby="text"/>
  </span>
</span>
```
Here, the explicit ruby text container is assigned 50% of 24px = 12px, and the ruby text content inherits the 12px computed value from the explicit ruby text container.

Scenario # 2 - Implicit Ruby Text Container

```
<span tts:ruby="container" tts:fontSize="24px">
  ...
  <span tts:ruby="textContainer">  <!-- implied text container -->
    <span tts:ruby="text"/>
  </span>
</span>
```
Here, the implied ruby text container is assigned 50% of 24px = 12px, and the ruby text content inherits the 12px computed value from the implied ruby text container.

Looking at these, it seems that the next to last existing paragraph should say (emphasis added for changed text):

>A span element for which the computed value of tts:ruby is textContainer does not inherit tts:fontSize from its parent. Instead, if no tts:fontSize attribute is specified on the ruby text container span element **(whether explicit or implied)**, a value equal to 50% of the value of the computed value of tts:fontSize on the nearest ancestor span element for which the computed value of tts:ruby is container is used; otherwise, the specified value is used.

Then the last paragraph need only say:

>A span element for which the computed value of tts:ruby is text inherits the computed value of tts:fontSize from its parent ruby text container (whether explicit or implied).

**Comment by skynavga** [comment]
Marking this as substantive since a fix is going to require changing normative text.

**Comment by nigelmegitt** [comment]
@skynavga in https://github.com/w3c/ttml2/issues/967#issuecomment-410074068 the two example scenarios seem to be identical. Perhaps one of them needs to be adjusted to clarify the argument?
