### ISSUE TITLE
Clarify that #length-root-container-relative applies to all <length> expressions.

### ISSUE THREAD

**Issue by skynavga** [w3c/ttml2#973]
Add note to E.1.129 that `#length-root-container-relative` applies to all length expressions, e.g., those used with `tts:origin`.

See #972 for the motivation for this clarification.

**Comment by nigelmegitt** [comment]
This needs discussion before going ahead. It is not obvious that it is always desirable, and as mentioned separately recently, it could be that the nature of `rw` and `rh` units is such that a blanket "everywhere" or "nowhere" rule is too coarse. Adding to the agenda.

**Comment by skynavga** [comment]
@nigelmegitt this is marked for processing during PR, not CR3, so we need take no action just now; as for whether `#length-root-container-relative` applies everywhere, that is how it is defined, which is congruent with `#length-cell`, `#length-em`, and `#length-percentage`. Since we do not qualify any of these, I see no need to qualify `#length-root-container-relative`, and, in any case, doing so would be a substantive change, which we will not entertain before TTML2 2e.
