### ISSUE TITLE
Fix CSS derivation of tts:displayAlign.

### ISSUE THREAD

**Issue by skynavga** [w3c/ttml2#976]
CSS mapping should be `align-items`, not `justify-content`. The `tts:displayAlign` property is doing alignment in the BPD dimension, not IPD.

**Comment by nigelmegitt** [comment]
Sorry I didn't pick this up before (poor excuse but it was raised the day my vacation began!) @palemieux would appreciate your view on this - I think we discussed it a long time ago, and you had implementation experience that was relevant and slightly surprising given a first look at the CSS spec.

**Comment by nigelmegitt** [comment]
Specifically, the use of `flex-direction: column;` switches the axes in a way that makes the existing text correct, and the behaviour of `align-items` and `justify-content` is not identical except for a switched axis.

I think this issue should be closed with no change; would like confirmation though.

**Comment by palemieux** [comment]
Below is what imscJS uses today:

```
                    dom_element.style.display = "flex";
                    dom_element.style.flexDirection = "column";


                    if (attr === "before") {

                        dom_element.style.justifyContent = "flex-start";

                    } else if (attr === "center") {

                        dom_element.style.justifyContent = "center";

                    } else if (attr === "after") {

                        dom_element.style.justifyContent = "flex-end";
                    }
```

**Comment by skynavga** [comment]
Closed without change per imsc.js usage of justify-content.

**Comment by nigelmegitt** [comment]
Thanks @palemieux and @skynavga .
