### ISSUE TITLE
Clarify that text combination is not defined in a ruby base or text context.

### ISSUE THREAD

**Issue by skynavga** [w3c/ttml2#978]

**Comment by skynavga** [comment]
no; text contain usage is not defined anywhere in a ruby container, which is the equivalent to saying it is not defined in a ruby base or ruby text context;

also, I am not saying it is not permitted, I am saying it is not defined; it may be we wish to define such semantics in the future, but we have not done so yet, which is the point of adding such an editorial clarification

**Comment by palemieux** [comment]
> no; text contain usage is not defined anywhere in a ruby container

You mean _text combination usage_, right?

**Comment by palemieux** [comment]
>  it may be we wish to define such semantics in the future, but we have not done so yet, which is the point of adding such an editorial clarification

This is clearly more than an editorial clarification, and needs to be clarified in 2ED.

In the meantime, the TTWG can reach consensus on a resolution and the test vectors adapted accordingly.

**Comment by palemieux** [comment]
To be sure, I do not object to either prohibiting or leaving undefined the presence of text combination within `<span tts:ruby="container"></span>`.

**Comment by skynavga** [comment]
Yes, text combination. I agree that defining semantics for using text combination in a ruby container would have to be 2Ed or later. The intention of the present issue is to simply add a note saying that text combination is not defined in this context (in the 1Ed).

**Comment by palemieux** [comment]
> The intention of the present issue is to simply add a note saying that text combination is not defined in this context (in the 1Ed).

Although I like the direction of the note, I do not think the current prose supports this editorial note. I would simply capture a consensus resolution on this thread, and defer its implementation until 2ED.

**Comment by skynavga** [comment]
In what way does the current prose define the use of text combination in a ruby container? I contend that it says nothing, and, therefore, is not defined. For example, the following language:

>Further, let N<sub>R</sub> and N<sub>B</sub>, be, respectively, the number of glyph area descendants of these inline areas.

would count all of the glyph areas in a text combination inside a base context as base glyphs instead of counting the outer inline area (in cross-baseline progression orientation) as one base glyph, which would produce incorrect behavior with `withBase` alignment.

**Comment by palemieux** [comment]
> In what way does the current prose define the use of text combination in a ruby container? 

`tts:textCombination` defines semantics.

`tts:ruby` defines semantics.

Neither prohibits their combined use, therefore both semantics apply -- for better or for worse.

> which would produce incorrect behavior with withBase alignment.

... which is why it needs to be corrected in 2ED.

**Comment by palemieux** [comment]
> tts:textCombine defines semantics.

tts:textCombine states that:

* _Combination processing may make use of one or more techniques to obtain the goal of visual combination into an em square of the surrounding vertical text._

* _If none of these techniques are able to achieve the target dimension along the block progression dimension of the containing line area, then this dimension of the containing line area may be increased if permitted by the line stacking strategy in effect._

In other words, the combined text affects the line area like other glyphs on the same line.

The semantic basis for `tts:textCombine` is CSS [text-combine-upright
](https://www.w3.org/TR/css-writing-modes-3/#text-combine-upright)

> tts:ruby defines semantics.

The semantics of `tts:ruby` are those defined in CSS, according to Table 10-1.

[CSS](https://www.w3.org/TR/css-ruby-1/#ruby-layout) specifies that:

* _Ruby annotations associated with the base level are then positioned with respect to their ruby base boxes according to the applicable ruby-position values._

* Each ruby base container is sized and positioned to contain exactly the full height of its ruby bases.

So, the text combination is laid out in the ruby base, generating in the process a ruby base container of a certain dimension, and then the ruby text is laid out relatively to the ruby base container.

What makes `tts:textCombine` in ruby different than, say, doubling the font size of one character within the ruby base container.

See  https://codepen.io/palemieux/pen/NLxRGv

**Comment by skynavga** [comment]
See https://github.com/w3c/ttml2/issues/978#issuecomment-415492472. Further, CSS does not define the presentation semantics of text-combine-upright in a ruby context. It isn't even mentioned in the CSS Ruby Module. And the definition of text-combine-upright similarly does not mention usage in a ruby context. The existence of an implementation that supports such usage does not mean it is defined or sanctioned by the CSS specs. As the author of the TTML2 ruby and text combine features, I can assure you such a use case was not discussed or considered in drafting the current language. That makes it undefined in my book.

**Comment by skynavga** [comment]
Removing ttml.next, leaving here for ttml2 2e processing.
