### ISSUE TITLE
Prohibition of nested xlink:href attributes should not be limited to span elements.

### ISSUE THREAD

**Issue by palemieux** [w3c/ttml2#982]
TTML2 states in 8.1.6:

_If a `span` element specifies an `xlink:href` attribute, then a nested `span` element descendant must not specify an `xlink:href` attribute, and, if it does, then the latter must be ignored for the purpose of presentation or activation processing._

The discussion at https://github.com/w3c/ttml2-tests/issues/121 suggests that such prohibition of  `xlink:href` attribute nesting should extend beyond nested `span` elements.

**Comment by nigelmegitt** [comment]
How far does it go? To _any_ descendant element of a `span`?

**Comment by skynavga** [comment]
yes, but since only span and image employ xlink:href, and since image cannot contain content (like span), then its easy to specify this case (image in span)

**Comment by nigelmegitt** [comment]
OK, it seems that this is a general rule though, so it would be worth expressing as "any descendant element must not specifyan `xlink:href` attribute _etc_" so that if we ever add another element that can be a child of a `span` then we get this for free without having to remember it explicitly.

**Comment by skynavga** [comment]
This is a testable change, so upgrading to substantive.
