### ISSUE TITLE
Change use of type xsd:nonNegativeInteger to <non-negative-integer> for consistency.

### ISSUE THREAD

**Issue by skynavga** [w3c/ttml2#983]
The XML schema data type `xsd:nonNegativeInteger` is used (inconsistently) in the definitions of `chunk` and `isd:sequence`, when other definitions employ the internally defined `<non-negative-integer>`. For the sake of consistency, only one of these syntaxes should be used, namely, the internally defined syntax `<non-negative-integer>`. Note also that the XML schema syntax permits the lexical representation `-0` for zero (0), while the internal definition does not.

**Comment by palemieux** [comment]
See the thread at https://github.com/w3c/imsc/issues/444

**Comment by skynavga** [comment]
Removing ttml.next, leaving here for ttml2 2e processing.
