### ISSUE TITLE
Prohibit zero numerator/denominator in XSD for ttp:displayAspectRatio

### ISSUE THREAD

**Issue by spoeschel** [w3c/ttml2#998]
https://github.com/w3c/ttml2/blob/7a09203ccb1810fb11c4fc2adc68839f8d7de6c5/spec/xsd/ttml2-datatypes.xsd#L147

The pattern regex should be changed to `\p{Nd}+[1-9]\p{Nd}+\s+\p{Nd}+[1-9]\p{Nd}+` to detect the case of a forbidden zero numerator/denominator.

**Comment by skynavga** [comment]
We have historically not use tight data type definitions on the schema to enforce semantic constraints, which zero is one. There are numerous cases where that is the case, so it would not be appropriate to cherry pick this attribute for a change. For example, see also ttp:cellResolution, ttp:frameRateMultiplier, and ttp:pixelAspectRatio, etc.

**Comment by spoeschel** [comment]
OK, I see. Yes, in that case the proposed change would introduce inconsistency. Thanks for the explanation.

**Comment by skynavga** [comment]
BTW, '0 0' is syntactically valid but semantically invalid, since the pattern in 7.2.3 is `<digit>+`.
